### ISSUE TITLE
NPE while loading extensions for tutorial.

### ISSUE THREAD

**Issue by xoltar** [druid-io/druid#1051]
I can't start the history server, or rather I can, but it crashes when trying to download extensions. Perhaps because I'm behind a corporate http proxy? I tried adding appropriate -D defines for proxy (http.proxyServerHost, http.proxyServerPort, https.proxyServerHost, https.proxyServerPort, http.nonProxyHosts), but still get the same result.

2015-01-18 06:28:58,871 INFO [main] io.druid.guice.PropertiesModule - Loading properties from runtime.properties
2015-01-18 06:28:58,907 INFO [main] org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 5.0.1.Final
2015-01-18 06:28:59,458 INFO [main] io.druid.guice.JsonConfigurator - Loaded class[class io.druid.guice.ExtensionsConfig] from props[druid.extensions.] as [ExtensionsConfig{searchCurrentClassloader=true, coordinates=[io.druid.extensions:druid-s3-extensions:0.6.147], localRepository='/home/hadoop/.m2/repository', remoteRepositories=[http://repo1.maven.org/maven2/, https://metamx.artifactoryonline.com/metamx/pub-libs-releases-local]}]
2015-01-18 06:28:59,589 INFO [main] io.druid.initialization.Initialization - Loading extension[io.druid.extensions:druid-s3-extensions:0.6.147] for class[io.druid.cli.CliCommandCreator]
2015-01-18 06:30:39,923 ERROR [main] io.druid.initialization.Initialization - Unable to resolve artifacts for [io.druid.extensions:druid-s3-extensions:jar:0.6.147 (runtime) -> [] < [central (http://repo1.maven.org/maven2/, releases+snapshots),  (https://metamx.artifactoryonline.com/metamx/pub-libs-releases-local, releases+snapshots)]].
java.lang.NullPointerException
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:361)
        at io.tesla.aether.internal.DefaultTeslaAether.resolveArtifacts(DefaultTeslaAether.java:289)
        at io.druid.initialization.Initialization.getClassLoaderForCoordinates(Initialization.java:200)
        at io.druid.initialization.Initialization.getFromExtensions(Initialization.java:142)
        at io.druid.cli.Main.main(Main.java:78)
Exception in thread "main" java.lang.NullPointerException
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:361)
        at io.tesla.aether.internal.DefaultTeslaAether.resolveArtifacts(DefaultTeslaAether.java:289)
        at io.druid.initialization.Initialization.getClassLoaderForCoordinates(Initialization.java:200)
        at io.druid.initialization.Initialization.getFromExtensions(Initialization.java:142)
        at io.druid.cli.Main.main(Main.java:78)

**Comment by xvrl** [comment]
can you try somewhere without a firewall and see if you still have the same problem?
