### ISSUE TITLE
Realtime task with lost segment reported as SUCCESS

### ISSUE THREAD

**Issue by tisonet** [druid-io/druid#1166]
## Problem
Real time task is not handling IOException correctly when persisting segments. Persisiting can fail, e.g. "No space left on device exception", but task finish with SUCCESS status.

## Expected behaviour:
Handle IOException on persisting the segment in all the cases should be to wait and retry for until the handoff succeeds to prevent any data loss.  

## Logs
```
2015-02-28 02:51:45,747 INFO [ssp-auction-2015-02-27T00:00:00.000Z-persist-n-merge] io.druid.segment.IndexMerger - outDir[/data/druid/baseTaskDir/index_realtime_ssp-auction_2015-02-27T00:00:00.000Z_1_0_dmpongod/work/persist/ssp-auction/2
015-02-27T00:00:00.000Z_2015-02-28T00:00:00.000Z/merged/v8-tmp] walked 500,000/29,000,000 rows in 16,455 millis.
2015-02-28 02:51:53,908 ERROR [ssp-auction-2015-02-27T00:00:00.000Z-persist-n-merge] io.druid.segment.realtime.plumber.RealtimePlumber - Failed to persist merged index[ssp-auction]: {class=io.druid.segment.realtime.plumber.RealtimePlumbe
r, exceptionType=class java.io.IOException, exceptionMessage=No space left on device, interval=2015-02-27T00:00:00.000Z/2015-02-28T00:00:00.000Z}
java.io.IOException: No space left on device
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:315)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
        at com.google.common.io.CountingOutputStream.write(CountingOutputStream.java:53)
        at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
        at io.druid.segment.data.VSizeIndexedWriter.write(VSizeIndexedWriter.java:77)
        at io.druid.segment.IndexMerger.makeIndexFiles(IndexMerger.java:652)
        at io.druid.segment.IndexMerger.merge(IndexMerger.java:307)
        at io.druid.segment.IndexMerger.mergeQueryableIndex(IndexMerger.java:169)
        at io.druid.segment.IndexMerger.mergeQueryableIndex(IndexMerger.java:162)
        at io.druid.segment.realtime.plumber.RealtimePlumber$4.doRun(RealtimePlumber.java:348)
        at io.druid.common.guava.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```
```
2015-02-28 02:51:59,505 INFO [task-runner-0] io.druid.indexing.worker.executor.ExecutorLifecycle - Task completed with status: {
  "id" : "index_realtime_ssp-auction_2015-02-27T00:00:00.000Z_1_0_dmpongod",
  "status" : "SUCCESS",
  "duration" : 53328147
}

```

**Comment by nishantmonu51** [comment]
more log lines to give some more context - 
2015-02-28 00:15:00,121 INFO [task-runner-0] io.druid.segment.realtime.plumber.RealtimePlumber - Shutting down...
above log line was before the exception, i.e the task was complete and marked as being shutttingdown.

**Comment by drcrallen** [comment]
@nishantmonu51 : Is that from the same log? the timestamps are WAY off unless one of them is not UTC.

**Comment by tisonet** [comment]
Hi,

logs are attached here: 
https://groups.google.com/forum/#!topic/druid-development/L-8_e7wramI

Next question, why is task shutting down so late? We have daily segment granularity and window 10 minutes. We are using tranquility for scheduling real time task
