### ISSUE TITLE
Cardinality aggregator throws ClassCastException in GroupBy query when queried from realtime node

### ISSUE THREAD

**Issue by haadcode** [druid-io/druid#1227]
When doing the following query **on realtime node**:
```javascript
{
  "queryType": "groupBy",
  "dataSource": "events",
  "granularity": "all",
  "dimensions": ["site"],
  "aggregations": [
    {"type": "count", "fieldName": "userId", "name": "Events"},
    {"type": "cardinality", "fieldNames": ["userId"], "name": "Unique Users", "byRow": true}
  ],
  "intervals": ["2015-03-01T00:00/2015-04-01T00"]
}
```

Druid returns:
```javascript
{ "error" : "java.lang.Double cannot be cast to io.druid.query.aggregation.hyperloglog.HyperLogLogCollector"}
```

Following exception can be found from realtime node's log:
```
java.lang.ClassCastException: java.lang.Double cannot be cast to io.druid.query.aggregation.hyperloglog.HyperLogLogCollector
	at io.druid.query.aggregation.hyperloglog.HyperUniquesAggregator.aggregate(HyperUniquesAggregator.java:46) ~[druid-processing-0.7.0.jar:0.7.0]
	at io.druid.segment.incremental.OnheapIncrementalIndex.addToFacts(OnheapIncrementalIndex.java:169) ~[druid-processing-0.7.0.jar:0.7.0]
	at io.druid.segment.incremental.IncrementalIndex.add(IncrementalIndex.java:431) ~[druid-processing-0.7.0.jar:0.7.0]
	at io.druid.query.groupby.GroupByQueryHelper$3.accumulate(GroupByQueryHelper.java:112) ~[druid-processing-0.7.0.jar:0.7.0]
	at io.druid.query.groupby.GroupByQueryHelper$3.accumulate(GroupByQueryHelper.java:104) ~[druid-processing-0.7.0.jar:0.7.0]
	at com.metamx.common.guava.MappingAccumulator.accumulate(MappingAccumulator.java:39) ~[java-util-0.26.14.jar:?]
	at com.metamx.common.guava.YieldingAccumulators$1.accumulate(YieldingAccumulators.java:32) ~[java-util-0.26.14.jar:?]
	at com.metamx.common.guava.BaseSequence.makeYielder(BaseSequence.java:104) ~[java-util-0.26.14.jar:?]
	at com.metamx.common.guava.BaseSequence.toYielder(BaseSequence.java:81) ~[java-util-0.26.14.jar:?]
	at com.metamx.common.guava.ResourceClosingSequence.toYielder(ResourceClosingSequence.java:41) ~[java-util-0.26.14.jar:?]
	at com.metamx.common.guava.YieldingSequenceBase.accumulate(YieldingSequenceBase.java:34) ~[java-util-0.26.14.jar:?]
	at com.metamx.common.guava.MappedSequence.accumulate(MappedSequence.java:40) ~[java-util-0.26.14.jar:?]
	at io.druid.query.GroupByParallelQueryRunner$1$1.call(GroupByParallelQueryRunner.java:115) ~[druid-processing-0.7.0.jar:0.7.0]
	at io.druid.query.GroupByParallelQueryRunner$1$1.call(GroupByParallelQueryRunner.java:106) ~[druid-processing-0.7.0.jar:0.7.0]
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) ~[?:1.7.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:166) ~[?:1.7.0_25]
	at io.druid.query.PrioritizedExecutorService$PrioritizedListenableFutureTask.run(PrioritizedExecutorService.java:202) ~[druid-processing-0.7.0.jar:0.7.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[?:1.7.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[?:1.7.0_25]
	at java.lang.Thread.run(Thread.java:724) [?:1.7.0_25]
```

The userId dimension is in format: 123456789012345678.
If the queryType is changed from *groupBy* to *timeseries*, the query is successful. If the query is made via broker node, the query is successful. Using Druid 0.7.0.

**Comment by drcrallen** [comment]
Semi-related issue: https://github.com/druid-io/druid/issues/1045

Can you share what the ingestion spec looks like with regards to dimensions and metrics which are in the query?

**Comment by drcrallen** [comment]
Also please include what version you are running in the issue description.

**Comment by haadcode** [comment]
Sure. See the ingestor spec below. I edited the original issue description and bumped the version to the top to make it more visible.

```javascript
[
  {
    "dataSchema" : {
      "dataSource" : "events",
      "parser" : {
        "type" : "string",
        "parseSpec" : {
          "type" : "tsv",
          "delimiter":"\t",
          "timestampSpec" : {
            "column" : "ts",
            "format" : "millis"
          },
          "columns" : ["userId", "cc", "site", "stream", "itemId", "format", "ts"],
          "dimensionsSpec" : {
            "dimensions": ["userId", "cc", "site", "stream", "itemId", "format", "ts"],
            "dimensionExclusions" : [],
            "spatialDimensions" : []
          }
        }
      },
      "metricsSpec" : [{
        "type" : "count",
        "name" : "count"
      }],
      "granularitySpec" : {
        "type" : "uniform",
        "segmentGranularity" : "minute",
        "queryGranularity" : "none"
      }
    },
    "ioConfig" : {
      "type" : "realtime",
      "firehose": {
        "type": "kafka-0.8",
        "consumerProps": {
          "zookeeper.connect": "{{ zookeeper_url }}:2181",
          "zookeeper.connection.timeout.ms" : "15000",
          "zookeeper.session.timeout.ms" : "15000",
          "zookeeper.sync.time.ms" : "5000",
          "group.id": "druid-ingestor",
          "fetch.message.max.bytes" : "1048586",
          "auto.offset.reset": "largest",
          "auto.commit.enable": "false"
        },
        "feed": "campaigns"
      },
      "plumber": {
        "type": "realtime"
      }
    },
    "tuningConfig": {
      "type" : "realtime",
      "maxRowsInMemory": 500000,
      "intermediatePersistPeriod": "PT10m",
      "windowPeriod": "PT60m",
      "basePersistDirectory": "/tmp/realtime/basePersist",
      "rejectionPolicy": {
        "type": "serverTime"
      }
    }
  }
]
```

**Comment by drcrallen** [comment]
@haadcode : Thanks, we are looking into this to try and make sure we understand why userId is showing up as a Double in IncrementalIndex

**Comment by drcrallen** [comment]
I believe the problem here is because the groupBy engine in 0.7.0 finalizes results when it really shouldn't have. Are you able to test against master?

The specific fix is https://github.com/druid-io/druid/pull/1044/files#diff-631de2c7bba9484c3ffd4a58b4cf691eR198 I believe

**Comment by xvrl** [comment]
@haadcode this should have been fixed in the latest release, please reopen if this is still an issue
