### ISSUE TITLE
S3 storage doesn't work with AWS v4 authentication

### ISSUE THREAD

**Issue by haadcode** [druid-io/druid#1278]
Druid can't use S3 buckets that have v4 authentication (AWS4-HMAC-SHA256).

Steps to reproduce:
Create S3 bucket that only supports v4 authentication (eg. location: Frankfurt)
Use that bucket as the deep storage

Result:
Exception in realtime node (see below).

The realtime node's log shows the following exception:
```
2015-04-13T10:52:04,029 INFO [clickse-2015-04-13T09:23:00.000Z-persist-n-merge] io.druid.storage.s3.S3DataSegmentPusher - Pushing S3Object [key=dev/v1/clickse/2015-04-13T09:23:00.000Z_2015-04-13T09:24:00.000Z/2015-04-13T09:23:00.000Z/0/index.zip, bucket=druid-test1, lastModified=null, dataInputStream=null, Metadata={x-amz-acl=bucket-owner-full-control, Content-Length=60270, Content-MD5=vekBQcVybiT/3DFdmxiE8w==, md5-hash=bde90141c5726e24ffdc315d9b1884f3, Content-Type=application/zip}].

2015-04-13T10:52:04,352 ERROR [clickse-2015-04-13T09:23:00.000Z-persist-n-merge] io.druid.segment.realtime.plumber.RealtimePlumber - Failed to persist merged index[clickse]: {class=io.druid.segment.realtime.plumber.RealtimePlumber, exceptionType=class java.io.IOException, exceptionMessage=org.jets3t.service.S3ServiceException: Service Error Message. -- ResponseCode: 400, ResponseStatus: Bad Request, XML Error Message: <?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>[omitted]</RequestId><HostId>[omitted]</HostId></Error>, interval=2015-04-13T09:23:00.000Z/2015-04-13T09:24:00.000Z}

java.io.IOException: org.jets3t.service.S3ServiceException: Service Error Message. -- ResponseCode: 400, ResponseStatus: Bad Request, XML Error Message: <?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>[omitted]</RequestId><HostId>[omitted]/HostId></Error>
	at io.druid.storage.s3.S3DataSegmentPusher.push(S3DataSegmentPusher.java:132) ~[?:?]
	at io.druid.segment.realtime.plumber.RealtimePlumber$4.doRun(RealtimePlumber.java:447) [druid-server-0.7.0.jar:0.7.0]
	at io.druid.common.guava.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:40) [druid-common-0.7.0.jar:0.7.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_25]
	at java.lang.Thread.run(Thread.java:724) [?:1.7.0_25]
Caused by: org.jets3t.service.S3ServiceException: Service Error Message.
	at org.jets3t.service.S3Service.putObject(S3Service.java:2069) ~[jets3t-0.9.1.jar:0.9.1]
	at io.druid.storage.s3.S3DataSegmentPusher$1.call(S3DataSegmentPusher.java:93) ~[?:?]
	at io.druid.storage.s3.S3DataSegmentPusher$1.call(S3DataSegmentPusher.java:77) ~[?:?]
	at com.metamx.common.RetryUtils.retry(RetryUtils.java:38) ~[java-util-0.26.14.jar:?]
	at io.druid.storage.s3.S3Utils.retryS3Operation(S3Utils.java:77) ~[?:?]
	at io.druid.storage.s3.S3DataSegmentPusher.push(S3DataSegmentPusher.java:75) ~[?:?]
	... 5 more
```

**Comment by drcrallen** [comment]
Hi @haadcode what version are you using?

**Comment by drcrallen** [comment]
https://github.com/druid-io/druid/pull/1205

**Comment by haadcode** [comment]
Just saw that there's 0.7.1.1 released. I updated the cluster to use the latest and I don't get the exception anymore. Seems like it's fixed. Sorry for extra work!
