### ISSUE TITLE
Nested groupBy query fails when outer query has multiple aggregators having same "fieldName"

### ISSUE THREAD

**Issue by himanshug** [druid-io/druid#1419]
Group thread:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/druid-user/L4A1iMhzOco/w_5C030krzEJ

Failing Query:
```
{
  "queryType": "groupBy",
  "dataSource":{
    "type": "query",
    "query": {
      "queryType": "groupBy",
      "dataSource": "platform",
      "granularity": "all",
      "dimensions": ["treatment_name", "subject_id", "dim_app_family"],
      "aggregations": [
        { "type": "longSum", "name": "value", "fieldName": "count" }
      ],
      "intervals": [ "2012-01-01T00:00:00.000/2020-01-03T00:00:00.000" ]
    }
  },
  "granularity": "all",
  "dimensions": ["treatment_name", "dim_app_family"],
  "aggregations": [
    { "type": "longSum", "name": "first_moment", "fieldName": "value" },
    { "type": "javascript",
      "name": "second_moment",
      "fieldNames": ["value"],
      "fnAggregate": "function(current, v) { return current + v * v; } ",
      "fnCombine": "function(partialA, partialB) { return partialA + partialB; }",
      "fnReset": "function() { return 0; }"
    }
  ],
  "intervals": [ "2012-01-01T00:00:00.000/2020-01-03T00:00:00.000" ]
}

```

Exception Stacktrace:
```
java.lang.IllegalArgumentException: [value] already defined
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:120)
	at io.druid.query.Queries.verifyAggregations(Queries.java:42)
	at io.druid.query.groupby.GroupByQuery.<init>(GroupByQuery.java:103)
	at io.druid.query.groupby.GroupByQuery$Builder.build(GroupByQuery.java:531)
	at io.druid.query.groupby.GroupByQueryQueryToolChest.mergeGroupByResults(GroupByQueryQueryToolChest.java:160)
```

**Comment by himanshug** [comment]
The problem happens because we end up building a transient groupBy query that adds all
agg.getRequiredColumns() from original outer query which would have same name.
See https://github.com/druid-io/druid/blob/master/processing/src/main/java/io/druid/query/groupby/GroupByQueryQueryToolChest.java#L163
