### ISSUE TITLE
Always fail to run run_example_server.sh 

### ISSUE THREAD

**Issue by IPL** [druid-io/druid#1540]
Always failed to download extensions. I think the reason is that the code is to download 0.8.1-snapshot, but the latest package is still 0.8.0-rc2. There is no 0.8.1-snapshot in https://metamx.artifactoryonline.com/metamx/pub-libs-releases-local.

This will run a stand-alone version of Druid
Please specify an example by its number.
Examples available:
1 - twitter/twitter_realtime.spec - No Description
2 - wikipedia/wikipedia_realtime.spec - No Description
[1] > 2
 
Running command:
+ java -Xmx512m -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Ddruid.realtime.specFile=/Users/Yu/Documents/workspace/druid/services/target/druid-0.8.1-SNAPSHOT/examples/wikipedia/wikipedia_realtime.spec -classpath '/Users/Yu/Documents/workspace/druid/services/target/druid-0.8.1-SNAPSHOT/../config/realtime:/Users/Yu/Documents/workspace/druid/services/target/druid-0.8.1-SNAPSHOT/examples/wikipedia:/Users/Yu/Documents/workspace/druid/services/target/druid-0.8.1-SNAPSHOT/config/_common:/Users/Yu/Documents/workspace/druid/services/target/druid-0.8.1-SNAPSHOT/config/realtime:/Users/Yu/Documents/workspace/druid/services/target/druid-0.8.1-SNAPSHOT/lib/*' io.druid.cli.Main example realtime
2015-07-20T15:18:57,123 INFO [main] io.druid.guice.PropertiesModule - Loading properties from common.runtime.properties
2015-07-20T15:18:57,128 INFO [main] io.druid.guice.PropertiesModule - Loading properties from runtime.properties
Jul 20, 2015 3:18:57 PM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 5.1.3.Final
2015-07-20T15:18:57,862 INFO [main] io.druid.guice.JsonConfigurator - Loaded class[class io.druid.guice.ExtensionsConfig] from props[druid.extensions.] as [ExtensionsConfig{searchCurrentClassloader=true, coordinates=[io.druid.extensions:druid-examples, io.druid.extensions:druid-kafka-eight], defaultVersion='0.8.1-SNAPSHOT', localRepository='/Users/Yu/.m2/repository', remoteRepositories=[https://repo1.maven.org/maven2/, https://metamx.artifactoryonline.com/metamx/pub-libs-releases-local]}]
2015-07-20T15:18:58,088 INFO [main] io.druid.initialization.Initialization - Loading extension[io.druid.extensions:druid-examples] for class[io.druid.cli.CliCommandCreator]
2015-07-20T15:19:03,102 ERROR [main] io.druid.initialization.Initialization - Unable to resolve artifacts for [io.druid.extensions:druid-examples:jar:0.8.1-SNAPSHOT (runtime) -> [] < [ (https://repo1.maven.org/maven2/, releases+snapshots),  (https://metamx.artifactoryonline.com/metamx/pub-libs-releases-local, releases+snapshots)]].
java.lang.NullPointerException
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:361) ~[aether-impl-0.9.0.M2.jar:?]
	at io.tesla.aether.internal.DefaultTeslaAether.resolveArtifacts(DefaultTeslaAether.java:289) ~[tesla-aether-0.0.5.jar:0.0.5]
	at io.druid.initialization.Initialization.getClassLoaderForCoordinates(Initialization.java:253) [druid-server-0.8.1-SNAPSHOT.jar:0.8.1-SNAPSHOT]
	at io.druid.initialization.Initialization.getFromExtensions(Initialization.java:153) [druid-server-0.8.1-SNAPSHOT.jar:0.8.1-SNAPSHOT]
	at io.druid.cli.Main.main(Main.java:76) [druid-services-0.8.1-SNAPSHOT.jar:0.8.1-SNAPSHOT]
Exception in thread "main" java.lang.NullPointerException
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:361)
	at io.tesla.aether.internal.DefaultTeslaAether.resolveArtifacts(DefaultTeslaAether.java:289)
	at io.druid.initialization.Initialization.getClassLoaderForCoordinates(Initialization.java:253)
	at io.druid.initialization.Initialization.getFromExtensions(Initialization.java:153)
	at io.druid.cli.Main.main(Main.java:76)

**Comment by fjy** [comment]
@IPL I believe this issue is caused by your firewall. Have you had a chance to try the new steps created in #1519 ?

**Comment by drcrallen** [comment]
@fjy Do we even publish SNAPSHOT versions?

If pulling from /master @IPL may need to `mvn install` to get the `-SNAPSHOT` jars into the maven local repository.

**Comment by fjy** [comment]
@drcrallen My bad, just noticed this problem is using SNAPSHOTs. No we don't publish snapshots

**Comment by fjy** [comment]
@IPL you will have to build the extensions yourself and install them locally

**Comment by IPL** [comment]
Yeah, got you. mvn install is needed first, then package and run the sample. Thanks.
