### ISSUE TITLE
NoClassDefFoundError after submitting local index task

### ISSUE THREAD

**Issue by guobingkun** [druid-io/druid#1545]
I was getting ```java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream``` after submitting a local wikipedia index task(same one as in the integration tests). I was using the latest code in the master branch.

Here is the stack trace,
```
2015-07-22T19:36:26,175 ERROR [task-runner-0] io.druid.indexing.overlord.ThreadPoolTaskRunner - Uncaught Throwable while running task[IndexTask{id=index_wikipedia_index_test_2015-07-22T19:36:21.081Z, type=index, dataSource=wikipedia_index_test}]
java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream
	at io.druid.indexing.common.task.IndexTask.determinePartitions(IndexTask.java:269) ~[classes/:?]
	at io.druid.indexing.common.task.IndexTask.run(IndexTask.java:193) ~[classes/:?]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:235) [classes/:?]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:214) [classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.FSDataInputStream
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_75]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_75]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_75]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_75]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_75]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[?:1.7.0_75]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_75]
	... 8 more
2015-07-22T19:36:26,183 ERROR [main] io.druid.cli.CliPeon - Error when starting up.  Failing.
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-16.0.1.jar:?]
	at io.druid.indexing.worker.executor.ExecutorLifecycle.join(ExecutorLifecycle.java:162) ~[classes/:?]
	at io.druid.cli.CliPeon.run(CliPeon.java:225) [classes/:?]
	at io.druid.cli.Main.main(Main.java:91) [classes/:?]
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299) ~[guava-16.0.1.jar:?]
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286) ~[guava-16.0.1.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116) ~[guava-16.0.1.jar:?]
	at io.druid.indexing.worker.executor.ExecutorLifecycle.join(ExecutorLifecycle.java:159) ~[classes/:?]
	... 2 more
Caused by: java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream
	at io.druid.indexing.common.task.IndexTask.determinePartitions(IndexTask.java:269) ~[classes/:?]
	at io.druid.indexing.common.task.IndexTask.run(IndexTask.java:193) ~[classes/:?]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:235) ~[classes/:?]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:214) ~[classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[?:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.7.0_75]
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.FSDataInputStream
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_75]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_75]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_75]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_75]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_75]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[?:1.7.0_75]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_75]
	at io.druid.indexing.common.task.IndexTask.determinePartitions(IndexTask.java:269) ~[classes/:?]
	at io.druid.indexing.common.task.IndexTask.run(IndexTask.java:193) ~[classes/:?]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:235) ~[classes/:?]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:214) ~[classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[?:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.7.0_75]
2015-07-22T19:36:26,184 INFO [Thread-42] io.druid.cli.CliPeon - Running shutdown hook
2015-07-22 19:36:26,207 FATAL Unable to register shutdown hook because JVM is shutting down.
```

It looks like ```HadoopDruidIndexerConfig``` triggers classloader to load ```FSDataInputStream```. 
Specifically this line in ```IndexTask```, 
```
hashFunction.hashBytes(HadoopDruidIndexerConfig.jsonMapper.writeValueAsBytes(groupKey))
                          .asBytes()
```

**Comment by pjain1** [comment]
:+1: I am also having the same issue.

**Comment by xvrl** [comment]
If this was working before, we should find out when that regression happened. @guobingkun what's the last version you ran where this worked?

**Comment by guobingkun** [comment]
@xvrl 0.8.0 - Stable is the latest version that works.

**Comment by xvrl** [comment]
@guobingkun any chance you can git bisect and find the offending commit?

**Comment by guobingkun** [comment]
@xvrl Sure, let me investigate.

**Comment by xvrl** [comment]
@guobingkun any updates on this? Since we'll be releasing 0.8.1 soon, it would be nice not to have a known regression in it

**Comment by guobingkun** [comment]
Was busy with other stuff. Will take a look this week.

**Comment by pjain1** [comment]
I investigated a bit and the bug has something to do with this commit - https://github.com/druid-io/druid/pull/1465
As a work around passing in `null` instead of `fs.open(pt)` at https://github.com/gianm/druid/blob/4a3a7dd1adf892f3fda75681e04e10851083ca15/indexing-hadoop/src/main/java/io/druid/indexer/HadoopDruidIndexerConfig.java#L184 does not cause the local index task to fail. I didn't spend much time on it so I am still not sure why `fs.open()` is causing it to fail as this line is not exercised during the local indexing task.

**Comment by xvrl** [comment]
Thanks @pjain1, @gianm do you have any idea what might be broken here?
