### ISSUE TITLE
Archive segment task (and move) fails on glacierized segments (AWS - S3)

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#1565]
There are checks to make sure a segment isn't moving into itself, but the object data cannot be acquired if the object is already glacierized. It instead returns the following error:
```
2015-07-27T18:10:49,154 ERROR [task-runner-0] io.druid.indexing.overlord.ThreadPoolTaskRunner - Exception while running task[ArchiveTask{id=REDACTED, type=archive, dataSource=READACTED}]
io.druid.segment.loading.SegmentLoadingException: Unable to move segment[REDACTED]
    at io.druid.storage.s3.S3DataSegmentMover.move(S3DataSegmentMover.java:101) ~[?:?]
    at io.druid.storage.s3.S3DataSegmentArchiver.archive(S3DataSegmentArchiver.java:51) ~[?:?]
    at io.druid.segment.loading.OmniDataSegmentArchiver.archive(OmniDataSegmentArchiver.java:41) ~[druid-selfcontained-ea0d307.jar:ea0d307]
    at io.druid.indexing.common.task.ArchiveTask.run(ArchiveTask.java:93) ~[druid-selfcontained-ea0d307.jar:ea0d307]
    at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:235) [druid-selfcontained-ea0d307.jar:ea0d307]
    at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:214) [druid-selfcontained-ea0d307.jar:ea0d307]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_80]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_80]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_80]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
Caused by: org.jets3t.service.ServiceException: Request Error.
    at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRequest(RestStorageService.java:424) ~[druid-selfcontained-ea0d307.jar:ea0d307]
...
    ... 9 more
Caused by: org.jets3t.service.impl.rest.HttpException
    at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRequest(RestStorageService.java:423) ~[druid-selfcontained-ea0d307.jar:ea0d307]
    at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRequest(RestStorageService.java:277) ~[druid-selfcontained-ea0d307.jar:ea0d307]
    at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRestHead(RestStorageService.java:1038) ~[druid-selfcontained-ea0d307.jar:ea0d307]
    at org.jets3t.service.impl.rest.httpclient.RestStorageService.getObjectImpl(RestStorageService.java:2250) ~[druid-selfcontained-ea0d307.jar:ea0d307]
    at org.jets3t.service.impl.rest.httpclient.RestStorageService.getObjectDetailsImpl(RestStorageService.java:2179) ~[druid-selfcontained-ea0d307.jar:ea0d307]
    at org.jets3t.service.StorageService.getObjectDetails(StorageService.java:1120) ~[druid-selfcontained-ea0d307.jar:ea0d307]
    at org.jets3t.service.StorageService.getObjectDetails(StorageService.java:575) ~[druid-selfcontained-ea0d307.jar:ea0d307]
    at org.jets3t.service.StorageService.isObjectInBucket(StorageService.java:512) ~[druid-selfcontained-ea0d307.jar:ea0d307]
    at io.druid.storage.s3.S3DataSegmentMover$2.call(S3DataSegmentMover.java:119) ~[?:?]
    at io.druid.storage.s3.S3DataSegmentMover$2.call(S3DataSegmentMover.java:115) ~[?:?]
    at com.metamx.common.RetryUtils.retry(RetryUtils.java:38) ~[druid-selfcontained-ea0d307.jar:ea0d307]
    at io.druid.storage.s3.S3Utils.retryS3Operation(S3Utils.java:86) ~[?:?]
    at io.druid.storage.s3.S3DataSegmentMover.safeMove(S3DataSegmentMover.java:113) ~[?:?]
    at io.druid.storage.s3.S3DataSegmentMover.move(S3DataSegmentMover.java:78) ~[?:?]
    ... 9 more
```

**Comment by drcrallen** [comment]
Suspected to be problem with permissions. Once verified will close.
