### ISSUE TITLE
transient ut failure NamespaceExtractionCacheManagerExecutorsTest

### ISSUE THREAD

**Issue by himanshug** [druid-io/druid#1610]
Build: https://travis-ci.org/druid-io/druid/jobs/74628709
```
Running io.druid.server.namespace.cache.NamespaceExtractionCacheManagerExecutorsTest

Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.494 sec <<< FAILURE! - in io.druid.server.namespace.cache.NamespaceExtractionCacheManagerExecutorsTest

testDelete(io.druid.server.namespace.cache.NamespaceExtractionCacheManagerExecutorsTest)  Time elapsed: 0.049 sec  <<< FAILURE!

java.lang.AssertionError: null

	at org.junit.Assert.fail(Assert.java:86)

	at org.junit.Assert.assertTrue(Assert.java:41)

	at org.junit.Assert.assertTrue(Assert.java:52)

	at io.druid.server.namespace.cache.NamespaceExtractionCacheManagerExecutorsTest.testDelete(NamespaceExtractionCacheManagerExecutorsTest.java:316)

	at io.druid.server.namespace.cache.NamespaceExtractionCacheManagerExecutorsTest.testDelete(NamespaceExtractionCacheManagerExecutorsTest.java:258)
```

**Comment by guobingkun** [comment]
This is a different error I got.
travis URL: https://travis-ci.org/druid-io/druid/jobs/76483691
```
Running io.druid.server.namespace.cache.NamespaceExtractionCacheManagerExecutorsTest
Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 50.326 sec <<< FAILURE! - in io.druid.server.namespace.cache.NamespaceExtractionCacheManagerExecutorsTest
testDelete(io.druid.server.namespace.cache.NamespaceExtractionCacheManagerExecutorsTest)  Time elapsed: 50.009 sec  <<< ERROR!
java.lang.Exception: test timed out after 50000 milliseconds
	at io.druid.server.namespace.cache.NamespaceExtractionCacheManager.removeNamespaceLocalMetadata(NamespaceExtractionCacheManager.java:296)
	at io.druid.server.namespace.cache.NamespaceExtractionCacheManager.delete(NamespaceExtractionCacheManager.java:514)
	at io.druid.server.namespace.cache.OnHeapNamespaceExtractionCacheManager.delete(OnHeapNamespaceExtractionCacheManager.java:99)
	at io.druid.server.namespace.cache.NamespaceExtractionCacheManagerExecutorsTest.testDelete(NamespaceExtractionCacheManagerExecutorsTest.java:333)
	at io.druid.server.namespace.cache.NamespaceExtractionCacheManagerExecutorsTest.testDelete(NamespaceExtractionCacheManagerExecutorsTest.java:258)
```
