### ISSUE TITLE
Setting Processing Buffer Size in Config Has No Effect

### ISSUE THREAD

**Issue by MrAlias** [druid-io/druid#1636]
I'm attempting to running an instance of Druid-0.8.0 as a historical node on a VM with limited memory.

The service is failing to initialize with the following error repeated:

```
1) Not enough direct memory.  Please adjust -XX:MaxDirectMemorySize, druid.processing.buffer.sizeBytes, or druid.processing.numThreads: maxDirectMemory[528,154,624], memoryNeeded[2,147,483,648] = druid.processing.buffer.sizeBytes[1,073,741,824] * ( druid.processing.numThreads[1] + 1 )
  at io.druid.guice.DruidProcessingModule.getIntermediateResultsPool(DruidProcessingModule.java:106)
  at io.druid.guice.DruidProcessingModule.getIntermediateResultsPool(DruidProcessingModule.java:106)
  while locating io.druid.collections.StupidPool<java.nio.ByteBuffer> annotated with @io.druid.guice.annotations.Global()
    for parameter 1 at io.druid.query.groupby.GroupByQueryEngine.<init>(GroupByQueryEngine.java:75)
  at io.druid.guice.QueryRunnerFactoryModule.configure(QueryRunnerFactoryModule.java:83)
  while locating io.druid.query.groupby.GroupByQueryEngine
    for parameter 0 at io.druid.query.groupby.GroupByQueryRunnerFactory.<init>(GroupByQueryRunnerFactory.java:79)
  at io.druid.guice.QueryRunnerFactoryModule.configure(QueryRunnerFactoryModule.java:80)
  while locating io.druid.query.groupby.GroupByQueryRunnerFactory
  while locating io.druid.query.QueryRunnerFactory annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=26, type=MAPBINDER)
  at io.druid.guice.DruidBinders.queryRunnerFactoryBinder(DruidBinders.java:36)
  while locating java.util.Map<java.lang.Class<? extends io.druid.query.Query>, io.druid.query.QueryRunnerFactory>
    for parameter 0 at io.druid.query.DefaultQueryRunnerFactoryConglomerate.<init>(DefaultQueryRunnerFactoryConglomerate.java:34)
  while locating io.druid.query.DefaultQueryRunnerFactoryConglomerate
  at io.druid.guice.StorageNodeModule.configure(StorageNodeModule.java:53)
  while locating io.druid.query.QueryRunnerFactoryConglomerate
    for parameter 1 at io.druid.server.coordination.ServerManager.<init>(ServerManager.java:105)
  at io.druid.cli.CliHistorical$1.configure(CliHistorical.java:76)
  while locating io.druid.server.coordination.ServerManager
  at io.druid.cli.CliHistorical$1.configure(CliHistorical.java:78)
  while locating io.druid.query.QuerySegmentWalker
    for parameter 3 at io.druid.server.QueryResource.<init>(QueryResource.java:90)
  while locating io.druid.server.QueryResource

```

I can solve this error by adjusting the `-XX:MaxDirectMemorySize` size to be larger than the `memoryNeeded` size specified in the error.  However, when I try to reduce or even change the `druid.processing.buffer.sizeBytes` configuration value to fix the problem, this has no effect.  Regardless of what I set this value to in my properties file, the error message will report the value to be `1,073,741,824`.

In digging through the source it looks like this come from the `intermediateComputeSizeBytes` method of the [`DruidProcessingConfig`](https://github.com/druid-io/druid/blob/0.8.0/processing/src/main/java/io/druid/query/DruidProcessingConfig.java) class, which by default returns a static value (`1024 * 1024 * 1024`).  I'm likely missing some implementation  details of this class and method, so I can't say for certain why this is happening, but as it is the value set in the properties file has no effect on the reported buffer size for the storage of intermediate results.

**Comment by fjy** [comment]
@MrAlias How are you setting the config in your properties file?

**Comment by MrAlias** [comment]
Thanks for the reply @fjy. 

I'm running the server using the following command:

```shell
/usr/bin/java -server -Xmx512m -Xms512m -XX:+UseConcMarkSweepGC -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -classpath :/etc/druid/historical.runtime.properties:/etc/druid/common.runtime.properties:/usr/local/lib/druid/lib/* io.druid.cli.Main server historical
```

With:

```
$ ls -lh /etc/druid/
total 8.0K
-rw-r--r-- 1 root root 2.1K Aug 18 09:16 common.runtime.properties
-rw-r--r-- 1 root root 1.1K Aug 17 15:45 historical.runtime.properties
```

***/etc/druid/historical.runtime.properties***
```
# Node Configs
druid.host=10.0.2.15
druid.port=8083
druid.service=druid/historical

# General Configuration
druid.server.maxSize=268435456
druid.server.tier=_default_tier
druid.server.priority=0

# Storing Segments
druid.segmentCache.locations=[{"path":"/tmp/druid/indexCache","maxSize":"10000000000"}]
druid.segmentCache.deleteOnRemove=true
druid.segmentCache.dropSegmentDelayMillis=30000
druid.segmentCache.announceIntervalMillis=5000
druid.segmentCache.numLoadingThreads=1

# Query Configs
druid.server.http.numThreads=10
druid.server.http.maxIdleTime=PT5m

# Processing
druid.processing.buffer.sizeBytes=134217728
druid.processing.formatString=processing-%s
druid.processing.numThreads=1
druid.processing.columnCache.sizeBytes=0

# General Query Configuration
druid.query.groupBy.singleThreaded=false
druid.query.groupBy.maxIntermediateRows=50000
druid.query.groupBy.maxResults=500000

# Search Query Config
druid.query.search.maxSearchLimit=1000

# Caching
druid.historical.cache.useCache=false
druid.historical.cache.populateCache=false
druid.historical.cache.unCacheable=["groupBy", "select"]
```
and

***/etc/druid/common.runtime.properties***
```
# Extensions
druid.extensions.remoteRepositories=["http://repo1.maven.org/maven2/", "https://metamx.artifactoryonline.com/metamx/pub-libs-releases-local"]
druid.extensions.localRepository=~/.m2/repository
druid.extensions.coordinates=[]
druid.extensions.searchCurrentClassloader=true

# Zookeeper
druid.zk.paths.base=/druid
druid.zk.service.host=localhost
druid.zk.service.sessionTimeoutMs=30000
druid.curator.compress=true
druid.zk.paths.base=/druid
druid.discovery.curator.path=/druid/discovery

# Request Logging
druid.request.logging.type=noop

# Enabling Metrics
druid.monitoring.emissionPeriod=PT1m

# Emitting Metrics
druid.emitter=logging
druid.emitter.logging.loggerClass=LoggingEmitter
druid.emitter.logging.logLevel=info

# Metadata Storage
druid.metadata.storage.type=mysql
druid.metadata.storage.connector.connectURI=jdbc:mysql://localhost:3306/druid?characterEncoding=UTF-8
druid.metadata.storage.connector.user=druid
druid.metadata.storage.connector.password=insecure_pass
druid.metadata.storage.connector.createTables=true
druid.metadata.storage.tables.base=druid
druid.metadata.storage.tables.segmentTable=druid_segments
druid.metadata.storage.tables.ruleTable=druid_rules
druid.metadata.storage.tables.configTable=druid_config
druid.metadata.storage.tables.tasks=druid_tasks
druid.metadata.storage.tables.taskLog=druid_taskLog
druid.metadata.storage.tables.taskLock=druid_taskLock
druid.metadata.storage.tables.audit=druid_audit

# Deep Storage
druid.storage.type=local
druid.storage.storageDirectory=/tmp/druid/localStorage

# Caching
druid.cache.type=local
druid.cache.sizeInBytes=0
druid.cache.initialSize=500000
druid.cache.logEvictionCount=0

# Indexing Service Discovery
druid.selectors.indexing.serviceName=druid/overlord

# Announcing Segments
druid.announcer.type=batch
druid.announcer.segmentsPerNode=50
druid.announcer.maxBytesPerNode=524288
```

Thanks to your suggestion I've looked a bit closer at the logging output an noticed that only the *common.runtime.properties* properties file is specified as being loaded:

```
2015-08-18T16:15:19,133 INFO [main] io.druid.guice.PropertiesModule - Loading properties from common.runtime.properties
1.486: [GC1.486: [DefNew: 68160K->6962K(76672K), 0.0206570 secs] 68160K->6962K(515776K), 0.0210040 secs] [Times: user=0.02 sys=0.01, real=0.02 secs] 
2015-08-18T16:15:20,000 INFO [main] io.druid.guice.JsonConfigurator - Loaded class[class io.druid.guice.ExtensionsConfig] from props[druid.extensions.] as [ExtensionsConfig{searchCurrentClassloader=true, coordinates=[], defaultVersion='0.8.0', localRepository='~/.m2/repository', remoteRepositories=[http://repo1.maven.org/maven2/, https://metamx.artifactoryonline.com/metamx/pub-libs-releases-local]}]
2.537: [GC2.537: [DefNew: 75122K->7427K(76672K), 0.0353910 secs] 75122K->9692K(515776K), 0.0357760 secs] [Times: user=0.02 sys=0.02, real=0.04 secs] 
2015-08-18T16:15:21,893 INFO [main] io.druid.guice.JsonConfigurator - Loaded class[class com.metamx.emitter.core.LoggingEmitterConfig] from props[druid.emitter.logging.] as [LoggingEmitterConfig{loggerClass='LoggingEmitter', logLevel='info'}]
2015-08-18T16:15:22,030 INFO [main] io.druid.guice.JsonConfigurator - Loaded class[class io.druid.server.metrics.DruidMonitorSchedulerConfig] from props[druid.monitoring.] as [io.druid.server.metrics.DruidMonitorSchedulerConfig@2af12577]
2015-08-18T16:15:22,047 INFO [main] io.druid.guice.JsonConfigurator - Loaded class[class io.druid.server.metrics.MonitorsConfig] from props[druid.monitoring.] as [MonitorsConfig{monitors=[]}]
2015-08-18T16:15:22,079 INFO [main] io.druid.guice.JsonConfigurator - Loaded class[class io.druid.server.DruidNode] from props[druid.] as [DruidNode{serviceName='druid/historical', host='druid-test', port=8083}]
2015-08-18T16:15:22,115 INFO [main] io.druid.guice.JsonConfigurator - Loaded class[interface io.druid.client.cache.CacheProvider] from props[druid.cache.] as [io.druid.client.cache.LocalCacheProvider@6d29cb02]
2015-08-18T16:15:22,118 INFO [main] io.druid.server.metrics.MetricsModule - Adding monitor[io.druid.client.cache.CacheMonitor@71a79ffb]
2015-08-18T16:15:22,140 INFO [main] io.druid.guice.JsonConfigurator - Loaded class[class io.druid.server.initialization.ServerConfig] from props[druid.server.http.] as [ServerConfig{numThreads=40, maxIdleTime=PT5M}]
2015-08-18T16:15:22,161 INFO [main] org.eclipse.jetty.util.log - Logging initialized @4178ms
4.388: [GC4.388: [DefNew: 75587K->6695K(76672K), 0.0321180 secs] 77852K->10176K(515776K), 0.0324180 secs] [Times: user=0.04 sys=0.00, real=0.05 secs] 
2015-08-18T16:15:22,399 INFO [main] org.skife.config.ConfigurationObjectFactory - Using method itself for [druid.computation.buffer.size, ${base_path}.buffer.sizeBytes] on [io.druid.query.DruidProcessingConfig#intermediateComputeSizeBytes()]
2015-08-18T16:15:22,409 INFO [main] org.skife.config.ConfigurationObjectFactory - Using method itself for [${base_path}.numThreads] on [io.druid.query.DruidProcessingConfig#getNumThreads()]
2015-08-18T16:15:22,409 INFO [main] org.skife.config.ConfigurationObjectFactory - Using method itself for [${base_path}.columnCache.sizeBytes] on [io.druid.query.DruidProcessingConfig#columnCacheSizeBytes()]
2015-08-18T16:15:22,410 INFO [main] org.skife.config.ConfigurationObjectFactory - Assigning default value [processing-%s] for [${base_path}.formatString] on [com.metamx.common.concurrent.ExecutorServiceConfig#getFormatString()]
2015-08-18T16:15:22,535 INFO [main] io.druid.guice.JsonConfigurator - Loaded class[class io.druid.query.search.search.SearchQueryConfig] from props[druid.query.search.] as [io.druid.query.search.search.SearchQueryConfig@1f748c4]
2015-08-18T16:15:22,542 INFO [main] io.druid.guice.JsonConfigurator - Loaded class[class io.druid.query.groupby.GroupByQueryConfig] from props[druid.query.groupBy.] as [io.druid.query.groupby.GroupByQueryConfig@1f5d282a]
2015-08-18T16:15:22,553 INFO [main] io.druid.guice.JsonConfigurator - Loaded class[class io.druid.client.cache.CacheConfig] from props[druid.historical.cache.] as [io.druid.client.cache.CacheConfig@3e0db8d8]
2015-08-18T16:15:22,561 INFO [main] io.druid.guice.JsonConfigurator - Loaded class[interface io.druid.server.log.RequestLoggerProvider] from props[druid.request.logging.] as [io.druid.server.log.NoopRequestLoggerProvider@7f322d18]
2015-08-18T16:15:22,565 ERROR [main] io.druid.cli.CliHistorical - Error when starting up.  Failing.
com.google.inject.ProvisionException: Guice provision errors:

...
```

I tried combining all the configuration values into *common.runtime.properties* and it appeared to fix the issue, as the service no longer failed with the memory error.

I likely have missed something, but I did think that it was possible to specify configurations in different properties files.  I remember doing this when I was first playing around with the shipped druid examples.  Is there a reason */etc/druid/historical.runtime.properties* would not be loaded given this setup?

**Comment by fjy** [comment]
@MrAlias I wonder if this is a silly bug in the code, but what happens if you rename historical.runtime.properties to just runtime.properties and make sure it comes after the common.runtime.properties in the classpath?

**Comment by MrAlias** [comment]
Yes! That fixes it:

```
$ /usr/bin/java -server -Xmx512m -Xms512m -XX:+UseConcMarkSweepGC -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -classpath :/etc/druid/common.runtime.properties:/etc/druid/runtime.properties:/usr/local/lib/druid/lib/* io.druid.cli.Main server historical
2015-08-18T16:50:45,651 INFO [main] io.druid.guice.PropertiesModule - Loading properties from common.runtime.properties
2015-08-18T16:50:45,664 INFO [main] io.druid.guice.PropertiesModule - Loading properties from runtime.properties
1.517: [GC1.517: [DefNew: 68160K->6967K(76672K), 0.0202210 secs] 68160K->6967K(515776K), 0.0206200 secs] [Times: user=0.03 sys=0.00, real=0.02 secs] 
2015-08-18T16:50:46,517 INFO [main] io.druid.guice.JsonConfigurator - Loaded class[class io.druid.guice.ExtensionsConfig] from props[druid.extensions.] as [ExtensionsConfig{searchCurrentClassloader=true, coordinates=[], defaultVersion='0.8.0', localRepository='~/.m2/repository', remoteRepositories=[http://repo1.maven.org/maven2/, https://metamx.artifactoryonline.com/metamx/pub-libs-releases-local]}]

...
```

This ran without errors and looks to be loading the configuration in */etc/druid/runtime.properties* fine.
