### ISSUE TITLE
Running index task->NPE in Peon run

### ISSUE THREAD

**Issue by nmarasoiu** [druid-io/druid#1803]
Hi,
I run master via docker build made available by druid-io.

Initially I got a DirectMemory capacity issue, so I configured supervisor to start the jvms with 
-Ddruid.indexer.fork.property.druid.processing.buffer.sizeBytes=512000
-Ddruid.processing.buffer.sizeBytes=512000

Now another exception occurs:
```
2015-10-05T14:12:59,209 INFO [main] io.druid.indexing.common.actions.LocalTaskActionClient - Performing action for task[index_wikipedia_2015-10-05T14:12:53.318Z]: LockTryAcquireAction{interval=2013-08-31T
00:00:00.000Z/2013-09-01T00:00:00.000Z}
2015-10-05T14:12:59,211 WARN [main] io.druid.guice.LifecycleScope - Caught exception when trying to create a[Key[type=io.druid.indexing.worker.executor.ExecutorLifecycle, annotation=[none]]]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
        at com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler.start(Lifecycle.java:325) ~[druid-services-master-selfcontained.jar:master]
        at com.metamx.common.lifecycle.Lifecycle.addMaybeStartHandler(Lifecycle.java:230) ~[druid-services-master-selfcontained.jar:master]
        at com.metamx.common.lifecycle.Lifecycle.addMaybeStartManagedInstance(Lifecycle.java:176) ~[druid-services-master-selfcontained.jar:master]
        at io.druid.guice.LifecycleScope$1.get(LifecycleScope.java:76) [druid-services-master-selfcontained.jar:master]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) [druid-services-master-selfcontained.jar:master]
        at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:1005) [druid-services-master-selfcontained.jar:master]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1051) [druid-services-master-selfcontained.jar:master]
        at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:1001) [druid-services-master-selfcontained.jar:master]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1040) [druid-services-master-selfcontained.jar:master]
        at io.druid.cli.CliPeon.run(CliPeon.java:225) [druid-services-master-selfcontained.jar:master]
        at io.druid.cli.Main.main(Main.java:91) [druid-services-master-selfcontained.jar:master]
Caused by: com.metamx.common.ISE: Failed to run isReady
        at io.druid.indexing.worker.executor.ExecutorLifecycle.start(ExecutorLifecycle.java:124) ~[druid-services-master-selfcontained.jar:master]
        ... 15 more
Caused by: com.metamx.common.ISE: Unable to grant lock to inactive Task [index_wikipedia_2015-10-05T14:12:53.318Z]
        at io.druid.indexing.overlord.TaskLockbox.tryLock(TaskLockbox.java:224) ~[druid-services-master-selfcontained.jar:master]
        at io.druid.indexing.overlord.TaskLockbox.tryLock(TaskLockbox.java:201) ~[druid-services-master-selfcontained.jar:master]
        at io.druid.indexing.common.actions.LockTryAcquireAction.perform(LockTryAcquireAction.java:58) ~[druid-services-master-selfcontained.jar:master]
        at io.druid.indexing.common.actions.LockTryAcquireAction.perform(LockTryAcquireAction.java:29) ~[druid-services-master-selfcontained.jar:master]
        at io.druid.indexing.common.actions.LocalTaskActionClient.submit(LocalTaskActionClient.java:62) ~[druid-services-master-selfcontained.jar:master]
        at io.druid.indexing.common.task.AbstractFixedIntervalTask.isReady(AbstractFixedIntervalTask.java:89) ~[druid-services-master-selfcontained.jar:master]
        at io.druid.indexing.worker.executor.ExecutorLifecycle.start(ExecutorLifecycle.java:120) ~[druid-services-master-selfcontained.jar:master]
        ... 15 more
2015-10-05T14:12:59,217 ERROR [main] io.druid.cli.CliPeon - Error when starting up.  Failing.
java.lang.NullPointerException
        at io.druid.cli.CliPeon.run(CliPeon.java:225) [druid-services-master-selfcontained.jar:master]
        at io.druid.cli.Main.main(Main.java:91) [druid-services-master-selfcontained.jar:master]
```

**Comment by chrishawkins** [comment]
I'm getting this error as well, did you ever resolve it?

**Comment by fjy** [comment]
@nmarasoiu Apologies for missing this issue. We respond much faster in the user groups :P
@chrishawkins what version of Druid are you using? Can you post the full logs?

**Comment by chrishawkins** [comment]
@fiy Sure thing. https://gist.github.com/chrishawkins/e7868de9013120ebbe70
I am currently on the master branch as that is what the Druid-Docker project checks out by default.

**Comment by xvrl** [comment]
@chrishawkins do you have the full json of the task you are submitting?

**Comment by chrishawkins** [comment]
@xvrl Sure, it is the exact sample provided on the website, also here: https://gist.github.com/chrishawkins/132c2bb9339d08044e69

**Comment by xvrl** [comment]
@chrishawkins @fjy @nmarasoiu it looks like the problem is caused by settings `-Ddruid.peon.mode=local` on the overlord. The same problem happens when running outside of docker.

**Comment by fjy** [comment]
@xvrl that configuration is neither documented nor officially supported. Why are we setting it in docker?

**Comment by gianm** [comment]
Does it work if that's changed to `remote` (or just removed)?

**Comment by gianm** [comment]
If you have an overlord the peon should be talking to that rather than trying to access the metadata store and stuff directly, which is what `druid.peon.mode=local` does.

**Comment by xvrl** [comment]
@gianm it was probably leftover from something else, the fact that the overlord blindly passes down properties to the peon caused this to break. Maybe we should filter properties to avoid things like that? not sure.

**Comment by chrishawkins** [comment]
@xvrl @fjy Thanks! Appreciate it!
