### ISSUE TITLE
json parse fail when json format data has control-code in string [bug]

### ISSUE THREAD

**Issue by exitNA** [druid-io/druid#1840]
for example:
the input data is : {"test":"aaa\x01aaa"},when import this message to druid, an exception occured,that is:

2015-10-20T14:58:29,034 ERROR [task-runner-0] io.druid.indexing.overlord.ThreadPoolTaskRunner - Exception while running task[IndexTask{id=index_auction_log_2015-10-20T14:58:23.260+08:00, type=index, dataSource=auction_log}]
com.metamx.common.parsers.ParseException: Unable to parse row [....]
	at com.metamx.common.parsers.JSONParser.parse(JSONParser.java:147) ~[java-util-0.27.0.jar:?]
	at io.druid.data.input.impl.StringInputRowParser.parseString(StringInputRowParser.java:86) ~[druid-api-0.3.9.jar:0.3.9]
	at io.druid.data.input.impl.StringInputRowParser.parse(StringInputRowParser.java:91) ~[druid-api-0.3.9.jar:0.3.9]
	at io.druid.data.input.impl.FileIteratingFirehose.nextRow(FileIteratingFirehose.java:54) ~[druid-api-0.3.9.jar:0.3.9]
	at io.druid.indexing.common.task.IndexTask.getDataIntervals(IndexTask.java:228) ~[druid-indexing-service-0.8.1.jar:0.8.1]
	at io.druid.indexing.common.task.IndexTask.run(IndexTask.java:184) ~[druid-indexing-service-0.8.1.jar:0.8.1]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:235) [druid-indexing-service-0.8.1.jar:0.8.1]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:214) [druid-indexing-service-0.8.1.jar:0.8.1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal unquoted character ((CTRL-CHAR, code 1)): has to be escaped using backslash to be included in string value
 at [Source:...line: 1, column: 718]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419) ~[jackson-core-2.4.4.jar:2.4.4]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508) ~[jackson-core-2.4.4.jar:2.4.4]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._throwUnquotedSpace(ParserMinimalBase.java:472) ~[jackson-core-2.4.4.jar:2.4.4]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString2(ReaderBasedJsonParser.java:1613) ~[jackson-core-2.4.4.jar:2.4.4]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString(ReaderBasedJsonParser.java:1585) ~[jackson-core-2.4.4.jar:2.4.4]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText(ReaderBasedJsonParser.java:233) ~[jackson-core-2.4.4.jar:2.4.4]
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:224) ~[jackson-databind-2.4.4.jar:2.4.4]
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:62) ~[jackson-databind-2.4.4.jar:2.4.4]
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:14) ~[jackson-databind-2.4.4.jar:2.4.4]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3066) ~[jackson-databind-2.4.4.jar:2.4.4]
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1833) ~[jackson-databind-2.4.4.jar:2.4.4]
	at com.metamx.common.parsers.JSONParser.parse(JSONParser.java:115) ~[java-util-0.27.0.jar:?]
	... 11 more

**Comment by himanshug** [comment]
error is coming from underlying parser used by druid, most likely, it is not valid json, you probably need to use `\u` instead of `\x`

**Comment by xvrl** [comment]
I concur with @himanshug, http://rfc7159.net/rfc7159#rfc.section.7 states control characters need to be escaped.
