### ISSUE TITLE
python recursion depth exceeded in post-index-task

### ISSUE THREAD

**Issue by milimetric** [druid-io/druid#1856]
I'm working on loading a big file - 35GB with a hadoop indexer copied from the Imply quickstart.  This succeeded on smaller pieces of the same file, and I used `ignoreInvalidRows` to make sure it doesn't fail.  But this time, it went on for 81 minutes and at the end said:

```
Task index_hadoop_pageviews-per-article_2015-10-24T13:15:53.608Z still running...
Task index_hadoop_pageviews-per-article_2015-10-24T13:15:53.608Z still running...
Task index_hadoop_pageviews-per-article_2015-10-24T13:15:53.608Z still running...
Traceback (most recent call last):
  File "bin/post-index-task", line 85, in <module>
    main()
  File "bin/post-index-task", line 81, in main
    task_status = await_task_completion(args, task_id, complete_timeout_at)
  File "bin/post-index-task", line 60, in await_task_completion
    return await_task_completion(args, task_id, timeout_at)
...
... [all line 60 in await_task_completion] ...
...
  File "bin/post-index-task", line 60, in await_task_completion
    return await_task_completion(args, task_id, timeout_at)
  File "bin/post-index-task", line 50, in await_task_completion
    response = urllib2.urlopen(req, None, response_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1194, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 793, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    sock = socket(af, socktype, proto)
  File "/usr/lib/python2.7/socket.py", line 187, in __init__
    _sock = _realsocket(family, type, proto)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

The index job I posted was:

```
{
  "type" : "index_hadoop",
  "spec" : {
    "ioConfig" : {
      "type" : "hadoop",
      "inputSpec" : {
        "type" : "static",
        "paths" : "/srv/for-druid/pageviews.2015.10.14.hourly.json"
      }
    },
    "dataSchema" : {
      "dataSource" : "pageviews-per-article",
      "granularitySpec" : {
        "type" : "uniform",
        "segmentGranularity" : "day",
        "queryGranularity" : "none",
        "intervals" : ["2015-10-14/2015-10-15"]
      },
      "parser" : {
        "type" : "string",
        "parseSpec" : {
          "format" : "json",
          "dimensionsSpec" : {
            "dimensions" : [
              "project",
              "access",
              "agent",
              "article"
            ]
          },
          "timestampSpec" : {
            "format" : "auto",
            "column" : "time"
          }
        }
      },
      "metricsSpec" : [
        {
          "name" : "view_count",
          "type" : "doubleSum",
          "fieldName": "view_count"
        }
      ]
    },
    "tuningConfig" : {
      "type" : "hadoop",
      "ignoreInvalidRows" : true,
      "partitionsSpec" : {
        "type" : "hashed",
        "targetPartitionSize" : 5000000
      },
      "jobProperties" : {}
    }
  }
}
```

Interestingly, `/tmp/hadoop-root` is still growing after the job finished, it's now at 7GB.

**Comment by milimetric** [comment]
Oh, I see, I looked at that python code.  Indexing is still happening, but the file is so huge, the recursive calls to `await_task_completion` caused just the python to error out.  My suggestion there is: instead of the recursive call, just turn it into a `while True:` loop.  You can break out of it when you need (timeout, error, etc.) and then you're not pushing calls on the stack.

**Comment by fjy** [comment]
@milimetric Thanks for the feedback! We had tested with some large files but I guess this bug sneaked through. We'll be sure to fix it for next release.

**Comment by gianm** [comment]
hey @milimetric, this is fixed in master and will be in the next imply release. Fwiw this script is not actually part of Druid so the issue would be better filed in https://github.com/implydata/distribution. But I won't blame you for that because we hadn't actually made that repo public until just now :P

**Comment by milimetric** [comment]
Makes sense, thanks guys.
