### ISSUE TITLE
Successful index task logs errors on shutdown

### ISSUE THREAD

**Issue by xvrl** [druid-io/druid#1962]
Running the example wikipedia task causes the task logs to have errors on task shutdown. The task completes successfully, so the errors are not a problem in itself, but still an annoyance that might confuse someone.

```
2015-11-12T21:41:02,181 INFO [Thread-42] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void io.druid.curator.discovery.ServerDiscoverySelector.stop() throws java.io.IOException] on object[io.druid.curator.discovery.ServerDiscoverySelector@63bde6c2].
2015-11-12T21:41:02,181 ERROR [Thread-42] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Exception when stopping method[public void io.druid.curator.discovery.ServerDiscoverySelector.stop() throws java.io.IOException] on object[io.druid.curator.discovery.ServerDiscoverySelector@63bde6c2]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler.stop(Lifecycle.java:337) [druid-services-master-selfcontained.jar:master]
	at com.metamx.common.lifecycle.Lifecycle.stop(Lifecycle.java:261) [druid-services-master-selfcontained.jar:master]
	at io.druid.cli.CliPeon$2.run(CliPeon.java:220) [druid-services-master-selfcontained.jar:master]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.IllegalStateException: Already closed or has not been started
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[druid-services-master-selfcontained.jar:master]
	at org.apache.curator.x.discovery.details.ServiceCacheImpl.close(ServiceCacheImpl.java:104) ~[druid-services-master-selfcontained.jar:master]
	at org.apache.curator.x.discovery.details.ServiceProviderImpl.close(ServiceProviderImpl.java:78) ~[druid-services-master-selfcontained.jar:master]
	at io.druid.curator.discovery.ServerDiscoverySelector.stop(ServerDiscoverySelector.java:122) ~[druid-services-master-selfcontained.jar:master]
	... 8 more
2015-11-12T21:41:02,194 INFO [Thread-42] io.druid.curator.CuratorModule - Stopping Curator
2015-11-12T21:41:02,194 INFO [Thread-42] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void com.metamx.http.client.NettyHttpClient.stop()] on object[com.metamx.http.client.NettyHttpClient@771d1ffb].
2015-11-12T21:41:02,195 INFO [Thread-42] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void com.metamx.metrics.MonitorScheduler.stop()] on object[com.metamx.metrics.MonitorScheduler@5f780a86].
2015-11-12T21:41:02,195 INFO [Thread-42] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void com.metamx.emitter.service.ServiceEmitter.close() throws java.io.IOException] on object[com.metamx.emitter.service.ServiceEmitter@53dad875].
2015-11-12T21:41:02,196 INFO [Thread-42] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void io.druid.initialization.Log4jShutterDownerModule$Log4jShutterDowner.stop()] on object[io.druid.initialization.Log4jShutterDownerModule$Log4jShutterDowner@22590e3e].
2015-11-12T21:41:02,196 ERROR [Thread-42] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Exception when stopping method[public void io.druid.initialization.Log4jShutterDownerModule$Log4jShutterDowner.stop()] on object[io.druid.initialization.Log4jShutterDownerModule$Log4jShutterDowner@22590e3e]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler.stop(Lifecycle.java:337) [druid-services-master-selfcontained.jar:master]
	at com.metamx.common.lifecycle.Lifecycle.stop(Lifecycle.java:261) [druid-services-master-selfcontained.jar:master]
	at io.druid.cli.CliPeon$2.run(CliPeon.java:220) [druid-services-master-selfcontained.jar:master]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.IllegalStateException: Expected state [STARTED] found [STOPPED]
	at io.druid.common.config.Log4jShutdown.stop(Log4jShutdown.java:102) ~[druid-services-master-selfcontained.jar:master]
	at io.druid.initialization.Log4jShutterDownerModule$Log4jShutterDowner.stop(Log4jShutterDownerModule.java:109) ~[druid-services-master-selfcontained.jar:master]
	... 8 more
```

**Comment by drcrallen** [comment]
Possibly fixed by https://github.com/metamx/java-util/pull/28

**Comment by heamon7** [comment]
Hi,I came across the same error with Imply 1.0.2.
I want to know how can I solve the problem.
Is there a patch or a newer version of Imply?

**Comment by drcrallen** [comment]
fix in master
