### ISSUE TITLE
Non-deterministic io.druid.query.extraction.namespace.TestKafkaExtractionCluster testSimpleRename

### ISSUE THREAD

**Issue by fjy** [druid-io/druid#2113]
```
Running io.druid.query.extraction.namespace.TestKafkaExtractionCluster
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.488 sec <<< FAILURE! - in io.druid.query.extraction.namespace.TestKafkaExtractionCluster
testSimpleRename(io.druid.query.extraction.namespace.TestKafkaExtractionCluster)  Time elapsed: 0.088 sec  <<< FAILURE!
java.lang.AssertionError: expected:<bar> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.druid.query.extraction.namespace.TestKafkaExtractionCluster.testSimpleRename(TestKafkaExtractionCluster.java:352)
Running io.druid.query.extraction.namespace.KafkaExtractionNamespaceTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in io.druid.query.extraction.namespace.KafkaExtractionNamespaceTest
```

**Comment by fjy** [comment]
@drcrallen This test doesn't even work in IntelliJ


com.google.inject.CreationException: Guice creation errors:

1) Map injection failed due to duplicated key "io.druid.query.extraction.namespace.JDBCExtractionNamespace"
  at com.google.inject.multibindings.MapBinder$RealMapBinder$1.initialize(MapBinder.java:357)
  at io.druid.server.namespace.NamespacedExtractionModule.getNamespaceFactoryMapBinder(NamespacedExtractionModule.java:91)

2) Map injection failed due to duplicated key "offheap"
  at com.google.inject.multibindings.MapBinder$RealMapBinder$1.initialize(MapBinder.java:357)
  at io.druid.guice.PolyBind.optionBinder(PolyBind.java:113)

2 errors

	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:448)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:176)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at io.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:322)
	at io.druid.query.extraction.namespace.TestKafkaExtractionCluster.setupStatic(TestKafkaExtractionCluster.java:227)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
