### ISSUE TITLE
Non-deterministic io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest

### ISSUE THREAD

**Issue by fjy** [druid-io/druid#2116]
Tests run: 20, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.776 sec <<< FAILURE! - in io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest
testReverseFunction[[.dat]:[io.druid.server.namespace.cache.OffHeapNamespaceExtractionCacheManager]](io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest)  Time elapsed: 0.106 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:621)
	at org.junit.Assert.assertNotNull(Assert.java:631)
	at io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest.testReverseFunction(URIExtractionNamespaceFunctionFactoryTest.java:325)

**Comment by fjy** [comment]
Duplicated by #2115
