### ISSUE TITLE
Non-deterministic io.druid.server.coordinator.DruidCoordinatorTest testCoordinatorRun

### ISSUE THREAD

**Issue by fjy** [druid-io/druid#2117]
Running io.druid.server.coordinator.DruidCoordinatorTest
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.251 sec <<< FAILURE! - in io.druid.server.coordinator.DruidCoordinatorTest
testCoordinatorRun(io.druid.server.coordinator.DruidCoordinatorTest)  Time elapsed: 3.118 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at io.druid.server.coordinator.DruidCoordinatorTest.testCoordinatorRun(DruidCoordinatorTest.java:351)

**Comment by fjy** [comment]
Fixed by #2153

**Comment by gianm** [comment]
reopening, @acslk saw this on master recently.

**Comment by acslk** [comment]
Travis failed this test on Java 8, but not Java 7. The failure cannot be reproduced on local machine or another travis test.
The failed assertion is "Assert.assertEquals(1L, dataSourceMap.get(dataSource).get());" which is the same as the one reported in this issue.

https://travis-ci.org/druid-io/druid/jobs/129883914

io.druid.server.coordinator.DruidCoordinatorTest
testCoordinatorRun(io.druid.server.coordinator.DruidCoordinatorTest)  Time elapsed: 1.794 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:743)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:555)
at org.junit.Assert.assertEquals(Assert.java:542)
at io.druid.server.coordinator.DruidCoordinatorTest.testCoordinatorRun(DruidCoordinatorTest.java:374)

**Comment by pjain1** [comment]
see - https://github.com/druid-io/druid/pull/2967
