### ISSUE TITLE
ExecutorLifecycle stop not idempotent

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#2122]
The following error appears during shutdown now
```
2015-12-18T12:19:51,978 ERROR [Thread-77] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Exception when stopping method[public void io.druid.indexing.worker.executor.ExecutorLifecycle.stop() throws java.lang.Exception] on object[io.druid.indexing.worker.executor.ExecutorLifecycle@61911947]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler.stop(Lifecycle.java:337) [druid-selfcontained-0.8.3-rc2-mmx1.jar:0.8.3-rc2-mmx1]
	at com.metamx.common.lifecycle.Lifecycle.stop(Lifecycle.java:261) [druid-selfcontained-0.8.3-rc2-mmx1.jar:0.8.3-rc2-mmx1]
	at io.druid.cli.CliPeon$2.run(CliPeon.java:241) [druid-selfcontained-0.8.3-rc2-mmx1.jar:0.8.3-rc2-mmx1]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.nio.channels.ClosedChannelException
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:58) ~[?:1.8.0_66]
	at io.druid.indexing.worker.executor.ExecutorLifecycle.stop(ExecutorLifecycle.java:220) ~[druid-selfcontained-0.8.3-rc2-mmx1.jar:0.8.3-rc2-mmx1]
	... 8 more
```

**Comment by drcrallen** [comment]
Should be solved by https://github.com/druid-io/druid/pull/2063 via https://github.com/metamx/java-util/pull/28

**Comment by drcrallen** [comment]
Note this is probably not a regression, but simply exposing prior behavior in the logs since https://github.com/druid-io/druid/pull/1387
