### ISSUE TITLE
ServerDiscoverySelector.stop() not idempotent

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#2123]
```
2015-12-18T12:19:51,982 ERROR [Thread-77] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Exception when stopping method[public void io.druid.curator.discovery.ServerDiscoverySelector.stop() throws java.io.IOException] on object[io.druid.curator.discovery.ServerDiscoverySelector@26e0d39c]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler.stop(Lifecycle.java:337) [druid-selfcontained-0.8.3-rc2-mmx1.jar:0.8.3-rc2-mmx1]
	at com.metamx.common.lifecycle.Lifecycle.stop(Lifecycle.java:261) [druid-selfcontained-0.8.3-rc2-mmx1.jar:0.8.3-rc2-mmx1]
	at io.druid.cli.CliPeon$2.run(CliPeon.java:241) [druid-selfcontained-0.8.3-rc2-mmx1.jar:0.8.3-rc2-mmx1]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.IllegalStateException: Already closed or has not been started
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[druid-selfcontained-0.8.3-rc2-mmx1.jar:0.8.3-rc2-mmx1]
	at org.apache.curator.x.discovery.details.ServiceCacheImpl.close(ServiceCacheImpl.java:104) ~[druid-selfcontained-0.8.3-rc2-mmx1.jar:0.8.3-rc2-mmx1]
	at org.apache.curator.x.discovery.details.ServiceProviderImpl.close(ServiceProviderImpl.java:78) ~[druid-selfcontained-0.8.3-rc2-mmx1.jar:0.8.3-rc2-mmx1]
	at io.druid.curator.discovery.ServerDiscoverySelector.stop(ServerDiscoverySelector.java:122) ~[druid-selfcontained-0.8.3-rc2-mmx1.jar:0.8.3-rc2-mmx1]
	... 8 more
```

**Comment by drcrallen** [comment]
Should be solved by https://github.com/druid-io/druid/pull/2063 via https://github.com/metamx/java-util/pull/28

**Comment by drcrallen** [comment]
Note this is probably not a regression, but simply exposing prior behavior in the logs since https://github.com/druid-io/druid/pull/1387
