### ISSUE TITLE
Non-deterministic io.druid.client.CoordinatorServerViewTest

### ISSUE THREAD

**Issue by jon-wei** [druid-io/druid#2128]
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 9.822 sec <<< FAILURE! - in io.druid.client.CoordinatorServerViewTest
testMultipleServerAddedRemovedSegment(io.druid.client.CoordinatorServerViewTest)  Time elapsed: 1.158 sec  <<< ERROR!
org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /druid/segments/locahost:0
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:727)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:703)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107)
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:699)
	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:477)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:467)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:447)
	at org.apache.curator.framework.imps.CreateBuilderImpl$4.forPath(CreateBuilderImpl.java:355)
	at org.apache.curator.framework.imps.CreateBuilderImpl$4.forPath(CreateBuilderImpl.java:291)
	at io.druid.client.CoordinatorServerViewTest.setupZNodeForServer(CoordinatorServerViewTest.java:363)
	at io.druid.client.CoordinatorServerViewTest.testMultipleServerAddedRemovedSegment(CoordinatorServerViewTest.java:171)

**Comment by jon-wei** [comment]
Example travis failure:

https://travis-ci.org/druid-io/druid/jobs/97770822

**Comment by gianm** [comment]
still occurs post #2132: https://travis-ci.org/druid-io/druid/jobs/98268514

**Comment by guobingkun** [comment]
https://github.com/druid-io/druid/pull/2137 is another effort on fixing this.
