### ISSUE TITLE
Transient failure on io.druid.indexing.overlord.RemoteTaskRunnerTest.testRunExistingTaskThatHasntStartedRunning

### ISSUE THREAD

**Issue by fjy** [druid-io/druid#2185]
testRunExistingTaskThatHasntStartedRunning(io.druid.indexing.overlord.RemoteTaskRunnerTest)  Time elapsed: 2.731 sec  <<< FAILURE!
java.lang.AssertionError: expected:<SUCCESS> but was:<FAILED>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.druid.indexing.overlord.RemoteTaskRunnerTest.testRunExistingTaskThatHasntStartedRunning(RemoteTaskRunnerTest.java:157)

**Comment by fjy** [comment]
Another RTR test is failing: https://travis-ci.org/druid-io/druid/jobs/100115132

**Comment by gianm** [comment]
@fjy copied that to #2199

**Comment by fjy** [comment]
Fixed by #2201 (maybe?)
