### ISSUE TITLE
Could not resolve type id 'kafka-0.8-v2' into a subtype

### ISSUE THREAD

**Issue by beta-beta** [druid-io/druid#2202]
hello, when I use KafkaSimpleConsumerFirehose example, there is some wrong:

) Error injecting constructor, java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Could not resolve type id 'kafka-0.8-v2' into a subtype of [simple type, class io.druid.data.input.FirehoseFactoryV2]
 at [Source: ad_log_realtime.spec; line: 38, column: 2] (through reference chain: java.util.ArrayList[0])
  at io.druid.guice.FireDepartmentsProvider.<init>(FireDepartmentsProvider.java:41)
  while locating io.druid.guice.FireDepartmentsProvider
  at io.druid.guice.RealtimeModule.configure(RealtimeModule.java:79)
  while locating java.util.List<io.druid.segment.realtime.FireDepartment>
    for parameter 0 at io.druid.segment.realtime.RealtimeMetricsMonitor.<init>(RealtimeMetricsMonitor.java:42)
  while locating io.druid.segment.realtime.RealtimeMetricsMonitor
  at io.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:78)
  at io.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:78)
  while locating com.metamx.metrics.MonitorScheduler
  at io.druid.server.metrics.MetricsModule.configure(MetricsModule.java:63)
  while locating com.metamx.metrics.MonitorScheduler annotated with @com.google.inject.name.Named(value=ForTheEagerness)

thanks.

**Comment by gianm** [comment]
@beta-beta, to get this to work you need to include the `druid-kafka-eight-simple-consumer` extension (see http://druid.io/docs/latest/operations/including-extensions.html).
