### ISSUE TITLE
transient AnnouncerTest.testSanity() failure

### ISSUE THREAD

**Issue by himanshug** [druid-io/druid#2253]
https://travis-ci.org/druid-io/druid/jobs/101730020

```
testSanity(io.druid.curator.announcement.AnnouncerTest)  Time elapsed: 61.019 sec  <<< ERROR!

java.lang.Exception: test timed out after 60000 milliseconds

    at sun.misc.Unsafe.park(Native Method)

    at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)

    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)

    at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)

    at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)

    at org.apache.curator.test.Timing.awaitLatch(Timing.java:120)

    at io.druid.curator.announcement.AnnouncerTest.testSanity(AnnouncerTest.java:101)
```

**Comment by drcrallen** [comment]
I'm hitting this a lot today.

**Comment by drcrallen** [comment]
I'll start linking failed runs here

**Comment by drcrallen** [comment]
https://travis-ci.org/druid-io/druid/jobs/111798131

**Comment by gianm** [comment]
https://travis-ci.org/druid-io/druid/builds/115210472

**Comment by gianm** [comment]
https://travis-ci.org/druid-io/druid/jobs/119699509

**Comment by gianm** [comment]
https://travis-ci.org/druid-io/druid/builds/135057242

**Comment by gianm** [comment]
https://travis-ci.org/druid-io/druid/jobs/144765914

**Comment by leventov** [comment]
This transient failure hits very often recently

**Comment by gianm** [comment]
I tried some things in #4866 but they didn't seem to work. I did discover one additional clue though, see https://github.com/druid-io/druid/pull/4866#issuecomment-332583647. It wasn't enough for me to get to the bottom of it but it is some more information.

**Comment by jihoonson** [comment]
I'm working on this.
