### ISSUE TITLE
Problems with not exist dimension when they are at the last

### ISSUE THREAD

**Issue by nebrera** [druid-io/druid#235]
Query1:

{
    "queryType": "groupBy",
    "dataSource": "rb_event",
    "granularity": "thirty_minute", 
    "dimensions": ["sensor_name","msg","src_name","action","rev","tos","ethlength","priority","proto","domain"],
    "aggregations":[{"type":"count", "name":"events"}],
    "filter":{
    "type":"and", 
    "fields":[{"type":"selector","dimension":"sensor_name","value":"sensor-produccion"},{"type":"selector","dimension":"msg","value":"WEB-MISC bad HTTP/1.1 request, Potentially worm attack"},{"type":"selector","dimension":"src_name","value":"217.18.160.7"},{"type":"selector","dimension":"action","value":"alert"},{"type":"selector","dimension":"rev","value":"12"},{"type":"selector","dimension":"tos","value":"64"},{"type":"selector","dimension":"ethlength","value":"72"},{"type":"selector","dimension":"priority","value":"2"},{"type":"selector","dimension":"proto","value":"6"},{"type":"selector","dimension":"domain","value":"eneo"}]
    },
    "intervals":["2013-08-30T10:00:00+02:00/2013-08-30T11:00:00+02:00"]
}

Result:

[ {
  "version" : "v1",
  "timestamp" : "2013-08-30T08:00:00.000Z",
  "event" : {
    "tos" : "64",
    "rev" : "12",
    "sensor_name" : "sensor-produccion",
    "events" : 59,
    "priority" : "2",
    "src_name" : "217.18.160.7",
    "domain" : "eneo",
    "ethlength" : "72",
    "action" : "alert",
    "msg" : "WEB-MISC bad HTTP/1.1 request, Potentially worm attack",
    "proto" : "6" 
  }
} ]

Query2 (with vlan_name):

{
    "queryType": "groupBy",
    "dataSource": "rb_event",
    "granularity": "thirty_minute", 
    "dimensions": ["sensor_name","msg","src_name","action","rev","tos","ethlength","priority","proto","domain","vlan_name"],
    "aggregations":[{"type":"count", "name":"events"}],
    "filter":{
    "type":"and", 
    "fields":[{"type":"selector","dimension":"sensor_name","value":"sensor-produccion"},{"type":"selector","dimension":"msg","value":"WEB-MISC bad HTTP/1.1 request, Potentially worm attack"},{"type":"selector","dimension":"src_name","value":"217.18.160.7"},{"type":"selector","dimension":"action","value":"alert"},{"type":"selector","dimension":"rev","value":"12"},{"type":"selector","dimension":"tos","value":"64"},{"type":"selector","dimension":"ethlength","value":"72"},{"type":"selector","dimension":"priority","value":"2"},{"type":"selector","dimension":"proto","value":"6"},{"type":"selector","dimension":"domain","value":"eneo"}]
    },
    "intervals":["2013-08-30T10:00:00+02:00/2013-08-30T11:00:00+02:00"]
}

Response:

[]

Exception Log:

[2013-08-30 16:05:04,277] WARN  QueryServlet:88 - Exception occurred on request [GroupByQuery{limitSpec=NoopLimitSpec, dimFilter=(sensor_name = sensor-produccion && msg = WEB-MISC bad HTTP/1.1 request, Potentially worm attack && src_name = 217.18.160.7 && action = alert && rev = 12 && tos = 64 && ethlength = 72 && priority = 2 && proto = 6 && domain = eneo), granularity=DurationGranularity{length=1800000, origin=0}, dimensions=[DefaultDimensionSpec{dimension='sensor_name', outputName='sensor_name'}, DefaultDimensionSpec{dimension='msg', outputName='msg'}, DefaultDimensionSpec{dimension='src_name', outputName='src_name'}, DefaultDimensionSpec{dimension='action', outputName='action'}, DefaultDimensionSpec{dimension='rev', outputName='rev'}, DefaultDimensionSpec{dimension='tos', outputName='tos'}, DefaultDimensionSpec{dimension='ethlength', outputName='ethlength'}, DefaultDimensionSpec{dimension='priority', outputName='priority'}, DefaultDimensionSpec{dimension='proto', outputName='proto'}, DefaultDimensionSpec{dimension='vlan_name', outputName='vlan_name'}, DefaultDimensionSpec{dimension='domain', outputName='domain'}], aggregatorSpecs=[CountAggregatorFactory{name='events'}], postAggregatorSpecs=[], orderByLimitFn=identity}]
com.fasterxml.jackson.databind.JsonMappingException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.NoSuchElementException
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:129)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:681)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:534)
	at com.metamx.druid.http.QueryServlet.doPost(QueryServlet.java:108)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.NoSuchElementException
	at com.metamx.druid.query.ChainedExecutionQueryRunner$1$2.apply(ChainedExecutionQueryRunner.java:140)
	at com.metamx.druid.query.ChainedExecutionQueryRunner$1$2.apply(ChainedExecutionQueryRunner.java:129)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:860)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.metamx.common.guava.MergeIterable.iterator(MergeIterable.java:45)
	at com.metamx.druid.query.ChainedExecutionQueryRunner$1.make(ChainedExecutionQueryRunner.java:124)
	at com.metamx.common.guava.BaseSequence.toYielder(BaseSequence.java:77)
	at com.metamx.common.guava.BaseSequence.accumulate(BaseSequence.java:66)
	at com.metamx.druid.jackson.DefaultObjectMapper$4.serialize(DefaultObjectMapper.java:118)
	at com.metamx.druid.jackson.DefaultObjectMapper$4.serialize(DefaultObjectMapper.java:112)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:118)
	... 18 more
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.NoSuchElementException
	at java.util.concurrent.FutureTask$Sync.innerGet(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.metamx.druid.query.ChainedExecutionQueryRunner$1$2.apply(ChainedExecutionQueryRunner.java:134)
	... 28 more
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.NoSuchElementException
	at com.metamx.druid.query.ChainedExecutionQueryRunner$1$2.apply(ChainedExecutionQueryRunner.java:140)
	at com.metamx.druid.query.ChainedExecutionQueryRunner$1$2.apply(ChainedExecutionQueryRunner.java:129)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:860)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.metamx.common.guava.MergeIterable.iterator(MergeIterable.java:45)
	at com.metamx.druid.query.ChainedExecutionQueryRunner$1.make(ChainedExecutionQueryRunner.java:124)
	at com.metamx.common.guava.BaseSequence.toYielder(BaseSequence.java:77)
	at com.metamx.common.guava.BaseSequence.accumulate(BaseSequence.java:66)
	at com.metamx.druid.query.MetricsEmittingQueryRunner$1.accumulate(MetricsEmittingQueryRunner.java:83)
	at com.metamx.druid.query.segment.SpecificSegmentQueryRunner$2$1.call(SpecificSegmentQueryRunner.java:78)
	at com.metamx.druid.query.segment.SpecificSegmentQueryRunner.doNamed(SpecificSegmentQueryRunner.java:149)
	at com.metamx.druid.query.segment.SpecificSegmentQueryRunner.access$300(SpecificSegmentQueryRunner.java:35)
	at com.metamx.druid.query.segment.SpecificSegmentQueryRunner$2.doItNamed(SpecificSegmentQueryRunner.java:140)
	at com.metamx.druid.query.segment.SpecificSegmentQueryRunner$2.accumulate(SpecificSegmentQueryRunner.java:72)
	at com.metamx.common.guava.Sequences.toList(Sequences.java:92)
	at com.metamx.druid.query.ChainedExecutionQueryRunner$1$1$1.call(ChainedExecutionQueryRunner.java:110)
	at com.metamx.druid.query.ChainedExecutionQueryRunner$1$1$1.call(ChainedExecutionQueryRunner.java:105)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:61)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:45)
	at com.metamx.druid.query.ChainedExecutionQueryRunner$1$1.apply(ChainedExecutionQueryRunner.java:103)
	at com.metamx.druid.query.ChainedExecutionQueryRunner$1$1.apply(ChainedExecutionQueryRunner.java:99)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:860)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Lists.newArrayList(Lists.java:145)
	at com.google.common.collect.Lists.newArrayList(Lists.java:125)
	at com.metamx.druid.query.ChainedExecutionQueryRunner$1.make(ChainedExecutionQueryRunner.java:95)
	... 23 more
Caused by: java.util.concurrent.ExecutionException: java.util.NoSuchElementException
	at java.util.concurrent.FutureTask$Sync.innerGet(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.metamx.druid.query.ChainedExecutionQueryRunner$1$2.apply(ChainedExecutionQueryRunner.java:134)
	... 51 more
Caused by: java.util.NoSuchElementException
	at java.util.TreeMap$PrivateEntryIterator.nextEntry(Unknown Source)
	at java.util.TreeMap$EntryIterator.next(Unknown Source)
	at java.util.TreeMap$EntryIterator.next(Unknown Source)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.metamx.common.guava.FunctionalIterator.next(FunctionalIterator.java:65)
	at com.metamx.druid.query.group.GroupByQueryEngine$RowIterator.next(GroupByQueryEngine.java:400)
	at com.metamx.druid.query.group.GroupByQueryEngine$RowIterator.next(GroupByQueryEngine.java:272)
	at com.metamx.common.guava.BaseSequence.makeYielder(BaseSequence.java:103)
	at com.metamx.common.guava.BaseSequence.toYielder(BaseSequence.java:80)
	at com.metamx.common.guava.BaseSequence.accumulate(BaseSequence.java:66)
	at com.metamx.common.guava.ConcatSequence$1.accumulate(ConcatSequence.java:46)
	at com.metamx.common.guava.ConcatSequence$1.accumulate(ConcatSequence.java:42)
	at com.metamx.common.guava.YieldingAccumulators$1.accumulate(YieldingAccumulators.java:32)
	at com.metamx.common.guava.BaseSequence.makeYielder(BaseSequence.java:103)
	at com.metamx.common.guava.BaseSequence.toYielder(BaseSequence.java:80)
	at com.metamx.common.guava.BaseSequence.accumulate(BaseSequence.java:66)
	at com.metamx.common.guava.ConcatSequence.accumulate(ConcatSequence.java:40)
	at com.metamx.common.guava.Sequences.toList(Sequences.java:92)
	at com.metamx.druid.query.ChainedExecutionQueryRunner$1$1$1.call(ChainedExecutionQueryRunner.java:110)
	at com.metamx.druid.query.ChainedExecutionQueryRunner$1$1$1.call(ChainedExecutionQueryRunner.java:105)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:61)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:45)
	at com.metamx.druid.query.ChainedExecutionQueryRunner$1$1.apply(ChainedExecutionQueryRunner.java:103)
	at com.metamx.druid.query.ChainedExecutionQueryRunner$1$1.apply(ChainedExecutionQueryRunner.java:99)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:860)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Lists.newArrayList(Lists.java:145)
	at com.google.common.collect.Lists.newArrayList(Lists.java:125)
	at com.metamx.druid.query.ChainedExecutionQueryRunner$1.make(ChainedExecutionQueryRunner.java:95)
	... 46 more

**Comment by xvrl** [comment]
@nebrera sorry we dropped the ball on this one, are you still experiencing this issue in Druid 0.7.3? Please reopen if so.
