### ISSUE TITLE
Selfcontained jar gets put at end of dependency tree causing errors in some jobs

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#2443]
PullDeps won't consider excluding dependencies outside the stock exclude list. So if, for example, you have extra jars in the aws credentials extension who have different versions which are pulled in by... say... spark. Then when the hadoop isolating classloader tries to load up the hadoop dependencies and then the druid and then the extension ones, you'll end up with not the classes you want because they are either the wrong version or loaded in the wrong classloaders. This will lead to a nasty stacktrace like this:

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[druid-selfcontained-0.9.0-rc1-mmx2.jar:0.9.0-rc1-mmx2]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:170) ~[druid-selfcontained-0.9.0-rc1-mmx2.jar:0.9.0-rc1-mmx2]
	at io.druid.indexer.spark.SparkBatchIndexTask.run(SparkBatchIndexTask.scala:155) [druid-spark-batch_2.10-0.0.27.jar:0.0.27]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:338) [druid-selfcontained-0.9.0-rc1-mmx2.jar:0.9.0-rc1-mmx2]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:318) [druid-selfcontained-0.9.0-rc1-mmx2.jar:0.9.0-rc1-mmx2]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:167) ~[druid-selfcontained-0.9.0-rc1-mmx2.jar:0.9.0-rc1-mmx2]
	... 7 more
Caused by: java.util.ServiceConfigurationError: io.druid.initialization.DruidModule: Provider io.druid.storage.s3.S3StorageDruidModule could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232) ~[?:1.8.0_72]
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185) ~[?:1.8.0_72]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384) ~[?:1.8.0_72]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[?:1.8.0_72]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[?:1.8.0_72]
	at io.druid.initialization.Initialization.getFromExtensions(Initialization.java:132) ~[druid-selfcontained-0.9.0-rc1-mmx2.jar:0.9.0-rc1-mmx2]
	at io.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:318) ~[druid-selfcontained-0.9.0-rc1-mmx2.jar:0.9.0-rc1-mmx2]
	at io.druid.indexer.spark.SerializedJsonStatic$.liftedTree1$1(SparkDruidIndexer.scala:421) ~[?:?]
	at io.druid.indexer.spark.SerializedJsonStatic$.injector$lzycompute(SparkDruidIndexer.scala:420) ~[?:?]
	at io.druid.indexer.spark.SerializedJsonStatic$.injector(SparkDruidIndexer.scala:419) ~[?:?]
	at io.druid.indexer.spark.SerializedJsonStatic$.liftedTree2$1(SparkDruidIndexer.scala:449) ~[?:?]
	at io.druid.indexer.spark.SerializedJsonStatic$.mapper$lzycompute(SparkDruidIndexer.scala:448) ~[?:?]
	at io.druid.indexer.spark.SerializedJsonStatic$.mapper(SparkDruidIndexer.scala:447) ~[?:?]
	at io.druid.indexer.spark.SparkBatchIndexTask$.runTask(SparkBatchIndexTask.scala:277) ~[?:?]
	at io.druid.indexer.spark.SparkBatchIndexTask.runTask(SparkBatchIndexTask.scala) ~[?:?]
	at io.druid.indexer.spark.Runner.runTask(Runner.java:29) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:167) ~[druid-selfcontained-0.9.0-rc1-mmx2.jar:0.9.0-rc1-mmx2]
	... 7 more
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    io/druid/storage/s3/S3StorageDruidModule.getRestS3Service(Lcom/amazonaws/auth/AWSCredentialsProvider;)Lorg/jets3t/service/impl/rest/httpclient/RestS3Service; @24: invokespecial
  Reason:
    Type 'io/druid/storage/s3/AWSSessionCredentialsAdapter' (current frame, stack[2]) is not assignable to 'org/jets3t/service/security/ProviderCredentials'
  Current Frame:
    bci: @24
    flags: { }
    locals: { 'io/druid/storage/s3/S3StorageDruidModule', 'com/amazonaws/auth/AWSCredentialsProvider' }
    stack: { uninitialized 12, uninitialized 12, 'io/druid/storage/s3/AWSSessionCredentialsAdapter' }
  Bytecode:
    0x0000000: 2bb9 0027 0100 c100 2899 0013 bb00 2959
    0x0000010: bb00 2a59 2bb7 002b b700 2cb0 bb00 2959
    0x0000020: bb00 2d59 2bb9 0027 0100 b900 2e01 002b
    0x0000030: b900 2701 00b9 002f 0100 b700 30b7 002c
    0x0000040: b0                                     
  Stackmap Table:
    same_frame(@28)

	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_72]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_72]
	at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_72]
	at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_72]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380) ~[?:1.8.0_72]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[?:1.8.0_72]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[?:1.8.0_72]
	at io.druid.initialization.Initialization.getFromExtensions(Initialization.java:132) ~[druid-selfcontained-0.9.0-rc1-mmx2.jar:0.9.0-rc1-mmx2]
	at io.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:318) ~[druid-selfcontained-0.9.0-rc1-mmx2.jar:0.9.0-rc1-mmx2]
	at io.druid.indexer.spark.SerializedJsonStatic$.liftedTree1$1(SparkDruidIndexer.scala:421) ~[?:?]
	at io.druid.indexer.spark.SerializedJsonStatic$.injector$lzycompute(SparkDruidIndexer.scala:420) ~[?:?]
	at io.druid.indexer.spark.SerializedJsonStatic$.injector(SparkDruidIndexer.scala:419) ~[?:?]
	at io.druid.indexer.spark.SerializedJsonStatic$.liftedTree2$1(SparkDruidIndexer.scala:449) ~[?:?]
	at io.druid.indexer.spark.SerializedJsonStatic$.mapper$lzycompute(SparkDruidIndexer.scala:448) ~[?:?]
	at io.druid.indexer.spark.SerializedJsonStatic$.mapper(SparkDruidIndexer.scala:447) ~[?:?]
	at io.druid.indexer.spark.SparkBatchIndexTask$.runTask(SparkBatchIndexTask.scala:277) ~[?:?]
	at io.druid.indexer.spark.SparkBatchIndexTask.runTask(SparkBatchIndexTask.scala) ~[?:?]
	at io.druid.indexer.spark.Runner.runTask(Runner.java:29) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:167) ~[druid-selfcontained-0.9.0-rc1-mmx2.jar:0.9.0-rc1-mmx2]
	... 7 more
```

**Comment by drcrallen** [comment]
For the record, here's a list of some of the files from pulldeps:


```
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/hadoop-yarn-api-2.4.0-mmx1.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/stax-api-1.0-2.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/hadoop-yarn-client-2.4.0-mmx1.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/hadoop-mapreduce-client-jobclient-2.4.0-mmx1.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/hadoop-annotations-2.4.0-mmx1.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/jaxb-api-2.2.2.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/commons-math3-3.1.1.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/hadoop-common-2.4.0-mmx1.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/commons-net-3.1.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/hadoop-client-2.4.0-mmx1.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/hadoop-mapreduce-client-app-2.4.0-mmx1.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/hadoop-yarn-server-common-2.4.0-mmx1.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/hadoop-auth-2.4.0-mmx1.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/hadoop-mapreduce-client-core-2.4.0-mmx1.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/commons-configuration-1.6.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/xz-1.0.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/hadoop-mapreduce-client-shuffle-2.4.0-mmx1.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/hadoop-hdfs-2.4.0-mmx1.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/commons-collections-3.2.1.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/commons-beanutils-core-1.8.0.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/servlet-api-2.5.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/commons-compress-1.4.1.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/commons-beanutils-1.7.0.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/paranamer-2.3.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/commons-httpclient-3.1.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/snappy-java-1.0.4.1.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/hadoop-mapreduce-client-common-2.4.0-mmx1.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/xmlenc-0.52.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/hadoop-yarn-common-2.4.0-mmx1.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/avro-1.7.4.jar
lib/hadoop_dependencies/hadoop-client/2.4.0-mmx1/commons-digester-1.8.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/hadoop-yarn-api-2.2.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/chill_2.10-0.5.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/avro-ipc-1.7.7.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/scala-library-2.10.4.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/hadoop-mapreduce-client-core-2.2.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/snappy-java-1.1.1.7.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/commons-math3-3.4.1.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/unused-1.0.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/guice-3.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/commons-lang3-3.3.2.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/akka-remote_2.10-2.3.11.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/stream-2.7.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/pyrolite-4.4.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/scala-compiler-2.10.4.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/jersey-test-framework-grizzly2-1.9.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/scalap-2.10.4.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/spark-network-common_2.10-1.5.2-mmx0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/commons-math-2.1.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/akka-actor_2.10-2.3.11.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/spark-unsafe_2.10-1.5.2-mmx0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/jackson-module-scala_2.10-2.4.4.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/mesos-0.21.1-shaded-protobuf.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/jersey-test-framework-core-1.9.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/commons-net-2.2.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/compress-lzf-1.0.3.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/uncommons-maths-1.2.2a.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/hadoop-client-2.2.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/config-1.2.1.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/akka-slf4j_2.10-2.3.11.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/commons-configuration-1.6.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/reflectasm-1.07-shaded.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/hadoop-mapreduce-client-common-2.2.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/scala-reflect-2.10.4.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/jets3t-0.7.1.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/xz-1.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/chill-java-0.5.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/spark-core_2.10-1.5.2-mmx0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/hadoop-annotations-2.2.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/json4s-jackson_2.10-3.2.10.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/commons-collections-3.2.1.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/commons-beanutils-core-1.8.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/json4s-ast_2.10-3.2.10.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/ivy-2.4.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/py4j-0.8.2.1.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/objenesis-1.2.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/hadoop-mapreduce-client-shuffle-2.2.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/curator-recipes-2.4.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/hadoop-yarn-client-2.2.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/hadoop-auth-2.2.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/commons-compress-1.4.1.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/json4s-core_2.10-3.2.10.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/kryo-2.21.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/javax.servlet-api-3.0.1.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/avro-1.7.7.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/javax.inject-1.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/avro-mapred-1.7.7-hadoop2.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/oro-2.0.8.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/commons-beanutils-1.7.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/spark-launcher_2.10-1.5.2-mmx0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/hadoop-yarn-common-2.2.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/hadoop-hdfs-2.2.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/aopalliance-1.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/metrics-graphite-3.1.2.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/hadoop-yarn-server-common-2.2.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/commons-httpclient-3.1.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/tachyon-underfs-hdfs-0.7.1.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/lz4-1.3.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/metrics-json-3.1.2.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/curator-framework-2.4.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/avro-ipc-1.7.7-tests.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/hadoop-common-2.2.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/metrics-jvm-3.1.2.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/curator-client-2.4.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/hadoop-mapreduce-client-jobclient-2.2.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/xmlenc-0.52.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/tachyon-underfs-local-0.7.1.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/spark-network-shuffle_2.10-1.5.2-mmx0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/javax.servlet-3.0.0.v201112011016.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/paranamer-2.6.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/commons-digester-1.8.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/hadoop-mapreduce-client-app-2.2.0.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/metrics-core-3.1.2.jar
lib/hadoop_dependencies/spark-core_2.10/1.5.2-mmx0/tachyon-client-0.7.1.jar
lib/extensions/druid-extensions/druid-extensions-0.9.0-a9c4646-0.9.0-rc1-mmx2.jar
lib/extensions/druid-kafka-eight/scala-library-2.10.4.jar
lib/extensions/druid-kafka-eight/zkclient-0.3.jar
lib/extensions/druid-kafka-eight/kafka_2.10-0.8.2.1.jar
lib/extensions/druid-kafka-eight/druid-kafka-eight-0.9.0-rc1-mmx2.jar
lib/extensions/druid-kafka-eight/jopt-simple-3.2.jar
lib/extensions/druid-kafka-eight/kafka-clients-0.8.2.1.jar
lib/extensions/druid-kafka-eight/lz4-1.3.0.jar
lib/extensions/druid-kafka-eight/snappy-java-1.1.1.6.jar
lib/extensions/druid-kafka-eight/metrics-core-2.2.0.jar
lib/extensions/druid-s3-extensions/java-xmlbuilder-1.1.jar
lib/extensions/druid-s3-extensions/base64-2.3.8.jar
lib/extensions/druid-s3-extensions/log4j-1.2-api-2.5.jar
lib/extensions/druid-s3-extensions/bcprov-jdk15on-1.52.jar
lib/extensions/druid-s3-extensions/log4j-core-2.5.jar
lib/extensions/druid-s3-extensions/druid-s3-extensions-0.9.0-rc1-mmx2.jar
lib/extensions/druid-s3-extensions/jets3t-0.9.4.jar
lib/extensions/druid-s3-extensions/log4j-api-2.5.jar
lib/extensions/druid-s3-extensions/http-client-1.0.4.jar
lib/extensions/druid-s3-extensions/emitter-0.3.6.jar
lib/extensions/druid-spark-batch_2.10/druid-spark-batch_2.10-0.0.27.jar
lib/extensions/druid-spark-batch_2.10/scala-library-2.10.5.jar
lib/extensions/druid-packaging/hadoop-yarn-api-2.4.0-mmx1.jar
lib/extensions/druid-packaging/stax-api-1.0-2.jar
lib/extensions/druid-packaging/hadoop-yarn-client-2.4.0-mmx1.jar
lib/extensions/druid-packaging/hadoop-mapreduce-client-jobclient-2.4.0-mmx1.jar
lib/extensions/druid-packaging/hadoop-annotations-2.4.0-mmx1.jar
lib/extensions/druid-packaging/jaxb-api-2.2.2.jar
lib/extensions/druid-packaging/commons-math3-3.1.1.jar
lib/extensions/druid-packaging/hadoop-common-2.4.0-mmx1.jar
lib/extensions/druid-packaging/commons-net-3.1.jar
lib/extensions/druid-packaging/druid-packaging-0.9.0-a9c4646-0.9.0-rc1-mmx2.jar
lib/extensions/druid-packaging/hadoop-client-2.4.0-mmx1.jar
lib/extensions/druid-packaging/hadoop-mapreduce-client-app-2.4.0-mmx1.jar
lib/extensions/druid-packaging/hadoop-yarn-server-common-2.4.0-mmx1.jar
lib/extensions/druid-packaging/hadoop-auth-2.4.0-mmx1.jar
lib/extensions/druid-packaging/hadoop-mapreduce-client-core-2.4.0-mmx1.jar
lib/extensions/druid-packaging/commons-configuration-1.6.jar
lib/extensions/druid-packaging/xz-1.0.jar
lib/extensions/druid-packaging/hadoop-mapreduce-client-shuffle-2.4.0-mmx1.jar
lib/extensions/druid-packaging/hadoop-hdfs-2.4.0-mmx1.jar
lib/extensions/druid-packaging/commons-collections-3.2.1.jar
lib/extensions/druid-packaging/sigar-1.6.5.132.jar
lib/extensions/druid-packaging/commons-beanutils-core-1.8.0.jar
lib/extensions/druid-packaging/servlet-api-2.5.jar
lib/extensions/druid-packaging/commons-compress-1.4.1.jar
lib/extensions/druid-packaging/commons-beanutils-1.7.0.jar
lib/extensions/druid-packaging/paranamer-2.3.jar
lib/extensions/druid-packaging/commons-httpclient-3.1.jar
lib/extensions/druid-packaging/snappy-java-1.0.4.1.jar
lib/extensions/druid-packaging/hadoop-mapreduce-client-common-2.4.0-mmx1.jar
lib/extensions/druid-packaging/xmlenc-0.52.jar
lib/extensions/druid-packaging/hadoop-yarn-common-2.4.0-mmx1.jar
lib/extensions/druid-packaging/avro-1.7.4.jar
lib/extensions/druid-packaging/commons-digester-1.8.jar
lib/extensions/mysql-metadata-storage/jdbi-2.63.1.jar
lib/extensions/mysql-metadata-storage/mysql-connector-java-5.1.34.jar
lib/extensions/mysql-metadata-storage/mysql-metadata-storage-0.9.0-rc1-mmx2.jar
lib/extensions/druid-histogram/druid-histogram-0.9.0-rc1-mmx2.jar
lib/extensions/druid-namespace-lookup/druid-namespace-lookup-0.9.0-rc1-mmx2.jar
```

Notice that jets3t is on there twice, once for spark and once for the aws credentials.

**Comment by drcrallen** [comment]
The challenge here is that it is not obvious that jets3t SHOULDN'T be used until it is trying to be in both classloaders at once. I'll see if I can reproduce this locally.

**Comment by drcrallen** [comment]
Or maybe its this? http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8006684

**Comment by drcrallen** [comment]
this was a problem with selfcontained jar

**Comment by nishantmonu51** [comment]
@drcrallen: Can we resolve since the mentioned PRs have been merged and backported ?
