### ISSUE TITLE
Getting strange looping error (bug?) 

### ISSUE THREAD

**Issue by dkoen** [druid-io/druid#2591]
```
2016-03-03T20:51:33,775 ERROR [Master-PeonExec--0] io.druid.server.coordinator.LoadQueuePeon - Server[/druid/v1/prod/loadQueue/ec2-54-174-23-0.compute-1.amazonaws.com:8080], throwable caught when submitting [SegmentChangeRequestLoad{segment=DataSegment{size=26421737, shardSpec=NoneShardSpec, metrics=[impressions, mouseovers, clicks, shares, rendered, viewable, video_starts, video_q1, video_q2, video_q3, video_completions, duration_watched, publisher_revenue, spend, conversions], dimensions=[advertiser_id, brand_id, browser_id, buyer_member_id, country, creative_asset_id, creative_library_id, deal_id, device_type_id, dma, domain, insertion_order_id, inventory_type_id, is_adserver, is_ghost, line_item_id, os_id, placement_id, publisher_id, region, tactic_id], version='2016-03-03T20:25:33.691Z', loadSpec={type=s3_zip, bucket=druid.triplelift.com, key=main_hourly_prod_v2/2016-03-03T18:00:00.000Z_2016-03-03T19:00:00.000Z/2016-03-03T20:25:33.691Z/0/index.zip}, interval=2016-03-03T18:00:00.000Z/2016-03-03T19:00:00.000Z, dataSource='main_hourly_prod_v2', binaryVersion='9'}}].
com.metamx.common.ISE: /druid/v1/prod/loadQueue/ec2-54-174-23-0.compute-1.amazonaws.com:8080/main_hourly_prod_v2_2016-03-03T18:00:00.000Z_2016-03-03T19:00:00.000Z_2016-03-03T20:25:33.691Z was never removed! Failing this operation!
        at io.druid.server.coordinator.LoadQueuePeon$1$1.run(LoadQueuePeon.java:236) [druid-server-0.8.3.jar:0.8.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_85]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_85]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) [?:1.7.0_85]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) [?:1.7.0_85]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_85]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_85]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_85]
2016-03-03T20:51:33,775 INFO [Master-PeonExec--0] io.druid.server.coordinator.LoadQueuePeon - Server[/druid/v1/prod/loadQueue/ec2-54-174-23-0.compute-1.amazonaws.com:8080] loading [main_hourly_prod_v2_2016-03-03T17:00:00.000Z_2016-03-03T18:00:00.000Z_2016-03-03T19:43:18.629Z]
2016-03-03T20:51:33,775 INFO [Master-PeonExec--0] io.druid.server.coordinator.LoadQueuePeon - Server[/druid/v1/prod/loadQueue/ec2-54-174-23-0.compute-1.amazonaws.com:8080] processing segment[main_hourly_prod_v2_2016-03-03T17:00:00.000Z_2016-03-03T18:00:00.000Z_2016-03-03T19:43:18.629Z]
2016-03-03T20:51:35,926 INFO [DatabaseSegmentManager-Exec--0] io.druid.metadata.SQLMetadataSegmentManager - Polled and found 1,582 segments in the database
2016-03-03T20:51:40,632 ERROR [Master-PeonExec--0] io.druid.server.coordinator.LoadQueuePeon - Server[/druid/v1/prod/loadQueue/ec2-54-174-23-0.compute-1.amazonaws.com:8080], throwable caught when submitting [SegmentChangeRequestLoad{segment=DataSegment{size=23926509, shardSpec=NoneShardSpec, metrics=[impressions, mouseovers, clicks, shares, rendered, viewable, video_starts, video_q1, video_q2, video_q3, video_completions, duration_watched, publisher_revenue, spend, conversions], dimensions=[advertiser_id, brand_id, browser_id, buyer_member_id, country, creative_asset_id, creative_library_id, deal_id, device_type_id, dma, domain, insertion_order_id, inventory_type_id, is_adserver, is_ghost, line_item_id, os_id, placement_id, publisher_id, region, tactic_id], version='2016-03-03T19:43:18.629Z', loadSpec={type=s3_zip, bucket=druid.triplelift.com, key=main_hourly_prod_v2/2016-03-03T17:00:00.000Z_2016-03-03T18:00:00.000Z/2016-03-03T19:43:18.629Z/0/index.zip}, interval=2016-03-03T17:00:00.000Z/2016-03-03T18:00:00.000Z, dataSource='main_hourly_prod_v2', binaryVersion='9'}}].
com.metamx.common.ISE: /druid/v1/prod/loadQueue/ec2-54-174-23-0.compute-1.amazonaws.com:8080/main_hourly_prod_v2_2016-03-03T17:00:00.000Z_2016-03-03T18:00:00.000Z_2016-03-03T19:43:18.629Z was never removed! Failing this operation!
        at io.druid.server.coordinator.LoadQueuePeon$1$1.run(LoadQueuePeon.java:236) [druid-server-0.8.3.jar:0.8.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_85]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_85]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) [?:1.7.0_85]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) [?:1.7.0_85]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_85]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_85]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_85]
2016-03-03T20:51:40,632 INFO [Master-PeonExec--0] io.druid.server.coordinator.LoadQueuePeon - Server[/druid/v1/prod/loadQueue/ec2-54-174-23-0.compute-1.amazonaws.com:8080] loading [main_hourly_prod_v2_2016-03-03T16:00:00.000Z_2016-03-03T17:00:00.000Z_2016-03-03T19:30:34.170Z]
2016-03-03T20:51:40,632 INFO [Master-PeonExec--0] io.druid.server.coordinator.LoadQueuePeon - Server[/druid/v1/prod/loadQueue/ec2-54-174-23-0.compute-1.amazonaws.com:8080] processing segment[main_hourly_prod_v2_2016-03-03T16:00:00.000Z_2016-03-03T17:00:00.000Z_2016-03-03T19:30:34.170Z]
``` 

Coordinator seems to be stuck in a loop. I'm not sure why.

**Comment by dkoen** [comment]
There number of segments to load seems to revolve around 30 going up and down.
