### ISSUE TITLE
Transient failure in WorkerTaskMonitorTest.testRestartCleansOldStatus

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#2637]
https://travis-ci.org/druid-io/druid/builds/115348852

```
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.356 sec <<< FAILURE! - in io.druid.indexing.worker.WorkerTaskMonitorTest
testRestartCleansOldStatus(io.druid.indexing.worker.WorkerTaskMonitorTest)  Time elapsed: 1.213 sec  <<< FAILURE!
java.lang.AssertionError: expected:<FAILED> but was:<RUNNING>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.druid.indexing.worker.WorkerTaskMonitorTest.testRestartCleansOldStatus(WorkerTaskMonitorTest.java:338)
```

**Comment by gianm** [comment]
This test is simulating a restart, this is possibly caused by the old WTM not fully exiting.

**Comment by gianm** [comment]
Diff

**Comment by gianm** [comment]
Different failure!

```
Tests run: 5, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 35.37 sec <<< FAILURE! - in io.druid.indexing.worker.WorkerTaskMonitorTest
testRestartCleansOldStatus(io.druid.indexing.worker.WorkerTaskMonitorTest)  Time elapsed: 31.073 sec  <<< ERROR!
java.lang.Exception: test timed out after 30000 milliseconds
    at sun.misc.Unsafe.park(Native Method)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
    at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
    at io.druid.indexing.worker.WorkerTaskMonitor.stop(WorkerTaskMonitor.java:260)
    at io.druid.indexing.worker.WorkerTaskMonitorTest.testRestartCleansOldStatus(WorkerTaskMonitorTest.java:331)
testRestartCleansOldStatus(io.druid.indexing.worker.WorkerTaskMonitorTest)  Time elapsed: 31.073 sec  <<< ERROR!
java.lang.IllegalStateException: not started
    at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
    at io.druid.indexing.worker.WorkerTaskMonitor.stop(WorkerTaskMonitor.java:250)
    at io.druid.indexing.worker.WorkerTaskMonitorTest.tearDown(WorkerTaskMonitorTest.java:205)
```

**Comment by gianm** [comment]
wait, that should be a different issue.
