### ISSUE TITLE
Transient test failure - io.druid.indexing.worker.WorkerTaskMonitorTest testRestartCleansOldStatus

### ISSUE THREAD

**Issue by pjain1** [druid-io/druid#2664]
https://travis-ci.org/druid-io/druid/jobs/116194415
```
Tests run: 5, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 35.373 sec <<< FAILURE! - in io.druid.indexing.worker.WorkerTaskMonitorTest
testRestartCleansOldStatus(io.druid.indexing.worker.WorkerTaskMonitorTest)  Time elapsed: 31.136 sec  <<< ERROR!
java.lang.Exception: test timed out after 30000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at io.druid.indexing.worker.WorkerTaskMonitor.stop(WorkerTaskMonitor.java:260)
	at io.druid.indexing.worker.WorkerTaskMonitorTest.testRestartCleansOldStatus(WorkerTaskMonitorTest.java:331)
testRestartCleansOldStatus(io.druid.indexing.worker.WorkerTaskMonitorTest)  Time elapsed: 31.136 sec  <<< ERROR!
java.lang.IllegalStateException: not started
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at io.druid.indexing.worker.WorkerTaskMonitor.stop(WorkerTaskMonitor.java:250)
	at io.druid.indexing.worker.WorkerTaskMonitorTest.tearDown(WorkerTaskMonitorTest.java:205)
```

**Comment by guobingkun** [comment]
https://travis-ci.org/druid-io/druid/jobs/118303028
```
testRestartCleansOldStatus(io.druid.indexing.worker.WorkerTaskMonitorTest)  Time elapsed: 31.086 sec  <<< ERROR!
java.lang.Exception: test timed out after 30000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at io.druid.indexing.worker.WorkerTaskMonitor.stop(WorkerTaskMonitor.java:260)
	at io.druid.indexing.worker.WorkerTaskMonitorTest.testRestartCleansOldStatus(WorkerTaskMonitorTest.java:331)
testRestartCleansOldStatus(io.druid.indexing.worker.WorkerTaskMonitorTest)  Time elapsed: 31.086 sec  <<< ERROR!
java.lang.IllegalStateException: not started
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at io.druid.indexing.worker.WorkerTaskMonitor.stop(WorkerTaskMonitor.java:250)
	at io.druid.indexing.worker.WorkerTaskMonitorTest.tearDown(WorkerTaskMonitorTest.java:205)
```

**Comment by guobingkun** [comment]
https://travis-ci.org/druid-io/druid/jobs/118513011
```
Tests run: 5, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 35.861 sec <<< FAILURE! - in io.druid.indexing.worker.WorkerTaskMonitorTest
testRestartCleansOldStatus(io.druid.indexing.worker.WorkerTaskMonitorTest)  Time elapsed: 31.089 sec  <<< ERROR!
java.lang.Exception: test timed out after 30000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at io.druid.indexing.worker.WorkerTaskMonitor.stop(WorkerTaskMonitor.java:260)
	at io.druid.indexing.worker.WorkerTaskMonitorTest.testRestartCleansOldStatus(WorkerTaskMonitorTest.java:331)
testRestartCleansOldStatus(io.druid.indexing.worker.WorkerTaskMonitorTest)  Time elapsed: 31.092 sec  <<< ERROR!
java.lang.IllegalStateException: not started
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at io.druid.indexing.worker.WorkerTaskMonitor.stop(WorkerTaskMonitor.java:250)
	at io.druid.indexing.worker.WorkerTaskMonitorTest.tearDown(WorkerTaskMonitorTest.java:205)
```
