### ISSUE TITLE
integration test using router failed after #2674

### ISSUE THREAD

**Issue by rasahner** [druid-io/druid#2681]
After PR https://github.com/druid-io/druid/pull/2674, the integration test ITRealtimeIndexTaskTest failed because the first query it tried timed out.  The rest of the tests passed.  The failed test is the only one that uses the router.  The router log says this at the time the query was done:

```
2016-03-18T13:15:46,350 WARN [HttpClient@162774556-169-selector-ClientSelectorManager@1e835d66/2] org.eclipse.jetty.io.SelectorManager - Could not process key for channel java.nio.channels.SocketChannel[closed]
java.util.concurrent.RejectedExecutionException: org.eclipse.jetty.client.PoolingHttpDestination$1@3165714f
   at org.eclipse.jetty.util.thread.QueuedThreadPool.execute(QueuedThreadPool.java:360) ~[jetty-util-9.2.5.v20141112.jar:9.2.5.v20141112]
   at org.eclipse.jetty.client.PoolingHttpDestination.failed(PoolingHttpDestination.java:59) ~[jetty-client-9.2.5.v20141112.jar:9.2.5.v20141112]
   at org.eclipse.jetty.client.ConnectionPool$1.failed(ConnectionPool.java:112) ~[jetty-client-9.2.5.v20141112.jar:9.2.5.v20141112]        
   at org.eclipse.jetty.client.AbstractHttpClientTransport.connectFailed(AbstractHttpClientTransport.java:126) ~[jetty-client-9.2.5.v20141112.jar:9.2.5.v20141112]
   at org.eclipse.jetty.client.AbstractHttpClientTransport$ClientSelectorManager.connectionFailed(AbstractHttpClientTransport.java:169) ~[jetty-client-9.2.5.v20141112.jar:9.2.5.v20141112]        
   at org.eclipse.jetty.io.SelectorManager$ManagedSelector$Connect.failed(SelectorManager.java:933) ~[jetty-io-9.2.5.v20141112.jar:9.2.5.v20141112]
```

**Comment by drcrallen** [comment]
Thanks @rasahner can you confirm that this was using the standard druid ITs, or was this using your guys stuff?

**Comment by rasahner** [comment]
The test that failed was a standard druid IT.

**Comment by xvrl** [comment]
@rasahner what kind of query is failing the test? Based on the code path, unless it was a DELETE request it should not behave any differently than before.

**Comment by rasahner** [comment]
it's timeBoundary (the very first query the test does).  query to the broker is ok, same query to the router times out.

**Comment by rasahner** [comment]
modified class is used by RouterJettyServerInitializer

**Comment by xvrl** [comment]
@rasahner not sure I understand what you mean by "modified class is used by RouterJettyServerInitializer"

**Comment by rasahner** [comment]
AsyncQueryForwardingServlet was modified by PR https://github.com/druid-io/druid/pull/2674.
In RouterJettyServerInitializer:
       final AsyncQueryForwardingServlet asyncQueryForwardingServlet = new AsyncQueryForwardingServlet( ....)

I don't see how the PR would cause different query behavior, but our build based on the druid.io master branch failed when the only change from the previous build was this PR.  I think the router is trying to do something using http (contact a broker?) and can't make a connection.

**Comment by xvrl** [comment]
@rasahner is it possible that #2644 introduced this issue?

**Comment by rasahner** [comment]
I don't think that is likely.  Our builds (incuding runs of all IT tests) passed after that PR was merged.  Also, I think that PR would only have an affect after the query was being processed.  In this failure, the query seems to be running into trouble at the router (doesn't seem to get to a broker).

**Comment by rasahner** [comment]
fyi, I reverted just the PR in question, and that let all the test pass. (I see you have a fix in metamx/druid.)
