### ISSUE TITLE
FAILURE! - in io.druid.query.lookup.LookupSnapshotTakerTest

### ISSUE THREAD

**Issue by JonStrabala** [druid-io/druid#2694]
When I run 'mvn test' on Building druid-processing 0.9.1-SNAPSHOT one test fails

Failed tests:
  LookupSnapshotTakerTest.testIOExceptionDuringLookupPersist Expected exception: com.metamx.common.ISE

Tests run: 8868, Failures: 1, Errors: 0, Skipped: 13

=== details ===
```
Running io.druid.query.lookup.LookupSnapshotTakerTest
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.018 sec <<< FAILURE! - in io.druid.query.lookup.LookupSnapshotTakerTest
testIOExceptionDuringLookupPersist(io.druid.query.lookup.LookupSnapshotTakerTest)  Time elapsed: 0.01 sec  <<< FAILURE!
java.lang.AssertionError: Expected exception: com.metamx.common.ISE
        at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by thaDude** [comment]
+1 Same issue. Is it normal for some tests to fail? I build 0.9.0 to check if this was a "regression" - and also encountered some test failures. I don't mind building with `-DskipTests`;-)

```
Apache Maven 3.0.4
Maven home: /usr/share/maven
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "3.16.0-0.bpo.4-amd64", arch: "amd64", family: "unix"
```

**Comment by drcrallen** [comment]
Checking this out to verify or refute.

**Comment by drcrallen** [comment]
In general, there are a few transient test failures, usually related to some of the tests which use zookeeper. And usually only appear on massively over-provisioned (or under-powered) systems like the travis-ci OSS free tier. These transient errors haven't been fixed because they are really hard to reproduce reliably.

The test in the master comment is a relatively new test suite but doesn't have any known transient errors.

**Comment by drcrallen** [comment]
Could not reproduce, but changed the test around a bit to see if it can be more explicit about the failure. Please give the patch in https://github.com/druid-io/druid/pull/2809 a try and see if the tests pass.

**Comment by fjy** [comment]
@drcrallen I believe this error is transient. I've seen it before as well.

**Comment by JonStrabala** [comment]
First, I always get this error so it is reproducible for me under  0.9.1-SNAPSHOT since Mar 31, 2016 including a new GIT pull from today May 5, 2016.  

But this seems to be an issues just because I run as user 'root' - see #2861 for details

Before anyone says why are you developing as user root - well I'm lazy - and I am doing this in a throw away SmartOS zone so I don't much care about mistakes or security etc.
