### ISSUE TITLE
BUG: hadoop index task occasional fail (distributed cache related)

### ISSUE THREAD

**Issue by hamlet-lee** [druid-io/druid#2707]
some times, the `hadoop index` task fail.

the task have two phases:
1) determine_partitions_hashed [success]
2) real index job  [fail]

from middle manager's log, it reports sth like:

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-16.0.1.jar:?]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:201) ~[druid-indexing-service-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at io.druid.indexing.common.task.HadoopIndexTask.run(HadoopIndexTask.java:208) ~[druid-indexing-service-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:407) [druid-indexing-service-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:380) [druid-indexing-service-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_71]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:198) ~[druid-indexing-service-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	... 7 more
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: File does not exist: hdfs://god001:8000/tmp/druid-indexing/myds/2016-03-23T101134.355+0800/4aa9e9219d254e3c87edaff8922b7783/classpath/druid-processing-0.9.0-SNAPSHOT.jar
	at io.druid.indexer.IndexGeneratorJob.run(IndexGeneratorJob.java:211) ~[druid-indexing-hadoop-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at io.druid.indexer.JobHelper.runJobs(JobHelper.java:323) ~[druid-indexing-hadoop-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at io.druid.indexer.HadoopDruidIndexerJob.run(HadoopDruidIndexerJob.java:94) ~[druid-indexing-hadoop-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at io.druid.indexing.common.task.HadoopIndexTask$HadoopIndexGeneratorInnerProcessing.runTask(HadoopIndexTask.java:261) ~[druid-indexing-service-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:198) ~[druid-indexing-service-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	... 7 more
Caused by: java.io.FileNotFoundException: File does not exist: hdfs://god001:8000/tmp/druid-indexing/myds/2016-03-23T101134.355+0800/4aa9e9219d254e3c87edaff8922b7783/classpath/druid-processing-0.9.0-SNAPSHOT.jar
	at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1309) ~[hadoop-hdfs-2.7.1.jar:?]
	at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1301) ~[hadoop-hdfs-2.7.1.jar:?]
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81) ~[hadoop-common-2.7.1.jar:?]
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1301) ~[hadoop-hdfs-2.7.1.jar:?]
	at org.apache.hadoop.mapreduce.filecache.ClientDistributedCacheManager.getFileStatus(ClientDistributedCacheManager.java:288) ~[hadoop-mapreduce-client-core-2.7.1.jar:?]
	at org.apache.hadoop.mapreduce.filecache.ClientDistributedCacheManager.getFileStatus(ClientDistributedCacheManager.java:224) ~[hadoop-mapreduce-client-core-2.7.1.jar:?]
	at org.apache.hadoop.mapreduce.filecache.ClientDistributedCacheManager.determineTimestamps(ClientDistributedCacheManager.java:99) ~[hadoop-mapreduce-client-core-2.7.1.jar:?]
	at org.apache.hadoop.mapreduce.filecache.ClientDistributedCacheManager.determineTimestampsAndCacheVisibilities(ClientDistributedCacheManager.java:57) ~[hadoop-mapreduce-client-core-2.7.1.jar:?]
	at org.apache.hadoop.mapreduce.JobResourceUploader.uploadFiles(JobResourceUploader.java:179) ~[hadoop-mapreduce-client-core-2.7.1.jar:?]
	at org.apache.hadoop.mapreduce.JobSubmitter.copyAndConfigureFiles(JobSubmitter.java:95) ~[hadoop-mapreduce-client-core-2.7.1.jar:?]
	at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:190) ~[hadoop-mapreduce-client-core-2.7.1.jar:?]
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1290) ~[hadoop-mapreduce-client-core-2.7.1.jar:?]
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1287) ~[hadoop-mapreduce-client-core-2.7.1.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_71]
	at javax.security.auth.Subject.doAs(Subject.java:415) ~[?:1.7.0_71]
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657) ~[hadoop-common-2.7.1.jar:?]
	at org.apache.hadoop.mapreduce.Job.submit(Job.java:1287) ~[hadoop-mapreduce-client-core-2.7.1.jar:?]
	at io.druid.indexer.IndexGeneratorJob.run(IndexGeneratorJob.java:199) ~[druid-indexing-hadoop-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at io.druid.indexer.JobHelper.runJobs(JobHelper.java:323) ~[druid-indexing-hadoop-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at io.druid.indexer.HadoopDruidIndexerJob.run(HadoopDruidIndexerJob.java:94) ~[druid-indexing-hadoop-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at io.druid.indexing.common.task.HadoopIndexTask$HadoopIndexGeneratorInnerProcessing.runTask(HadoopIndexTask.java:261) ~[druid-indexing-service-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:198) ~[druid-indexing-service-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
	... 7 more
2016-03-23T10:12:24,726 INFO [task-runner-0-priority-0] io.druid.indexing.worker.executor.ExecutorLifecycle - Task completed with status: {
  "id" : "index_hadoop_myds_2016-03-23T10:11:34.355+08:00",
  "status" : "FAILED",
  "duration" : 42553
}
```

I can see uploading success for the first job
```
2016-03-23T13:07:51,478 INFO [task-runner-0-priority-0] io.druid.indexer.JobHelper - Uploading jar to path[/tmp/druid-indexing/myds/2016-03-23T130738.821+0800/f07c492a80a24c3086b733b085cc8f2d/classpath/druid-processing-0.9.0-SNAPSHOT.jar]
```

It seem a bug related to DistributedCache.

Maybe the hadoop system deleted our Distributed Cache just after the first job succeed.

**Comment by hamlet-lee** [comment]
I found this line in task log, it seems we deleted the path...
```
io.druid.indexer.JobHelper - Deleting path[/tmp/druid-indexing/myds/2016-03-23T130738.821+0800/f07c492a80a24c3086b733b085cc8f2d]
```

it is deleted in the method: JobHelper.runJobs()

**Comment by hamlet-lee** [comment]
try to fix by https://github.com/druid-io/druid/pull/2708

**Comment by himanshug** [comment]
what is your full task log, it doesn't look like that #2708 would fix the problem you have.

- do you consistently see that happening or just some times? if consistently , then does #2708 fix the problem?
- it might be related to SNAPSHOT jar , can you change your version to non-snapshot and try ?

**Comment by hamlet-lee** [comment]
> what is your full task log, it doesn't look like that #2708 would fix the problem you have.

the error task's log 

the success task's log


> do you consistently see that happening or just some times? if consistently , then does #2708 fix the problem?

I just some times see that happening.  #2708 fixed that, I can see from the log.

> it might be related to SNAPSHOT jar , can you change your version to non-snapshot and try ?

I browse JobHelper's code, it seems surely related to SNAPSHOT

**Comment by hamlet-lee** [comment]
After examine the success and fail log. I suspect the problem come from "Version" fields in task's spec.

Version is generated both for `determine task` and `index task`.
Most of the cases, the two versions are very close, for example:
(in succ_chg.txt)
`2016-03-24T08:31:47.081+08:00` and ` 2016-03-24T08:31:47.082+08:00`

But sometimes, the two versions may have the same version number.
(in file_not_found_chg.txt)
`2016-03-23T10:11:34.355+08:00` and `2016-03-23T10:11:34.355+08:00`

The `version` is used to cretae temp directory name
(in HadoopDruidIndexerConfig.java)
```
  public Path makeIntermediatePath()
  {
    return new Path(
        String.format(
            "%s/%s/%s/%s",
            getWorkingPath(),
            schema.getDataSchema().getDataSource(),
            schema.getTuningConfig().getVersion().replace(":", ""),
            schema.getUniqueId()
        )
    );
  }
```

If `determine task` and `index task` have the same `version`, they will have same `intermediatePath`.

When this happend, the intermediate path will be removed after `determine task` finished.
And because the second task have the same intermediate path, it will not upload the jars again during checking from JobHelper.

```
  static void addSnapshotJarToClassPath(
      File jarFile,
      Path intermediateClassPath,
      FileSystem fs,
      Job job
  ) throws IOException
  {
    // Snapshot jars are uploaded to non shared intermediate directory.
    final Path hdfsPath = new Path(intermediateClassPath, jarFile.getName());

    // existing is used to prevent uploading file multiple times in same run.
    if (!existing.contains(hdfsPath)) {                  //hamlet-lee: here, path conflicts
      uploadJar(jarFile, hdfsPath, fs);
      existing.add(hdfsPath);
    }
    job.addFileToClassPath(hdfsPath);
  }
```

So, there are 3 possible solutions:
1) change logic of HadoopDruidIndexerConfig.makeIntermediatePath() to generate a unique directory name each time
2) change logic of JobHelper.runJobs(), and remove the deleted paths from JobHelper.existing
3) change the logic of `version` generating

I think the 1st solution would be good enough.

**Comment by hamlet-lee** [comment]
updated pull request: https://github.com/druid-io/druid/pull/2708

**Comment by drewdahlke** [comment]
I was trying the hadoop job in druid .9.1 rc4 and hit the same exact bug on every try. Pulling in @hamlet-lee's PR fixed it and the job ran perfectly. +1

**Comment by drcrallen** [comment]
IMHO your proposed solution #1 is the correct one: 

`change logic of HadoopDruidIndexerConfig.makeIntermediatePath() to generate a unique directory name each time`

fix the intermediate path to generate something that is unique per job.

**Comment by hamlet-lee** [comment]
@drcrallen  what do you think by this approach?
```
  public Path makeIntermediatePath()
  {
    return new Path(
        String.format(
            "%s/%s/%s/%s/%s",
            getWorkingPath(),
            schema.getDataSchema().getDataSource(),
            schema.getTuningConfig().getVersion().replace(":", ""),
            schema.getUniqueId(),
            UUID.randomUUID().toString()  //add unique sub dir
        )
    );
  }
```

**Comment by drcrallen** [comment]
@hamlet-lee are you setting `uniqueId` for the hadoop ingestion spec? if not, then `schema.getUniqueId()` should be doing what you are proposing

**Comment by drcrallen** [comment]
Note this was added in druid 0.9.0

**Comment by hamlet-lee** [comment]
@drcrallen schema.getUniqueId() seems not unique enough.  Consecutive calling getUniqueId() do not always produce different intermediate paths.  So "determine" and "index" task may conflict. This is one cause of this issue.
