### ISSUE TITLE
Real time Node merge index throws NPE after adding Metrics

### ISSUE THREAD

**Issue by Hailei** [druid-io/druid#2744]
@michaelschiff  @gianm 
Druid version  0.8.2
Segment Granularity: HOUR
My problem is very similar with this closed issue #145,
Around 40 minutes after an hour, I added a longSum metric and restarted the node.
when merging index,will throw NPE
```java
java.lang.NullPointerException
   at io.druid.query.aggregation.LongSumAggregator.combineValues(LongSumAggregator.java:39) ~[druid-processing-0.8.2.jar:0.8.2]
   at io.druid.query.aggregation.LongSumAggregatorFactory.combine(LongSumAggregatorFactory.java:78) ~[druid-processing-0.8.2.jar:0.8.2]
   at io.druid.segment.IndexMerger$RowboatMergeFunction.apply(IndexMerger.java:1260) ~[druid-processing-0.8.2.jar:0.8.2]
   at io.druid.segment.IndexMerger$RowboatMergeFunction.apply(IndexMerger.java:1236) ~[druid-processing-0.8.2.jar:0.8.2]
   at io.druid.collections.CombiningIterator.next(CombiningIterator.java:78) ~[druid-common-0.8.2.jar:0.8.2]
   at io.druid.segment.IndexMerger.makeIndexFiles(IndexMerger.java:747) ~[druid-processing-0.8.2.jar:0.8.2]
   at io.druid.segment.IndexMerger.merge(IndexMerger.java:351) ~[druid-processing-0.8.2.jar:0.8.2]
   at io.druid.segment.IndexMerger.mergeQueryableIndex(IndexMerger.java:227) ~[druid-processing-0.8.2.jar:0.8.2]
   at io.druid.segment.IndexMerger.mergeQueryableIndex(IndexMerger.java:216) ~[druid-processing-0.8.2.jar:0.8.2]
```

So I think this issue hasn't been resolved.

look into the following code of IndexMerger line number from 657 to 688.
```java
 boats.add(
          new MMappedIndexRowIterable(
              Iterables.transform(
                  indexes.get(i).getRows(),
                  new Function<Rowboat, Rowboat>()
                  {
                    @Override
                    public Rowboat apply(@Nullable Rowboat input)
                    {
                      int[][] newDims = new int[mergedDimensions.size()][];
                      int j = 0;
                      for (int[] dim : input.getDims()) {
                        newDims[dimLookup[j]] = dim;
                        j++;
                      }

                      Object[] newMetrics = new Object[mergedMetrics.size()];
                      j = 0;
                      for (Object met : input.getMetrics()) {
                        newMetrics[metricLookup[j]] = met;
                        j++;
                      }

                      return new Rowboat(
                          input.getTimestamp(),
                          newDims,
                          newMetrics,
                          input.getRowNum()
                      );
                    }
                  }
              )
```

Build newMetrics base on the metric of  input row. the previous indexes don't have new addition metric, So in the newMetrics,the value of new addition metric is null
```java
  for (Object met : input.getMetrics()) {
      newMetrics[metricLookup[j]] = met;
      j++;
  }
```

modify the code of LongSumAggregator ,first check for not null,it work well.
```java
 static long combineValues(Object lhs, Object rhs) {
	if(lhs == null){
		lhs = 0L;
	}
	if(rhs == null){
		rhs = 0L;
	}
    return ((Number) lhs).longValue() + ((Number) rhs).longValue();
  }
```

I found  that pull requst #2257 can solve NPE when adding metric.
But I add following unit test on Build 0.9.1-rc1,still throw NPE

```java
@Test
  public void testAddMetrics() throws IOException
  {
    IncrementalIndex index1 = IncrementalIndexTest.createIndex(new AggregatorFactory[]{
        new LongSumAggregatorFactory("A", "A")
    });
    closer.closeLater(index1);
    long timestamp  = System.currentTimeMillis();
    index1.add(
            new MapBasedInputRow(
                timestamp,
                Arrays.asList("dim1", "dim2"),
                ImmutableMap.<String, Object>of("dim1", "1", "dim2", "2","A",5)
            )
        );

    IncrementalIndex index2 = IncrementalIndexTest.createIndex(new AggregatorFactory[]{
        new LongSumAggregatorFactory("A", "A"),
        new LongSumAggregatorFactory("C", "C")
    });
    
    index2.add(
            new MapBasedInputRow(
                timestamp,
                Arrays.asList("dim1", "dim2"),
                ImmutableMap.<String, Object>of("dim1", "1", "dim2", "2","A",5,"C",6)
            )
    );
    
    closer.closeLater(index2);
    
    Interval interval = new Interval(0, new DateTime().getMillis());
    RoaringBitmapFactory factory = new RoaringBitmapFactory();
    ArrayList<IndexableAdapter> toMerge = Lists.<IndexableAdapter>newArrayList(
        new IncrementalIndexAdapter(interval, index1, factory),
        new IncrementalIndexAdapter(interval, index2, factory)

    );

    final File tmpDirMerged = temporaryFolder.newFolder();

    File merged = INDEX_MERGER.merge(
        toMerge,
        new AggregatorFactory[]{
            new LongSumAggregatorFactory("A", "A"),
            new LongSumAggregatorFactory("C", "C")
        },
        tmpDirMerged,
        indexSpec
    );
    final QueryableIndexStorageAdapter adapter = new QueryableIndexStorageAdapter(closer.closeLater(INDEX_IO.loadIndex(merged)));
    Assert.assertEquals(ImmutableSet.of("A","C"), ImmutableSet.copyOf(adapter.getAvailableMetrics()));

  }
```
can reproduce NPE

**Comment by michaelschiff** [comment]
@Hailei @gianm Yep, I was able to reproduce as well, and think you are correct about what is going on. 

I looked at #175 (which closes #145) and didn't actually see anything that addressed this issue. #2257 fixes a different case, so it would seem this bug is still present.

I think instead of checking for null in the Aggregator we can modify RowboatMergeFunction.apply 
`      Object[] metrics = new Object[metricAggs.length];
      Object[] lhsMetrics = lhs.getMetrics();
      Object[] rhsMetrics = rhs.getMetrics();

      for (int i = 0; i < metrics.length; ++i) {
          Object lhsMetric = lhsMetrics[i];
          Object rhsMetric = rhsMetrics[i];
          if (lhsMetric == null) {
              metrics[i] = rhsMetric;
          } else if (rhsMetric == null) {
              metrics[i] = lhsMetric;
          } else {
              metrics[i] = metricAggs[i].combine(lhsMetric, rhsMetric);
          }
      }`
This avoids having to modify every aggregator type.

**Comment by Hailei** [comment]
```java
for (int i = 0; i < metrics.length; ++i) {
      Object lhsMetric = lhsMetrics[i];
      Object rhsMetric = rhsMetrics[i];
      if (lhsMetric == null) {
          metrics[i] = rhsMetric;
      } else if (rhsMetric == null) {
          metrics[i] = lhsMetric;
      } else {
          metrics[i] = metricAggs[i].combine(lhsMetric, rhsMetric);
      }
  }

```


@michaelschiff  I think it's the robust way to solve this issue

**Comment by binlijin** [comment]
@Hailei, what would happen if both lhsMetric and rhsMetric == null?

**Comment by Hailei** [comment]
@binlijin I think  that both lhsMetric and rhsMetric == null  is impossible. In most case,only one of them is null.

**Comment by michaelschiff** [comment]
@binlijin @Hailei I have been able to reproduce the case where lhsMetric and rhsMetric == null in unit tests. I am not sure whether or not it would happen in practice, but it's definitely possible.  

In this case, the value of metrics[i] is set to null. The unit tests still passes, but I could imagine potential funkiness at query time.

**Comment by binlijin** [comment]
I think it good to handle all case.

**Comment by michaelschiff** [comment]
@binlijin @Hailei I agree. To me the most correct thing to do in the case where rhsMetric and lhsMetric == null would be to supply a zero-value. However since the metrics are not typed at this point, this becomes trickier to do in RowboatMergeFunction.apply.  I would like to confirm whether or not a null metric value for this index is a valid solution. @gianm @drcrallen any thoughts?

**Comment by Hailei** [comment]
@michaelschiff @binlijin @gianm @drcrallen 
I have checked the code that is related to LongSum DoubleSum and HyperUnique Complex metrics(e.g HyperUnique)
I think all of these have checked for null.Both LongSum and DoubleSum ,if the value of metrics is null ,it will be converted to 0 int the process of build index.

But not sure all complex like this.

LongMetricColumnSerializer
```java
 @Override
  public void serialize(Object obj) throws IOException
  {
    long val = (obj == null) ? 0 : ((Number) obj).longValue();
    writer.add(val);
  }
```
HyperUniquesBufferAggregator
```java
 @Override
  public void aggregate(ByteBuffer buf, int position)
  {
    HyperLogLogCollector collector = (HyperLogLogCollector) selector.get();

    if (collector == null) {
      return;
    }

    HyperLogLogCollector.makeCollector(
        (ByteBuffer) buf.duplicate().position(position).limit(
            position
            + HyperLogLogCollector.getLatestNumBytesForDenseStorage()
        )
    ).fold(collector);
  }
```
HyperUniquesSerde
```java
    @Override
      public byte[] toBytes(HyperLogLogCollector collector)
      {
        if (collector == null) {
          return new byte[]{};
        }
        ByteBuffer val = collector.toByteBuffer();
        byte[] retVal = new byte[val.remaining()];
        val.asReadOnlyBuffer().get(retVal);
        return retVal;
      }

```

**Comment by michaelschiff** [comment]
@Hailei thats good news, in this case I think setting metrics[i] = null would be a valid solution.

**Comment by michaelschiff** [comment]
@Hailei @fjy everyone good to close this?

**Comment by Hailei** [comment]
Thanks  @michaelschiff
