### ISSUE TITLE
Add ability to handle s3a URIs

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#2748]
More recent implementations of Hadoop's FS use [s3a](https://wiki.apache.org/hadoop/AmazonS3) scheme for native Amazon library access to S3.

There are a few places in the druid code that assume a file is either `s3` or `s3n` to use the s3 extensions.

This ask is that the uri scheme for `s3a` is properly handled.

**Comment by saurabhere** [comment]
Is there any ETA/ release version for this feature to be implemented yet? 
We also need to access S3 for hadoop ingestion and always passing AWS credentials is not safe. Can it at least be hidden in the task logs?

**Comment by gianm** [comment]
@saurabhere no ETA that I am aware of.

You should be able to work around this, though, by setting `fs.s3.impl` and `fs.s3n.impl` both to "org.apache.hadoop.fs.s3a.S3AFileSystem" and possibly setting some other properties too. That should get the system into using s3a for all `s3://` and `s3n://` urls, and it should be able to use your instance roles.

**Comment by saurabhere** [comment]
I tried that.
I got
```
Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2101) ~[?:?]
```
So, I downloaded hadoop-aws-2.7.3 explicitely into hadoop-dependencies
Then, i got
```
Caused by: java.lang.NoSuchMethodError: com.amazonaws.services.s3.transfer.TransferManagerConfiguration.setMultipartUploadThreshold(I)V
	at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:285) ~[?:?]
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669) ~[?:?]
```
Then I tried copying aws-java-sdk-s3-1.10.21(and its dependencies aws-java-sdk-core and aws-java-sdk-kms)  to the hadoop-dependencies in vain. 
Is there something else I can do?

**Comment by saurabhere** [comment]
So, I built my own version of hadoop-2.7.3 by changing the aws-java-sdk version dependency to 1.10.21 and updating the call to `TransferManagerConfiguration.setMultipartUploadThreshold(L)`,
and it works smoothly.
Thanks @gianm for the vote of confidence. :grin:

**Comment by gianm** [comment]
Yay 😄

I'd like to add official support for this at some point but I'm glad you found a workaround.

**Comment by RobertErvin** [comment]
+1

**Comment by b-slim** [comment]
related to https://github.com/druid-io/druid/pull/3940

**Comment by dene14** [comment]
@drcrallen shouldn't it be closed now?
