### ISSUE TITLE
SelectQueryQueryToolchest.filterSegments break if dataSource name contains DataSegment.delimiter

### ISSUE THREAD

**Issue by nishantmonu51** [druid-io/druid#2786]
SelectQuery with pagingSpec breaks when datasource name contains DataSegment.delimiter i.e '_' e.g test_ds. 
Refer to SegmentDesc.valueOf() method which splits the segmentIdentifier and fails with dataSource name containing an underscore. 

Stack trace for failure - 
java.lang.IllegalArgumentException: Invalid format: "ds"
	at org.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:187)
	at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:780)
	at org.joda.time.convert.StringConverter.getInstantMillis(StringConverter.java:65)
	at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:175)
	at org.joda.time.DateTime.<init>(DateTime.java:257)
	at io.druid.segment.SegmentDesc.valueOf(SegmentDesc.java:52)

**Comment by nishantmonu51** [comment]
@navis, It was introduced in https://github.com/druid-io/druid/pull/2480
can you take a look into it  ?

**Comment by navis** [comment]
@nishantmonu51 my bad. fixed in #2797

**Comment by nishantmonu51** [comment]
fixed by https://github.com/druid-io/druid/pull/2797
