### ISSUE TITLE
Overlord cannot connect to Derby in a docker container

### ISSUE THREAD

**Issue by l15k4** [druid-io/druid#2904]
Hey,

I have this cluster setup built on implydata `distribution` and `distribution-docker` in ec2 cloud : 

- 2 query nodes with Broker and Pivot
- 2 historical nodes
- 1 indexer node with MiddleManager and Peons
- 1 master node with ZooKeeper, Overlord, Coordinator, Derby

But Overlord cannot connect to Derby on locahost:1527. Which is weird because I can do :
```
root@4673d6248275:~/imply-1.2.0# ./bin/derby-client conf-interpolated/druid 
ij version 10.11
DRUID* -        jdbc:derby://localhost:1527/var/druid/metadata.db
* = current connection
ij> 
```

org.skife.jdbi.v2.exceptions.UnableToObtainConnectionException: java.sql.SQLException: Cannot create PoolableConnectionFactory (java.net.ConnectException : Error connecting to server localhost on port 1,527 with message Connection refused.)
at org.skife.jdbi.v2.DBI.open(DBI.java:230) ~[jdbi-2.63.1.jar:2.63.1]
at org.skife.jdbi.v2.DBI.withHandle(DBI.java:279) ~[jdbi-2.63.1.jar:2.63.1]
at io.druid.metadata.SQLMetadataConnector$2.call(SQLMetadataConnector.java:113) ~[druid-server-0.9.0.jar:0.9.0]
at com.metamx.common.RetryUtils.retry(RetryUtils.java:38) [java-util-0.27.7.jar:?]
at io.druid.metadata.SQLMetadataConnector.retryWithHandle(SQLMetadataConnector.java:118) [druid-server-0.9.0.jar:0.9.0]
at io.druid.metadata.SQLMetadataConnector.retryWithHandle(SQLMetadataConnector.java:127) [druid-server-0.9.0.jar:0.9.0]
at io.druid.metadata.SQLMetadataConnector.createTable(SQLMetadataConnector.java:168) [druid-server-0.9.0.jar:0.9.0]
at io.druid.metadata.SQLMetadataConnector.createConfigTable(SQLMetadataConnector.java:267) [druid-server-0.9.0.jar:0.9.0]
at io.druid.metadata.SQLMetadataConnector.createConfigTable(SQLMetadataConnector.java:421) [druid-server-0.9.0.jar:0.9.0]
at io.druid.guice.JacksonConfigManagerModule$1.start(JacksonConfigManagerModule.java:58) [druid-common-0.9.0.jar:0.9.0]
at com.metamx.common.lifecycle.Lifecycle.start(Lifecycle.java:259) [java-util-0.27.7.jar:?]
at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:155) [druid-api-0.3.16.jar:0.9.0]
at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:91) [druid-services-0.9.0.jar:0.9.0]
at io.druid.cli.ServerRunnable.run(ServerRunnable.java:40) [druid-services-0.9.0.jar:0.9.0]
at io.druid.cli.Main.main(Main.java:105) [druid-services-0.9.0.jar:0.9.0]
Caused by: java.sql.SQLException: Cannot create PoolableConnectionFactory (java.net.ConnectException : Error connecting to server localhost on port 1,527 with message Connection refused.)
at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2152) ~[commons-dbcp2-2.0.1.jar:2.0.1]
at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:1903) ~[commons-dbcp2-2.0.1.jar:2.0.1]
at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1413) ~[commons-dbcp2-2.0.1.jar:2.0.1]
at org.skife.jdbi.v2.DataSourceConnectionFactory.openConnection(DataSourceConnectionFactory.java:36) ~[jdbi-2.63.1.jar:2.63.1]
at org.skife.jdbi.v2.DBI.open(DBI.java:212) ~[jdbi-2.63.1.jar:2.63.1]
... 14 more

**Comment by l15k4** [comment]
Hm, the hostname is OK ... so the issue is just that Overlord cannot connect to Derby on `locahost:1527`. Which is weird because I can do : 

```
root@4673d6248275:~/imply-1.2.0# ./bin/derby-client conf-interpolated/druid 
ij version 10.11
DRUID* -        jdbc:derby://localhost:1527/var/druid/metadata.db
* = current connection
ij> 
```


org.skife.jdbi.v2.exceptions.UnableToObtainConnectionException: java.sql.SQLException: Cannot create PoolableConnectionFactory (java.net.ConnectException : Error connecting to server localhost on port 1,527 with message Connection refused.)
        at org.skife.jdbi.v2.DBI.open(DBI.java:230) ~[jdbi-2.63.1.jar:2.63.1]
        at org.skife.jdbi.v2.DBI.withHandle(DBI.java:279) ~[jdbi-2.63.1.jar:2.63.1]
        at io.druid.metadata.SQLMetadataConnector$2.call(SQLMetadataConnector.java:113) ~[druid-server-0.9.0.jar:0.9.0]
        at com.metamx.common.RetryUtils.retry(RetryUtils.java:38) [java-util-0.27.7.jar:?]
        at io.druid.metadata.SQLMetadataConnector.retryWithHandle(SQLMetadataConnector.java:118) [druid-server-0.9.0.jar:0.9.0]
        at io.druid.metadata.SQLMetadataConnector.retryWithHandle(SQLMetadataConnector.java:127) [druid-server-0.9.0.jar:0.9.0]
        at io.druid.metadata.SQLMetadataConnector.createTable(SQLMetadataConnector.java:168) [druid-server-0.9.0.jar:0.9.0]
        at io.druid.metadata.SQLMetadataConnector.createConfigTable(SQLMetadataConnector.java:267) [druid-server-0.9.0.jar:0.9.0]
        at io.druid.metadata.SQLMetadataConnector.createConfigTable(SQLMetadataConnector.java:421) [druid-server-0.9.0.jar:0.9.0]
        at io.druid.guice.JacksonConfigManagerModule$1.start(JacksonConfigManagerModule.java:58) [druid-common-0.9.0.jar:0.9.0]
        at com.metamx.common.lifecycle.Lifecycle.start(Lifecycle.java:259) [java-util-0.27.7.jar:?]
        at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:155) [druid-api-0.3.16.jar:0.9.0]
        at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:91) [druid-services-0.9.0.jar:0.9.0]
        at io.druid.cli.ServerRunnable.run(ServerRunnable.java:40) [druid-services-0.9.0.jar:0.9.0]
        at io.druid.cli.Main.main(Main.java:105) [druid-services-0.9.0.jar:0.9.0]
Caused by: java.sql.SQLException: Cannot create PoolableConnectionFactory (java.net.ConnectException : Error connecting to server localhost on port 1,527 with message Connection refused.)
        at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2152) ~[commons-dbcp2-2.0.1.jar:2.0.1]
        at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:1903) ~[commons-dbcp2-2.0.1.jar:2.0.1]
        at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1413) ~[commons-dbcp2-2.0.1.jar:2.0.1]
        at org.skife.jdbi.v2.DataSourceConnectionFactory.openConnection(DataSourceConnectionFactory.java:36) ~[jdbi-2.63.1.jar:2.63.1]
        at org.skife.jdbi.v2.DBI.open(DBI.java:212) ~[jdbi-2.63.1.jar:2.63.1]
        ... 14 more

**Comment by l15k4** [comment]
It seems to be a racing condition : 
```
!p10 zk bin/run-zk conf
coordinator bin/run-druid coordinator conf
!p80 overlord bin/run-druid overlord conf
```

by the time `overlord` started `Derby` is not accepting connections yet (or is not started yet) ... There should be a little `sleep` between `coordinator` and `overlord` boot ups ...

**Comment by fjy** [comment]
@l15k4 tbh the docker distro hasn't really been tested and has seen no production use

You may want to check out: https://hub.docker.com/r/imply/imply/

**Comment by l15k4** [comment]
@fjy Yeah I'm using both https://github.com/implydata/distribution-docker and https://github.com/implydata/distribution ... A little modified versions though. It seems to be working fine, both the quickstart and the cluster setup. There is a last issue I'm facing https://groups.google.com/forum/#!topic/druid-user/lxY7fWGE03M but apart from that I'm ready for production.
