### ISSUE TITLE
RemoteTaskRunnerRunPendingTasksConcurrencyTest Transient testing issue

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#2911]
`io.druid.indexing.overlord.RemoteTaskRunnerRunPendingTasksConcurrencyTest` can fail in the following way:

```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.193 sec <<< FAILURE! - in io.druid.indexing.overlord.RemoteTaskRunnerRunPendingTasksConcurrencyTest
testConcurrency(io.druid.indexing.overlord.RemoteTaskRunnerRunPendingTasksConcurrencyTest)  Time elapsed: 1.191 sec  <<< ERROR!
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /test/druid/indexer/tasks/worker1/task2
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:111)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.delete(ZooKeeper.java:873)
	at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:243)
	at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:237)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:108)
	at org.apache.curator.framework.imps.DeleteBuilderImpl.pathInForeground(DeleteBuilderImpl.java:234)
	at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:218)
	at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:42)
	at io.druid.indexing.overlord.RemoteTaskRunnerTestUtils.mockWorkerRunningTask(RemoteTaskRunnerTestUtils.java:161)
	at io.druid.indexing.overlord.RemoteTaskRunnerRunPendingTasksConcurrencyTest.testConcurrency(RemoteTaskRunnerRunPendingTasksConcurrencyTest.java:123)
```

**Comment by drcrallen** [comment]
https://travis-ci.org/druid-io/druid/jobs/127192620
