### ISSUE TITLE
Druid 0.9 coordinatorBasedSegmentHandoffNotifier cannot find instance of coordinator

### ISSUE THREAD

**Issue by redlion99** [druid-io/druid#2994]
2016-05-19T19:30:37,026 ERROR [coordinator_handoff_scheduled_0] io.druid.curator.discovery.ServerDiscoverySelector - No server instance found
2016-05-19T19:30:37,027 ERROR [coordinator_handoff_scheduled_0] io.druid.segment.realtime.plumber.CoordinatorBasedSegmentHandoffNotifier - Exception while checking handoff for dataSource[cl_events_test] Segment[SegmentDescriptor{interval=2016-05-19T00:00:00.000Z/2016-05-19T06:00:00.000Z, version='2016-05-19T00:49:21.097Z', partitionNumber=0}], Will try again after [60000]secs
com.metamx.common.ISE: Cannot find instance of coordinator
	at io.druid.client.coordinator.CoordinatorClient.baseUrl(CoordinatorClient.java:108) ~[druid-server-0.9.0.jar:0.9.0]
	at io.druid.client.coordinator.CoordinatorClient.fetchServerView(CoordinatorClient.java:74) ~[druid-server-0.9.0.jar:0.9.0]
	at io.druid.segment.realtime.plumber.CoordinatorBasedSegmentHandoffNotifier.checkForSegmentHandoffs(CoordinatorBasedSegmentHandoffNotifier.java:101) [druid-server-0.9.0.jar:0.9.0]
	at io.druid.segment.realtime.plumber.CoordinatorBasedSegmentHandoffNotifier$1.run(CoordinatorBasedSegmentHandoffNotifier.java:86) [druid-server-0.9.0.jar:0.9.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72-internal]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_72-internal]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_72-internal]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_72-internal]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72-internal]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]

**Comment by redlion99** [comment]
druid.selectors.coordinator.serviceName is required since 0.8.3
