### ISSUE TITLE
Realtime nodes wont start if using roaring bitmaps

### ISSUE THREAD

**Issue by pdeva** [druid-io/druid#3014]
Druid 0.9.0.

Exception:

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class io.druid.segment.data.BitmapSerde$DefaultBitmapSerdeFactory] from String value ('roaring'); no single-String constructor/factory method
 at [Source: /opt/druid/conf/druid/realtime/dripstatspec.json; line: 95, column: 9] (through reference chain: java.util.ArrayList[0])
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:770) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:277) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:289) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1141) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:135) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:126) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:129) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:75) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:132) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:536) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:344) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1064) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:264) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:124) ~[jackson-databind-2.4.6.jar:2.4.6]
```
Here is the tuning config:

```
    "tuningConfig": {
      "type" : "realtime",
      "maxRowsInMemory": 500000,
      "intermediatePersistPeriod": "PT10m",
      "windowPeriod": "PT10m",
      "basePersistDirectory": "/data/realtime/basePersist",
      "rejectionPolicy": {
        "type": "serverTime"
      },
      "indexSpec": {
        "bitmap":"roaring"
      },
      "shardSpec": {
        "type": "linear",
        "partitionNum": 0
      }
    }
```

**Comment by gianm** [comment]
it's `"indexSpec": { "bitmap" : { "type": "roaring" } }`

**Comment by pdeva** [comment]
yup that works
