### ISSUE TITLE
FilteredAggregator with predicate-based ValueMatcher fails during ingestion

### ISSUE THREAD

**Issue by jon-wei** [druid-io/druid#3164]
During ingestion, If I use a FilteredAggregator with a filter that is implemented with a predicate-based ValueMatcher (e.g., BoundFilter), the following exception is thrown:

```
java.lang.UnsupportedOperationException: value cardinality is unknown in incremental index
	at io.druid.segment.incremental.IncrementalIndex$4$6.getValueCardinality(IncrementalIndex.java:321)
	at io.druid.query.aggregation.FilteredAggregatorFactory$FilteredAggregatorValueMatcherFactory.makeValueMatcher(FilteredAggregatorFactory.java:273)
	at io.druid.segment.filter.BoundFilter.makeMatcher(BoundFilter.java:143)
	at io.druid.segment.filter.OrFilter.makeMatcher(OrFilter.java:69)
	at io.druid.query.aggregation.FilteredAggregatorFactory.factorize(FilteredAggregatorFactory.java:64)
	at io.druid.segment.incremental.OnheapIncrementalIndex.factorizeAggs(OnheapIncrementalIndex.java:212)
	at io.druid.segment.incremental.OnheapIncrementalIndex.addToFacts(OnheapIncrementalIndex.java:176)
	at io.druid.segment.incremental.IncrementalIndex.add(IncrementalIndex.java:568)
	at io.druid.benchmark.FilteredAggregatorBenchmark.ingest(FilteredAggregatorBenchmark.java:277)
...
```

The ColumnSelectorFactory implementation in IncrementalIndex does not support getValueCardinality():
```
          @Override
          public int getValueCardinality()
          {
            throw new UnsupportedOperationException("value cardinality is unknown in incremental index");
          }
```

**Comment by gianm** [comment]
Fixed by #3312
