### ISSUE TITLE
Validation of realtime.properties doesn't work

### ISSUE THREAD

**Issue by maxd** [druid-io/druid#317]
Hello All,

Instead of information about validation problems I see the following exception:

~~~
2013-12-04 11:02:11,579 INFO [main] io.druid.guice.JsonConfigurator - Loaded class[class io.druid.server.metrics.MonitorsConfig] from props[druid.monitoring.] as [MonitorsConfig{monitors=[]}]
Exception in thread "main" java.lang.NoClassDefFoundError: javax/el/PropertyNotFoundException
        at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.interpolateExpression(ResourceBundleMessageInterpolator.java:227)
        at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.interpolateMessage(ResourceBundleMessageInterpolator.java:187)
        at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.interpolate(ResourceBundleMessageInterpolator.java:115)
        at org.hibernate.validator.internal.engine.ValidationContext.interpolate(ValidationContext.java:370)
        at org.hibernate.validator.internal.engine.ValidationContext.createConstraintViolation(ValidationContext.java:284)
        at org.hibernate.validator.internal.engine.ValidationContext.createConstraintViolations(ValidationContext.java:246)
        at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateSingleConstraint(ConstraintTree.java:289)
        at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:133)
        at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:91)
        at org.hibernate.validator.internal.metadata.core.MetaConstraint.validateConstraint(MetaConstraint.java:85)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraint(ValidatorImpl.java:478)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForDefaultGroup(ValidatorImpl.java:424)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForCurrentGroup(ValidatorImpl.java:388)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:340)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:158)
        at io.druid.guice.JsonConfigurator.configurate(JsonConfigurator.java:90)
        at io.druid.guice.JsonConfigProvider.get(JsonConfigProvider.java:181)
        at io.druid.guice.JsonConfigProvider.get(JsonConfigProvider.java:60)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:55)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1058)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)

...

        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1058)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1051)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:96)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at io.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:317)
        at io.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:56)
        at io.druid.cli.ServerRunnable.run(ServerRunnable.java:39)
        at io.druid.cli.Main.main(Main.java:88)
Caused by: java.lang.ClassNotFoundException: javax.el.PropertyNotFoundException
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)

...

~~~

I have added the following dependencies to the `pom.xml` and `services/pom.xml` files and rebuilded project:

~~~
        <dependency>
            <groupId>javax.el</groupId>
            <artifactId>javax.el-api</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.sun.el</groupId>
            <artifactId>el-ri</artifactId>
            <version>1.0</version>
        </dependency>
~~~

It fixed problem. Now I see approprimate validation messages:

~~~
Exception in thread "main" com.google.inject.CreationException: Guice creation errors:

1) druid.host - may not be null
  at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:112)
  at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:112)
  while locating com.google.common.base.Supplier<io.druid.server.DruidNode> annotated with @io.druid.guice.annotations.Self()
  at io.druid.server.initialization.EmitterModule.getServiceEmitter(EmitterModule.java:80)
  at io.druid.server.initialization.EmitterModule.getServiceEmitter(EmitterModule.java:80)
  while locating com.metamx.emitter.service.ServiceEmitter
  at io.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:80)
  at io.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:80)
  while locating com.metamx.metrics.MonitorScheduler
  at io.druid.server.metrics.MetricsModule.configure(MetricsModule.java:65)
  while locating com.metamx.metrics.MonitorScheduler annotated with @com.google.inject.name.Named(value=ForTheEagerness)

2) druid.port - must be greater than or equal to 0
  at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:112)
  at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:112)
  while locating com.google.common.base.Supplier<io.druid.server.DruidNode> annotated with @io.druid.guice.annotations.Self()
  at io.druid.server.initialization.EmitterModule.getServiceEmitter(EmitterModule.java:80)
  at io.druid.server.initialization.EmitterModule.getServiceEmitter(EmitterModule.java:80)
  while locating com.metamx.emitter.service.ServiceEmitter
  at io.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:80)
  at io.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:80)
  while locating com.metamx.metrics.MonitorScheduler
  at io.druid.server.metrics.MetricsModule.configure(MetricsModule.java:65)
  while locating com.metamx.metrics.MonitorScheduler annotated with @com.google.inject.name.Named(value=ForTheEagerness)

3) druid.service - may not be null
  at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:112)
  at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:112)
  while locating com.google.common.base.Supplier<io.druid.server.DruidNode> annotated with @io.druid.guice.annotations.Self()
  at io.druid.server.initialization.EmitterModule.getServiceEmitter(EmitterModule.java:80)
  at io.druid.server.initialization.EmitterModule.getServiceEmitter(EmitterModule.java:80)
  while locating com.metamx.emitter.service.ServiceEmitter
  at io.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:80)
  at io.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:80)
  while locating com.metamx.metrics.MonitorScheduler
  at io.druid.server.metrics.MetricsModule.configure(MetricsModule.java:65)
  while locating com.metamx.metrics.MonitorScheduler annotated with @com.google.inject.name.Named(value=ForTheEagerness)

3 errors
~~~

I am not a sure that I choose correct module for these dependencies. Could you please check it and add them?

Workaround:
  Add JARs to lib/ directory:

  * el-ri-1.0.jar
  * javax.el-api-3.0.0.jar

P.S.
  Druid 0.6.24
  jdk-7u45-linux-x64

**Comment by fjy** [comment]
With the inclusion of the dependencies listed above in Druid, this error should be resolved. I am closing this for now, please reopen if it is still a problem.
