### ISSUE TITLE
Cannot run program "java": error=2

### ISSUE THREAD

**Issue by AlejandroArmenteros** [druid-io/druid#3191]
Hi all,

I'm trying to do quickstart, i start all the differents nodes (without errors)
```
java `cat conf-quickstart/druid/historical/jvm.config | xargs` -cp conf-quickstart/druid/_common:conf-quickstart/druid/historical:lib/* io.druid.cli.Main server historical
java `cat conf-quickstart/druid/broker/jvm.config | xargs` -cp conf-quickstart/druid/_common:conf-quickstart/druid/broker:lib/* io.druid.cli.Main server broker
java `cat conf-quickstart/druid/coordinator/jvm.config | xargs` -cp conf-quickstart/druid/_common:conf-quickstart/druid/coordinator:lib/* io.druid.cli.Main server coordinator
java `cat conf-quickstart/druid/overlord/jvm.config | xargs` -cp conf-quickstart/druid/_common:conf-quickstart/druid/overlord:lib/* io.druid.cli.Main server overlord
java `cat conf-quickstart/druid/middleManager/jvm.config | xargs` -cp conf-quickstart/druid/_common:conf-quickstart/druid/middleManager:lib/* io.druid.cli.Main server middleManager
```

Before that, i try to load batch data.
`
 curl -X 'POST' -H 'Content-Type:application/json' -d @quickstart/wikiticker-index.json localhost:8090/druid/indexer/v1/task`

But the node with middleManager give me an error

```
2016-06-28T12:34:57,104` INFO [forking-task-runner-0] io.druid.indexing.overlord.ForkingTaskRunner - Exception caught during execution
java.io.IOException: Cannot run program "java": error=2, No existe el archivo o el directorio
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[?:1.8.0_91]
	at io.druid.indexing.overlord.ForkingTaskRunner$1.call(ForkingTaskRunner.java:365) [druid-indexing-service-0.9.0.jar:0.9.0]
	at io.druid.indexing.overlord.ForkingTaskRunner$1.call(ForkingTaskRunner.java:179) [druid-indexing-service-0.9.0.jar:0.9.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.io.IOException: error=2, No existe el archivo o el directorio
	at java.lang.UNIXProcess.forkAndExec(Native Method) ~[?:1.8.0_91]
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248) ~[?:1.8.0_91]
	at java.lang.ProcessImpl.start(ProcessImpl.java:134) ~[?:1.8.0_91]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[?:1.8.0_91]
	... 6 more
2016-06-28T12:34:57,106 INFO [forking-task-runner-0] io.druid.indexing.overlord.ForkingTaskRunner - Removing task directory: var/druid/task/index_hadoop_wikiticker_2016-06-28T12:34:56.882Z
2016-06-28T12:34:57,113 ERROR [WorkerTaskMonitor-0] io.druid.indexing.worker.WorkerTaskMonitor - I can't build there. Failed to run task: {class=io.druid.indexing.worker.WorkerTaskMonitor, exceptionType=class java.util.concurrent.ExecutionException, exceptionMessage=java.lang.RuntimeException: java.io.IOException: Cannot run program "java": error=2, No existe el archivo o el directorio, task=index_hadoop_wikiticker_2016-06-28T12:34:56.882Z}
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.io.IOException: Cannot run program "java": error=2, No existe el archivo o el directorio
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_91]
	at io.druid.indexing.worker.WorkerTaskMonitor$2.run(WorkerTaskMonitor.java:179) [druid-indexing-service-0.9.0.jar:0.9.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.RuntimeException: java.io.IOException: Cannot run program "java": error=2, No existe el archivo o el directorio
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-16.0.1.jar:?]
	at io.druid.indexing.overlord.ForkingTaskRunner$1.call(ForkingTaskRunner.java:408) ~[druid-indexing-service-0.9.0.jar:0.9.0]
	at io.druid.indexing.overlord.ForkingTaskRunner$1.call(ForkingTaskRunner.java:179) ~[druid-indexing-service-0.9.0.jar:0.9.0]
	... 4 more
Caused by: java.io.IOException: Cannot run program "java": error=2, No existe el archivo o el directorio
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[?:1.8.0_91]
	at io.druid.indexing.overlord.ForkingTaskRunner$1.call(ForkingTaskRunner.java:365) ~[druid-indexing-service-0.9.0.jar:0.9.0]
	at io.druid.indexing.overlord.ForkingTaskRunner$1.call(ForkingTaskRunner.java:179) ~[druid-indexing-service-0.9.0.jar:0.9.0]
	... 4 more
Caused by: java.io.IOException: error=2, No existe el archivo o el directorio
	at java.lang.UNIXProcess.forkAndExec(Native Method) ~[?:1.8.0_91]
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248) ~[?:1.8.0_91]
	at java.lang.ProcessImpl.start(ProcessImpl.java:134) ~[?:1.8.0_91]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[?:1.8.0_91]
	at io.druid.indexing.overlord.ForkingTaskRunner$1.call(ForkingTaskRunner.java:365) ~[druid-indexing-service-0.9.0.jar:0.9.0]
	at io.druid.indexing.overlord.ForkingTaskRunner$1.call(ForkingTaskRunner.java:179) ~[druid-indexing-service-0.9.0.jar:0.9.0]
	... 4 more
```

I try to use `druid.indexer.runner.javaCommand` with full path in the druid config, but i doesn't work.

I think the problem is that my java jdk isn't in a standard path. But it is in my $PATH, and i can do `java -version`
```
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

Thanks so much

**Comment by AlejandroArmenteros** [comment]
Ok,

I'm really stupid... I change the config in the conf folder, but i start the services in conf-quickstart.

It works when i change the config location in services.
