### ISSUE TITLE
druid s3 error@druid0.9,  druid.storage.baseKey 

### ISSUE THREAD

**Issue by wangbokun** [druid-io/druid#3208]
**druid.storage.baseKey		Base key prefix to use, i.e. what directory.	Must be set.**

what's   i.e.  ?

**Comment by fjy** [comment]
@wangbokun what verison of druid? what deep storage are you using?

**Comment by wangbokun** [comment]
druid 0.9 +  tranquility-distribution-0.8.1, &  deep storage is s3.

_common configure:
druid.storage.type=s3
#druid.storage.bucket=s3://xxxx/newdruid/
druid.storage.bucket=/xxxx/newdruid/
druid.storage.baseKey=newdruid/segments
druid.s3.accessKey=xxxxxx
druid.s3.secretKey=xxxx


the following is my error：
2016-06-29T14:43:00,618 INFO [user_feedback_hour_06291300-2016-06-29T14:30:00.000Z-persist-n-merge] io.druid.storage.s3.S3DataSegmentPusher - Pushing S3Object [key=newdruid/segments/user_feedback_hour_06291300/2016-06-29T14:30:00.000Z_2016-06-29T14:35:00.000Z/2016-06-29T14:30:31.458Z/0/index.zip, bucket=/bigdatasing/newdruid/, lastModified=null, dataInputStream=null, Metadata={x-amz-content-sha256=7cd699100ce933e7dd5363d7ed7af4a81f58f10a55b6fa4ec80b2929a2d05899, x-amz-acl=bucket-owner-full-control, md5-hash=7a6de9d0e5312cf420e71718c3c7e1bc, Content-Length=6866, Content-Type=application/zip, Content-MD5=em3p0OUxLPQg5xcYw8fhvA==}].


2016-06-29T14:43:02,126 ERROR [user_feedback_hour_06291300-2016-06-29T14:30:00.000Z-persist-n-merge] io.druid.segment.realtime.plumber.RealtimePlumber - Failed to persist merged index[user_feedback_hour_06291300]: {class=io.druid.segment.realtime.plumber.RealtimePlumber, exceptionType=class java.io.IOException, exceptionMessage=org.jets3t.service.S3ServiceException: Service Error Message. -- ResponseCode: 301, ResponseStatus: Moved Permanently, XML Error Message: <?xml version="1.0" encoding="UTF-8"?><Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Bucket>xxx</Bucket><Endpoint>xxx.s3.amazonaws.com</Endpoint><RequestId>xxxx</RequestId><HostId>xxx</HostId></Error>, interval=2016-06-29T14:30:00.000Z/2016-06-29T14:35:00.000Z}
java.io.IOException: org.jets3t.service.S3ServiceException: Service Error Message. -- ResponseCode: 301, ResponseStatus: Moved Permanently, XML Error Message: <?xml version="1.0" encoding="UTF-8"?><Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Bucket>xxx</Bucket><Endpoint>xxxx.s3.amazonaws.com</Endpoint><RequestId>xxxx</RequestId><HostId>xxx =</HostId></Error>
        at io.druid.storage.s3.S3DataSegmentPusher.push(S3DataSegmentPusher.java:138) ~[?:?]
        at io.druid.segment.realtime.plumber.RealtimePlumber$4.doRun(RealtimePlumber.java:550) [druid-server-0.9.0.jar:0.9.0]
        at io.druid.common.guava.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:42) [druid-common-0.9.0.jar:0.9.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: org.jets3t.service.S3ServiceException: Service Error Message.
        at org.jets3t.service.S3Service.putObject(S3Service.java:2214) ~[jets3t-0.9.4.jar:0.9.4]
        at io.druid.storage.s3.S3DataSegmentPusher$1.call(S3DataSegmentPusher.java:99) ~[?:?]
        at io.druid.storage.s3.S3DataSegmentPusher$1.call(S3DataSegmentPusher.java:83) ~[?:?]
        at com.metamx.common.RetryUtils.retry(RetryUtils.java:38) ~[java-util-0.27.7.jar:?]
        at io.druid.storage.s3.S3Utils.retryS3Operation(S3Utils.java:87) ~[?:?]
        at io.druid.storage.s3.S3DataSegmentPusher.push(S3DataSegmentPusher.java:81) ~[?:?]
        ... 5 more

**Comment by fjy** [comment]
Your bucket is configured incorrectly.

it should be of the form
druid.storage.bucket=myBucket
druid.storage.baseKey=newdruid/segments

**Comment by wangbokun** [comment]
Tks U very much!
 It's succeeded。

druid.storage.bucket is myBucket Name。
druid.storage.baseKey  is  path name   in the  myBucket。

**Comment by fjy** [comment]
@wangbokun cool!
