### ISSUE TITLE
`Caused by: com.metamx.common.IAE: Unknown version` on segment load

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#3233]
```
io.druid.segment.loading.SegmentLoadingException: Exception loading segment[ID_REDACTED]
        at io.druid.server.coordination.ZkCoordinator.loadSegment(ZkCoordinator.java:309) ~[druid-selfcontained-0.9.1-rc3-mmx0.jar:0.9.1-rc3-mmx0]
        at io.druid.server.coordination.ZkCoordinator.addSegment(ZkCoordinator.java:350) [druid-selfcontained-0.9.1-rc3-mmx0.jar:0.9.1-rc3-mmx0]
        at io.druid.server.coordination.SegmentChangeRequestLoad.go(SegmentChangeRequestLoad.java:44) [druid-selfcontained-0.9.1-rc3-mmx0.jar:0.9.1-rc3-mmx0]
        at io.druid.server.coordination.ZkCoordinator$1.childEvent(ZkCoordinator.java:152) [druid-selfcontained-0.9.1-rc3-mmx0.jar:0.9.1-rc3-mmx0]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:522) [druid-selfcontained-0.9.1-rc3-mmx0.jar:0.9.1-rc3-mmx0]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:516) [druid-selfcontained-0.9.1-rc3-mmx0.jar:0.9.1-rc3-mmx0]
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93) [druid-selfcontained-0.9.1-rc3-mmx0.jar:0.9.1-rc3-mmx0]
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) [druid-selfcontained-0.9.1-rc3-mmx0.jar:0.9.1-rc3-mmx0]
        at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85) [druid-selfcontained-0.9.1-rc3-mmx0.jar:0.9.1-rc3-mmx0]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache.callListeners(PathChildrenCache.java:514) [druid-selfcontained-0.9.1-rc3-mmx0.jar:0.9.1-rc3-mmx0]
        at org.apache.curator.framework.recipes.cache.EventOperation.invoke(EventOperation.java:35) [druid-selfcontained-0.9.1-rc3-mmx0.jar:0.9.1-rc3-mmx0]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$9.run(PathChildrenCache.java:772) [druid-selfcontained-0.9.1-rc3-mmx0.jar:0.9.1-rc3-mmx0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: com.metamx.common.IAE: Unknown version[68]
        at io.druid.segment.data.GenericIndexed.read(GenericIndexed.java:323) ~[druid-selfcontained-0.9.1-rc3-mmx0.jar:0.9.1-rc3-mmx0]
        at io.druid.segment.IndexIO$V9IndexLoader.load(IndexIO.java:1028) ~[druid-selfcontained-0.9.1-rc3-mmx0.jar:0.9.1-rc3-mmx0]
        at io.druid.segment.IndexIO.loadIndex(IndexIO.java:216) ~[druid-selfcontained-0.9.1-rc3-mmx0.jar:0.9.1-rc3-mmx0]
        at io.druid.segment.loading.MMappedQueryableIndexFactory.factorize(MMappedQueryableIndexFactory.java:49) ~[druid-selfcontained-0.9.1-rc3-mmx0.jar:0.9.1-rc3-mmx0]
        at io.druid.segment.loading.SegmentLoaderLocalCacheManager.getSegment(SegmentLoaderLocalCacheManager.java:96) ~[druid-selfcontained-0.9.1-rc3-mmx0.jar:0.9.1-rc3-mmx0]
        at io.druid.server.coordination.ServerManager.loadSegment(ServerManager.java:152) ~[druid-selfcontained-0.9.1-rc3-mmx0.jar:0.9.1-rc3-mmx0]
        at io.druid.server.coordination.ZkCoordinator.loadSegment(ZkCoordinator.java:305) ~[druid-selfcontained-0.9.1-rc3-mmx0.jar:0.9.1-rc3-mmx0]
        ... 18 more
```

Using a regex of `.*com\.metamx\.common\.IAE: Unknown version\[(?<version>[0-9]*)\].*` to extract the version, we can see that the errors began occurring on the 5th of July and only show a "wrong" version of 68 or 0.

<img width="1418" alt="screen shot 2016-07-11 at 2 18 32 pm" src="https://cloud.githubusercontent.com/assets/8213081/16747123/6e2fa32c-4772-11e6-8b85-e1bcfbd3190c.png">

I have not tagged this to a particular version because I haven't been able to discern the root cause yet. This ticket is out there to see if others are encountering this as well.

This *seems* to be coming from realtime indexing tasks, but unclear what is causing the file corruption.

**Comment by drcrallen** [comment]
0.9.1 was rolled out about Jun23, many weeks before this error was encountered. I do not think it is a regression.

**Comment by gianm** [comment]
Is this always from the same segment or is it from different segments? I wonder if one particular segment was corrupted before being uploaded, and now can't be loaded.

**Comment by drcrallen** [comment]
@gianm investigating still

**Comment by drcrallen** [comment]
There's actually 3 segments, the first of which appeared on 2016-07-05. It is unclear why these became corrupted, or why we've seen more of the corruption recently. Checking to see if they come from the same hardware.

**Comment by drcrallen** [comment]
Got another one today:

```
Pushing S3Object [key=REDACTED_KEY, bucket=REDACTED_BUCKET, lastModified=null, dataInputStream=null, Metadata={x-amz-content-sha256=09131b0eba0c0c46c98910e0f7d72284179b957deafe2f4177af22a4e74d0373, x-amz-acl=bucket-owner-full-control, md5-hash=eb3be751fe2c1b2e16f6cb6fde4d4aaa, Content-Length=62940878, Content-Type=application/zip, Content-MD5=6zvnUf4sGy4W9stv3k1Kqg==}].
```

I grabbed the object off s3 and verified the md5 and sha256 both match.

**Comment by drcrallen** [comment]
I *think* I tracked this down to a single node which started up on July 4th. Will close out in a couple days if no more issues.

**Comment by drcrallen** [comment]
Haven't seen any more since I closed down the bad node. Closing out this issue for now.
