### ISSUE TITLE
CSV empty cells should be empty strings

### ISSUE THREAD

**Issue by sandwwraith** [druid-io/druid#3390]
I have csv file with following line:
`1987,4,10,19,1,1987-10-19,CO,19704,CO,,597,10821,1082102,30852,BWI,"Baltimore, MD",MD,24,Maryland,35,12266,1226601,31453,IAH,"Houston, TX",TX,48,Texas,74,1650,1649,-1,0,0,-1,1600-1659,,,,,1850,1858,8,8,0,0,1800-1859,0,,0,180,189,,1,1235,5`
This line has empty values for some columns, as you can see. Such values usually treated as empty strings. However, Druid parses them as null values (although they are dimensions), which causes this error, when I try to index my data:
```
22/Aug/2016 17:24:43,649 ERROR [task-runner-0-priority-0] io.druid.indexing.overlord.ThreadPoolTaskRunner - Exception while running task[HadoopIndexTask{id=index_hadoop_ontime_2016-08-22T17:24:38.324Z, type=index_hadoop, dataSource=ontime}]
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-16.0.1.jar:?]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:160) ~[druid-indexing-service-0.9.0.jar:0.9.0]
	at io.druid.indexing.common.task.HadoopIndexTask.run(HadoopIndexTask.java:175) ~[druid-indexing-service-0.9.0.jar:0.9.0]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:338) [druid-indexing-service-0.9.0.jar:0.9.0]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:318) [druid-indexing-service-0.9.0.jar:0.9.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:157) ~[druid-indexing-service-0.9.0.jar:0.9.0]
	... 7 more
Caused by: java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
	at com.google.common.base.Absent.get(Absent.java:47) ~[guava-16.0.1.jar:?]
	at io.druid.indexer.HadoopDruidDetermineConfigurationJob.run(HadoopDruidDetermineConfigurationJob.java:63) ~[druid-indexing-hadoop-0.9.0.jar:0.9.0]
	at io.druid.indexing.common.task.HadoopIndexTask$HadoopDetermineConfigInnerProcessing.runTask(HadoopIndexTask.java:291) ~[druid-indexing-service-0.9.0.jar:0.9.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:157) ~[druid-indexing-service-0.9.0.jar:0.9.0]
	... 7 more
```

**Comment by sandwwraith** [comment]
Sorry, it was my fail with configuration. That stacktraces are not very informative

**Comment by chowey** [comment]
What was your problem with configuration? I am getting the same stacktraces.

**Comment by sandwwraith** [comment]
@chowey Sorry, I barely remember it. Something with dimensions and metrics config, I think.

**Comment by chowey** [comment]
No worries. It turned out I was missing my `"intervals"` in my `"granularitySpec"`.

**Comment by sdenham** [comment]
Thank you @chowey!
