### ISSUE TITLE
Kill tasks require hadoop to run even when hdfs storage is not used

### ISSUE THREAD

**Issue by erikdubbelboer** [druid-io/druid#3427]
We are using Google Cloud Storage support from https://github.com/druid-io/druid/pull/2458 and only start our hadoop cluster when running index tasks.

In theory a `kill` task shouldn't require hdfs as it can directly access everything. All other operations like realtime indexing, loading segments and logs work fine without the hadoop cluster.

But for some reason the `kill` task still tries to load the hdfs client (see stack trace below).

If anyone could point me to where and why this is happening I can make and test a fix myself.

```
Sep 06, 2016 6:03:31 AM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: java.net.UnknownHostException: hadoop-eu-1-m
java.lang.IllegalArgumentException: java.net.UnknownHostException: hadoop-eu-1-m
	at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:377)
	at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:237)
	at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:141)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:569)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:512)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:142)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2316)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:90)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2350)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2332)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:369)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:168)
	at io.druid.storage.hdfs.HdfsStorageDruidModule.configure(HdfsStorageDruidModule.java:106)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:230)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.spi.Elements.getElements(Elements.java:94)
	at com.google.inject.util.Modules$RealOverriddenModuleBuilder$1.configure(Modules.java:173)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:230)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:136)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at io.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:367)
	at io.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:60)
	at io.druid.cli.CliPeon.run(CliPeon.java:272)
	at io.druid.cli.Main.main(Main.java:105)
```

**Comment by erikdubbelboer** [comment]
We had `extensions/druid-hdfs-storage/*` in our classpath which made druid try to initialize the hdfs extension (even though it's not in the extensions-list). Removing this fixed the issue.

See also: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/druid-development/-vULOHhL5cI/hvPTou4sAQAJ
