### ISSUE TITLE
java.lang.NoSuchMethodError: com.metamx.common.CompressionUtils.unzip

### ISSUE THREAD

**Issue by maver1ck** [druid-io/druid#3478]
I successfully indexed table using hadoop indexer and yarn.
(compiled druid with hadoop 2.6.0 and shade guava)
Historical node is configured as in quickstart (+ hdfs plugin)
Started by:
```
java `cat conf-quickstart/druid/historical/jvm.config | xargs` -cp "conf-quickstart/druid/_common:conf-quickstart/druid/historical:lib/*" io.druid.cli.Main server historical
```
After querying data I'm getting:
```
2016-09-21T16:02:22,726 ERROR [ZkCoordinator-0] org.apache.curator.framework.listen.ListenerContainer - Listener (io.druid.server.coordination.ZkCoordinator$1@322204dc) threw an exception
java.lang.NoSuchMethodError: com.metamx.common.CompressionUtils.unzip(Lcom/google/common/io/ByteSource;Ljava/io/File;Lcom/google/common/base/Predicate;Z)Lcom/metamx/common/FileUtils$FileCopyResult;
        at io.druid.storage.hdfs.HdfsDataSegmentPuller.getSegmentFiles(HdfsDataSegmentPuller.java:235) ~[?:?]
        at io.druid.storage.hdfs.HdfsLoadSpec.loadSegment(HdfsLoadSpec.java:62) ~[?:?]
        at io.druid.segment.loading.SegmentLoaderLocalCacheManager.getSegmentFiles(SegmentLoaderLocalCacheManager.java:143) ~[druid-services-0.9.1.1-selfcontained.jar:0.9.1.1]
        at io.druid.segment.loading.SegmentLoaderLocalCacheManager.getSegment(SegmentLoaderLocalCacheManager.java:95) ~[druid-services-0.9.1.1-selfcontained.jar:0.9.1.1]
        at io.druid.server.coordination.ServerManager.loadSegment(ServerManager.java:152) ~[druid-services-0.9.1.1-selfcontained.jar:0.9.1.1]
        at io.druid.server.coordination.ZkCoordinator.loadSegment(ZkCoordinator.java:305) ~[druid-services-0.9.1.1-selfcontained.jar:0.9.1.1]
        at io.druid.server.coordination.ZkCoordinator.addSegment(ZkCoordinator.java:350) ~[druid-services-0.9.1.1-selfcontained.jar:0.9.1.1]
        at io.druid.server.coordination.SegmentChangeRequestLoad.go(SegmentChangeRequestLoad.java:44) ~[druid-services-0.9.1.1-selfcontained.jar:0.9.1.1]
        at io.druid.server.coordination.ZkCoordinator$1.childEvent(ZkCoordinator.java:152) ~[druid-services-0.9.1.1-selfcontained.jar:0.9.1.1]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:522) ~[druid-services-0.9.1.1-selfcontained.jar:0.9.1.1]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:516) ~[druid-services-0.9.1.1-selfcontained.jar:0.9.1.1]
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93) [druid-services-0.9.1.1-selfcontained.jar:0.9.1.1]
        at shade.com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) [druid-services-0.9.1.1-selfcontained.jar:0.9.1.1]
        at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85) [druid-services-0.9.1.1-selfcontained.jar:0.9.1.1]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache.callListeners(PathChildrenCache.java:514) [druid-services-0.9.1.1-selfcontained.jar:0.9.1.1]
        at org.apache.curator.framework.recipes.cache.EventOperation.invoke(EventOperation.java:35) [druid-services-0.9.1.1-selfcontained.jar:0.9.1.1]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$9.run(PathChildrenCache.java:772) [druid-services-0.9.1.1-selfcontained.jar:0.9.1.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
```
What process missed some jars on the classpath ?

**Comment by maver1ck** [comment]
Closing.
The problem was because of shading Guava.
I don't know how to solve it with hadoop 2.6.0 but hadoop-client 2.7.1 works fine with 2.6.0 cluster and can be compiled with guava 16.
