### ISSUE TITLE
Druid quickstart bug -  Exception: Insufficient threads

### ISSUE THREAD

**Issue by maver1ck** [druid-io/druid#3491]
Exception is thrown on many processes when following quickstart.

PR created
```
java.lang.IllegalStateException: Insufficient threads: max=8 < needed(acceptors=4 + selectors=4 + request=1)
        at org.eclipse.jetty.server.Server.doStart(Server.java:350) ~[org.eclipse.jetty.jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[org.eclipse.jetty.jetty-util-9.2.5.v20141112.jar:9.2.5.v20141112]
        at com.metamx.tranquility.server.http.ServerMain$$anonfun$createJettyServer$1$$anonfun$apply$1.apply$mcV$sp(ServerMain.scala:153) [io.druid.tranquility-server-0.8.2.jar:0.8.2]
        at com.metamx.tranquility.server.http.ServerMain$$anonfun$createJettyServer$1$$anonfun$apply$1.apply(ServerMain.scala:153) [io.druid.tranquility-server-0.8.2.jar:0.8.2]
        at com.metamx.tranquility.server.http.ServerMain$$anonfun$createJettyServer$1$$anonfun$apply$1.apply(ServerMain.scala:153) [io.druid.tranquility-server-0.8.2.jar:0.8.2]
        at com.metamx.common.scala.lifecycle$LifecycleOps$$anon$1.start(lifecycle.scala:31) [com.metamx.scala-util_2.11-1.11.6.jar:1.11.6]
        at com.metamx.common.lifecycle.Lifecycle.start(Lifecycle.java:259) [com.metamx.java-util-0.27.9.jar:na]
        at com.metamx.tranquility.server.http.ServerMain$.main(ServerMain.scala:81) [io.druid.tranquility-server-0.8.2.jar:0.8.2]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
        at com.twitter.app.App$$anonfun$nonExitingMain$3.apply(App.scala:168) [com.twitter.util-app_2.11-6.30.0.jar:6.30.0]
        at com.twitter.app.App$$anonfun$nonExitingMain$3.apply(App.scala:167) [com.twitter.util-app_2.11-6.30.0.jar:6.30.0]
        at scala.Option.foreach(Option.scala:257) [org.scala-lang.scala-library-2.11.7.jar:na]
        at com.twitter.app.App$class.nonExitingMain(App.scala:167) [com.twitter.util-app_2.11-6.30.0.jar:6.30.0]
        at com.metamx.tranquility.server.http.ServerMain$.nonExitingMain(ServerMain.scala:49) [io.druid.tranquility-server-0.8.2.jar:0.8.2]
        at com.twitter.app.App$class.main(App.scala:133) [com.twitter.util-app_2.11-6.30.0.jar:6.30.0]
        at com.metamx.tranquility.server.http.ServerMain$.main(ServerMain.scala:49) [io.druid.tranquility-server-0.8.2.jar:0.8.2]
        at com.metamx.tranquility.distribution.DistributionMain$.main(DistributionMain.scala:34) [io.druid.tranquility-distribution-0.8.2.jar:0.8.2]
        at com.metamx.tranquility.distribution.DistributionMain.main(DistributionMain.scala) [io.druid.tranquility-distribution-0.8.2.jar:0.8.2]
```

**Comment by dclim** [comment]
Fixed in #3492
