### ISSUE TITLE
Guava 14.x batch indexing fails

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#3519]
```
16/09/27 22:20:37 ERROR SparkDruidIndexer$: Error in partition [1]
java.lang.NoSuchMethodError: com.google.common.io.ByteSource.concat(Ljava/lang/Iterable;)Lcom/google/common/io/ByteSource;
	at io.druid.segment.data.GenericIndexedWriter.combineStreams(GenericIndexedWriter.java:139)
	at io.druid.segment.StringDimensionMergerLegacy.writeValueMetadataToFile(StringDimensionMergerLegacy.java:206)
	at io.druid.segment.IndexMerger.makeIndexFiles(IndexMerger.java:696)
	at io.druid.segment.IndexMerger.merge(IndexMerger.java:438)
	at io.druid.segment.IndexMerger.persist(IndexMerger.java:186)
	at io.druid.segment.IndexMerger.persist(IndexMerger.java:152)
	at io.druid.indexer.spark.SparkDruidIndexer$$anonfun$13$$anonfun$21.apply(SparkDruidIndexer.scala:293)
	at io.druid.indexer.spark.SparkDruidIndexer$$anonfun$13$$anonfun$21.apply(SparkDruidIndexer.scala:288)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:183)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:294)
	at scala.collection.AbstractIterator.toList(Iterator.scala:1336)
	at io.druid.indexer.spark.SparkDruidIndexer$$anonfun$13.apply(SparkDruidIndexer.scala:309)
	at io.druid.indexer.spark.SparkDruidIndexer$$anonfun$13.apply(SparkDruidIndexer.scala:205)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$25.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$25.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:85)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Fails from the change in https://github.com/druid-io/druid/pull/3148 which moved the prior usage of `ByteStreams.join` (in guava forever, deprecated for removal in 18) to `ByteSource concat` introduced in guava 15

**Comment by fjy** [comment]
Fixed by https://github.com/druid-io/druid/pull/3520
