### ISSUE TITLE
No batch reimport with HDFS deep storage

### ISSUE THREAD

**Issue by sixtus** [druid-io/druid#352]
I am seeing some really weird error, not sure what it is. But seems to only be triggered when I reindex an existing segment with HDFS as deep storage:

ERROR [main] io.druid.cli.CliHadoopIndexer - failure!!!!
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at io.druid.cli.CliHadoopIndexer.run(CliHadoopIndexer.java:104)
at io.druid.cli.Main.main(Main.java:91)
Caused by: java.lang.NullPointerException
at io.druid.indexer.IndexGeneratorJob.getPublishedSegments(IndexGeneratorJob.java:178)
at io.druid.indexer.DbUpdaterJob.run(DbUpdaterJob.java:58)
at io.druid.indexer.HadoopDruidIndexerJob.run(HadoopDruidIndexerJob.java:102)
at io.druid.cli.CliInternalHadoopIndexer.run(CliInternalHadoopIndexer.java:50)
at io.druid.cli.Main.main(Main.java:91)
... 6 more

**Comment by xvrl** [comment]
I believe this has been fixed by https://github.com/druid-io/druid/pull/1121. Please re-open if this is still a problem
