### ISSUE TITLE
Kafka indexing fails to stop correctly in 0.9.2rc1

### ISSUE THREAD

**Issue by gvsmirnov** [druid-io/druid#3531]
**Steps to reproduce:**

1. Create a [kafka indexer](http://druid.io/docs/0.9.1.1/development/extensions-core/kafka-ingestion.html)
2. Wait for a kafka index task to start
3. Emulate a `/stop` request sent from supervisor to worker, e.g. via
```
http post localhost:8100/druid/worker/v1/chat/index_kafka_Example_0f2f4bbb5f488f3_mjmpbfek/stop
```

**Expected behavior:**
Worker successfully stops

**Actual behavior:**
Worker process remains lingering until middle manager forcefully kills the process after timeout. The following exception is seen in the logs:

```
2016-10-04T13:16:56,181 ERROR [task-runner-0-priority-0] io.druid.indexing.overlord.ThreadPoolTaskRunner - Exception while running task[KafkaIndexTask{id=index_kafka_Example_0f2f4bbb5f488f3_mjmpbfek, type=index_kafka, dataSource=Example}]
java.util.concurrent.RejectedExecutionException: Got Interrupted while adding to the Queue
	at io.druid.concurrent.Execs$1.rejectedExecution(Execs.java:123) ~[druid-common-0.9.2-rc1.jar:0.9.2-rc1]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) ~[?:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369) ~[?:1.8.0_102]
	at com.google.common.util.concurrent.MoreExecutors$ListeningDecorator.execute(MoreExecutors.java:484) ~[guava-16.0.1.jar:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) ~[?:1.8.0_102]
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:58) ~[guava-16.0.1.jar:?]
	at io.druid.segment.realtime.appenderator.AppenderatorImpl.persistAll(AppenderatorImpl.java:377) ~[druid-server-0.9.2-rc1.jar:0.9.2-rc1]
	at io.druid.segment.realtime.appenderator.AppenderatorImpl.add(AppenderatorImpl.java:218) ~[druid-server-0.9.2-rc1.jar:0.9.2-rc1]
	at io.druid.segment.realtime.appenderator.FiniteAppenderatorDriver.add(FiniteAppenderatorDriver.java:199) ~[druid-server-0.9.2-rc1.jar:0.9.2-rc1]
	at io.druid.indexing.kafka.KafkaIndexTask.run(KafkaIndexTask.java:416) ~[?:?]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:436) [druid-indexing-service-0.9.2-rc1.jar:0.9.2-rc1]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:408) [druid-indexing-service-0.9.2-rc1.jar:0.9.2-rc1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
2016-10-04T13:16:56,284 INFO [task-runner-0-priority-0] io.druid.indexing.overlord.TaskRunnerUtils - Task [index_kafka_Example_0f2f4bbb5f488f3_mjmpbfek] status changed to [FAILED].
2016-10-04T13:16:56,293 INFO [task-runner-0-priority-0] io.druid.indexing.worker.executor.ExecutorLifecycle - Task completed with status: {
  "id" : "index_kafka_Example_0f2f4bbb5f488f3_mjmpbfek",
  "status" : "FAILED",
  "duration" : 1811725
}
```

---

This does not happen every time, but in about 70% of the cases so far. This issue is quite similar to https://github.com/druid-io/druid/issues/3346, except that this time the lookups do not have anything to do with it.

As I understand, `KafkaIndexTask` attempts to persist everything to `FiniteAppenderatorDriver`, but since the peon is being shut down, submitting a task in `AppenderatorImpl.persistAll` gets rejected.

I do not yet see what change could have caused it, but we do not observe the issue in 0.9.1.1. Any ideas? This would be a show-stopper for upgrading to 0.9.2 for anyone using kafka ingestion.

**Comment by dclim** [comment]
@gvsmirnov thanks for the report, I'll look into this

**Comment by dclim** [comment]
Some notes on this:
  - As far as I can tell, this isn't a regression introduced in 0.9.2 and this was always the behavior when calling /stop (hard interrupt the thread which would cause any future persists to fail)
  - The Kafka supervisor doesn't use the /stop endpoint except for shutting down unwanted tasks (either the ingestion schema changed or another replica completed before us) so the MM killing the task probably is not a showstopper. The normal "stop and publish" behavior uses the /offsets/end endpoint to cause the task to "reach the end of its offset assignments" and begin to publish, and that endpoint doesn't do any thread interruption.

I submitted a PR to clean up the /stop endpoint behavior which can definitely be improved.

**Comment by gvsmirnov** [comment]
@dclim Thanks for looking into this! Actually, we originally discovered this issue without manually invoking `/stop`, just by running the usual workload on rc1. I started calling it manually to get an easily reproducible test case. Did I understand correctly that this should *not* happen under normal conditions? If so, then it means that another issue is masked by this one. I'll try and see if I can make a test case that fails without invoking `/stop`, too.

**Comment by gvsmirnov** [comment]
Aha, got it. We occasionally re-submit kafka ingestion supervisor specs to the overlord. At this point, the tasks are [supposed to](http://druid.io/docs/0.9.1.1/development/extensions-core/kafka-ingestion.html#schema-configuration-changes) gracefully shut down and publish what they have.

However, this does not succeed in 0.9.2rc1, apparently because of this:

```
2016-10-05T13:54:10,384 INFO [main] io.druid.query.lookup.LookupReferencesManager - Stopping lookup factory references manager
2016-10-05T13:54:10,384 DEBUG [main-SendThread(localhost:2181)] org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x15794dc744c0013, packet:: clientPath:/druid/listeners/lookups/__default serverPath:/druid/listeners/lookups/__default finished:false header:: 63,12  replyHeader:: 63,639,0  request:: '/druid/listeners/lookups/__default,T  response::v{'192.168.10.196:8083,'192.168.10.196:8082},s{53,53,1475671310702,1475671310702,0,8,0,0,14,2,639} 
2016-10-05T13:54:10,388 DEBUG [main] io.druid.query.lookup.KafkaLookupExtractorFactory - Topic [exampleLookup] cancelled
2016-10-05T13:54:10,390 DEBUG [main] io.druid.server.lookup.namespace.cache.NamespaceExtractionCacheManager - Did not delete namespace [kafka-factory-exampleLookupbe1f0543-6e54-4f78-9552-a7f407956f11]
2016-10-05T13:54:10,390 ERROR [main] io.druid.query.lookup.KafkaLookupExtractorFactory - Error removing [kafka-factory-exampleLookupbe1f0543-6e54-4f78-9552-a7f407956f11] for topic [exampleLookup] from cache
```

The kafka lookups fail to stop because of this, and the peon process stays alive. It cascades from there, and eventually results in the behavior described originally.

So, it boils down to this:

```
2016-10-05T13:54:10,390 DEBUG [main] io.druid.server.lookup.namespace.cache.NamespaceExtractionCacheManager - Did not delete namespace [kafka-factory-exampleLookupbe1f0543-6e54-4f78-9552-a7f407956f11]
2016-10-05T13:54:10,390 ERROR [main] io.druid.query.lookup.KafkaLookupExtractorFactory - Error removing [kafka-factory-exampleLookupbe1f0543-6e54-4f78-9552-a7f407956f11] for topic [exampleLookup] from cache
```

We do not observe this error in 0.9.1.1. I am currently trying to see if I can figure out why the namespace removal fails, but no fruit yet.

**Comment by gvsmirnov** [comment]
A bit more info: at the beginning of `NamespaceExtractionCacheManager.delete()`, `implData` is empty, so the deletion fails. Since I added logging to all the places (actually, the only place) where something is removed from there, it seems likely that nothing is being put there.

**Comment by dclim** [comment]
@gvsmirnov ah interesting, I've never tried running a kafkaindextask with kafka lookup; I'll give it a try and see if I can reproduce what you're seeing

**Comment by gvsmirnov** [comment]
@dclim  Just to clarify, how I get it to reproduce from a clean state (clean druid 0.9.2-rc1, clean zookeeper, clean kafka):

1. Start zk, kafka, druid
2. Submit a kafka ingestion spec and a kafka lookup
3. Make sure that something is put into relevant kafka topics, and that the tasks are started
4. Re-submit a kafka ingestion spec with the same name (can even submit the same one)
5. Kaboom!

**Comment by dclim** [comment]
hey @gvsmirnov I was able to repro it and put in a patch that should fix the issue (#3539). The `implData` stuff turned out to be a red herring - there's something not right about the cleanup code there (the kafka lookups don't seem to use the scheduled cache update mechanism that NamespaceExtractionCacheManager.delete() expected it to use) but the real issue is that the Kafka consumer isn't closed properly and has non-daemon threads that keep the process alive.

**Comment by gvsmirnov** [comment]
@dclim The patched version works correctly in our tests. Thank you!

**Comment by dclim** [comment]
@gvsmirnov awesome, thanks for reporting and your help debugging
