### ISSUE TITLE
kafka-indexing  fails NullPointerException

### ISSUE THREAD

**Issue by tigran-a** [druid-io/druid#3546]
Hi, 

We're getting this exception while ingesting from kafka: 

```
2016-10-06T12:17:32,753 INFO [appenderator_persist_0] io.druid.segment.realtime.appenderator.AppenderatorImpl - Removing sink for segment[redirects-ro_2016-10-06T12:00:00.000Z_2016-10-06T13:00:00.000Z_2016-10-06T12:05:37.719Z_5].
2016-10-06T12:17:32,755 ERROR [task-runner-0-priority-0] io.druid.indexing.overlord.ThreadPoolTaskRunner - Exception while running task[KafkaIndexTask{id=index_kafka_redirects-ro_f9471446a216753_dejliclm, type=index_kafka, dataSource=redirects-ro}]
java.lang.NullPointerException
    at java.nio.ByteBuffer.wrap(ByteBuffer.java:396) ~[?:1.8.0_101]
    at io.druid.indexing.kafka.KafkaIndexTask.run(KafkaIndexTask.java:412) ~[?:?]
    at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:436) [druid-indexing-service-0.9.1.1.jar:0.9.1.1]
    at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:408) [druid-indexing-service-0.9.1.1.jar:0.9.1.1]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
2016-10-06T12:17:32,762 INFO [task-runner-0-priority-0] io.druid.indexing.overlord.TaskRunnerUtils - Task [index_kafka_redirects-ro_f9471446a216753_dejliclm] status changed to [FAILED].
2016-10-06T12:17:32,765 INFO [task-runner-0-priority-0] io.druid.indexing.worker.executor.ExecutorLifecycle - Task completed with status: {
  "id" : "index_kafka_redirects-ro_f9471446a216753_dejliclm",
  "status" : "FAILED",
  "duration" : 3424 
}
2016-10-06T12:17:32,768 INFO [main] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void io.druid.server.coordination.AbstractDataSegmentAnnouncer.stop()] on object[io.druid.server.coordination.BatchDataSegmentAnnouncer@1da1380b].
2016-10-06T12:17:32,768 INFO [main] io.druid.server.coordination.AbstractDataSegmentAnnouncer - Stopping class io.druid.server.coordination.BatchDataSegmentAnnouncer with config[io.druid.server.initialization.ZkPathsConfig@fc7661f4]
```

Any light on this? (or possible causes) ? 

Is it related to this commit: https://github.com/druid-io/druid/pull/3453/files  (meaning need to upgrade to rc2)

Thanks!

**Comment by dclim** [comment]
@tigran-a it looks like the same issue to me; are you able to try 0.9.2-rc1 to see if it's fixed there? http://druid.io/downloads.html

**Comment by tigran-a** [comment]
Yes, it seems solving the issue. Thanks
