### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#3568]
```
2016-10-14T04:01:36,159 WARN [qtp182926464-112-acceptor-1@b0595dd-ServerConnector@5bde57ab{HTTP/1.1}{0.0.0.0:23271}] org.eclipse.jetty.server.ServerConnector - 
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[?:1.8.0_101]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422) ~[?:1.8.0_101]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250) ~[?:1.8.0_101]
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:377) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:500) [jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620) [jetty-util-9.2.5.v20141112.jar:9.2.5.v20141112]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540) [jetty-util-9.2.5.v20141112.jar:9.2.5.v20141112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

I'm getting too many open files on brokers with 0.9.2 a few seconds after queries start to arrive.

**Comment by drcrallen** [comment]
0.9.1.1:

```
$ lsof -p $PID | wc -l
401
```


0.9.2:

```
$ lsof -p $PID | wc -l
7038
```

**Comment by drcrallen** [comment]
0.9.2 seems to try and establish `druid.broker.http.numConnections` immediately rather than using it as a limit.

**Comment by drcrallen** [comment]
nevermind, looks like the difference was "recently restarted" vs "restarted previously"

0.9.1.1 recently restarted
```
$ lsof -p $PID | wc -l
13152
```

**Comment by drcrallen** [comment]
Ok, I think this is a problem with my new deployment stuff

**Comment by drcrallen** [comment]
If anyone's interested, for mesos I had to set `ULIMIT` in `/etc/default/mesos-slave`

**Comment by BobbySun** [comment]
Is the problem sloved?
