### ISSUE TITLE
middlemanager throws an exception and exits

### ISSUE THREAD

**Issue by loganto** [druid-io/druid#3607]
Im trying to launch a docker-based druid setup.
Middlemanager throws this exception and exits.
Srry im new to Java and - is there a settings solution for this?

```
middlemanager_1  | 2016-10-25T16:59:24,024 WARN [main] org.eclipse.jetty.util.component.AbstractLifeCycle - FAILED org.eclipse.jetty.server.Server@5d01ea21: java.lang.IllegalStateException: Insufficient threads: max=5 < needed(acceptors=1 + selectors=4 + request=1)
middlemanager_1  | java.lang.IllegalStateException: Insufficient threads: max=5 < needed(acceptors=1 + selectors=4 + request=1)
middlemanager_1  | 	at org.eclipse.jetty.server.Server.doStart(Server.java:350) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
middlemanager_1  | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.5.v20141112.jar:9.2.5.v20141112]
middlemanager_1  | 	at io.druid.server.initialization.jetty.JettyServerModule$1.start(JettyServerModule.java:204) [druid-server-0.9.1.1.jar:0.9.1.1]
middlemanager_1  | 	at com.metamx.common.lifecycle.Lifecycle.start(Lifecycle.java:259) [java-util-0.27.9.jar:?]
middlemanager_1  | 	at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:155) [druid-api-0.9.1.1.jar:0.9.1.1]
middlemanager_1  | 	at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:91) [druid-services-0.9.1.1.jar:0.9.1.1]
middlemanager_1  | 	at io.druid.cli.ServerRunnable.run(ServerRunnable.java:40) [druid-services-0.9.1.1.jar:0.9.1.1]
middlemanager_1  | 	at io.druid.cli.Main.main(Main.java:105) [druid-services-0.9.1.1.jar:0.9.1.1]
middlemanager_1  | 2016-10-25T16:59:24,034 ERROR [main] io.druid.cli.CliMiddleManager - Error when starting up.  Failing.
middlemanager_1  | java.lang.IllegalStateException: Insufficient threads: max=5 < needed(acceptors=1 + selectors=4 + request=1)
middlemanager_1  | 	at org.eclipse.jetty.server.Server.doStart(Server.java:350) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
middlemanager_1  | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.2.5.v20141112.jar:9.2.5.v20141112]
middlemanager_1  | 	at io.druid.server.initialization.jetty.JettyServerModule$1.start(JettyServerModule.java:204) ~[druid-server-0.9.1.1.jar:0.9.1.1]
middlemanager_1  | 	at com.metamx.common.lifecycle.Lifecycle.start(Lifecycle.java:259) ~[java-util-0.27.9.jar:?]
middlemanager_1  | 	at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:155) ~[druid-api-0.9.1.1.jar:0.9.1.1]
middlemanager_1  | 	at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:91) [druid-services-0.9.1.1.jar:0.9.1.1]
middlemanager_1  | 	at io.druid.cli.ServerRunnable.run(ServerRunnable.java:40) [druid-services-0.9.1.1.jar:0.9.1.1]
middlemanager_1  | 	at io.druid.cli.Main.main(Main.java:105) [druid-services-0.9.1.1.jar:0.9.1.1]
middlemanager_1  | Heap
middlemanager_1  |  par new generation   total 230400K, used 115519K [0x00000000c0000000, 0x00000000cfa00000, 0x00000000cfa00000)
middlemanager_1  |   eden space 204800K,  48% used [0x00000000c0000000, 0x00000000c60d0180, 0x00000000cc800000)
middlemanager_1  |   from space 25600K,  63% used [0x00000000ce100000, 0x00000000cf0ffc28, 0x00000000cfa00000)
middlemanager_1  |   to   space 25600K,   0% used [0x00000000cc800000, 0x00000000cc800000, 0x00000000ce100000)
middlemanager_1  |  concurrent mark-sweep generation total 6144K, used 0K [0x00000000cfa00000, 0x00000000d0000000, 0x0000000100000000)
middlemanager_1  |  Metaspace       used 28324K, capacity 28703K, committed 28856K, reserved 1075200K
middlemanager_1  |   class space    used 3651K, capacity 3763K, committed 3780K, reserved 1048576K
```

**Comment by loganto** [comment]
thx. already fixed that one.
