### ISSUE TITLE
Druid builds do not run properly on Java 7

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#3795]
Druid builds need to be done with JDK8 compilers, because one of the extensions (druid-caffeine-cache) targets JDK8. But the other modules are supposed to target JDK7 and so we pass `-source 1.7 -target 1.7` to javac. But, this is not enough to properly target JDK7, due to method signature changes the Java API. One example is that `ConcurrentHashMap.keySet`'s return type changed from `Set` to `KeySetView`, leading to errors like the one below when Druid is run on JDK7.

We use this method in 4 places:

- io.druid.indexing.overlord.supervisor.SupervisorManager
- io.druid.indexing.kafka.supervisor.KafkaSupervisor
- io.druid.firehose.rocketmq.RocketMQFirehoseFactory
- io.druid.server.router.CoordinatorRuleManager

Presumably if one avoids the features corresponding to these classes (supervised ingestion, rocketmq extension, and the router; none of them are required) then things should work fine on JDK7. But still, this is not what we intended. Possible fixes:

- Cast ConcurrentHashMap to Map before calling keySet
- Pass the JDK7 runtime to bootclasspath when compiling with javac

If #3746 is agreed on then this issue becomes moot. See also https://bugs.openjdk.java.net/browse/JDK-8151366 for more details.

```
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_121]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_121]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_121]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_121]
    at com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler.stop(Lifecycle.java:362) [java-util-0.27.10.jar:?]
    at com.metamx.common.lifecycle.Lifecycle.stop(Lifecycle.java:280) [java-util-0.27.10.jar:?]
    at io.druid.indexing.overlord.TaskMaster.stopLeading(TaskMaster.java:227) [druid-indexing-service-0.9.2.jar:0.9.2]
    at io.druid.indexing.overlord.TaskMaster.stop(TaskMaster.java:207) [druid-indexing-service-0.9.2.jar:0.9.2]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_121]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_121]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_121]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_121]
    at com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler.stop(Lifecycle.java:362) [java-util-0.27.10.jar:?]
    at com.metamx.common.lifecycle.Lifecycle.stop(Lifecycle.java:280) [java-util-0.27.10.jar:?]
    at com.metamx.common.lifecycle.Lifecycle$1.run(Lifecycle.java:306) [java-util-0.27.10.jar:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_121]
Caused by: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
    at io.druid.indexing.overlord.supervisor.SupervisorManager.stop(SupervisorManager.java:116) ~[druid-indexing-service-0.9.2.jar:0.9.2]
    ... 16 more
```

**Comment by drcrallen** [comment]
How did travis CI java7 build not catch this?

**Comment by drcrallen** [comment]
ohhh, because it compiles in java 7 for java 7

**Comment by gianm** [comment]
I bet the travis CI java7 build actually uses a java7 compiler.

**Comment by ben-manes** [comment]
You could use Animal Sniffer and Collections.newSetFromMap()

**Comment by himanshug** [comment]
can you explain, "Pass the JDK7 runtime to bootclasspath when compiling with javac" a bit more?

will that be equivalent of compiling with java7 compiler instead of java8 compiler targeting version-7 ? If yes, I would like that because that will also take care of other similar (undiscovered) issues.

and, let us keep marching on java-8 only goal if tranquility and spark work fine but not let that be a blocker for the issue at hand.

**Comment by drcrallen** [comment]
The suggested work around from the maintainers is to cast to `Map` before calling `keySet()`
https://bugs.openjdk.java.net/browse/JDK-8151366?focusedCommentId=13973374&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13973374 Which sounds good to me

**Comment by gianm** [comment]
@himanshug "Pass the JDK7 runtime to bootclsaspath" was referring to this comment https://bugs.openjdk.java.net/browse/JDK-8151366?focusedCommentId=13909482&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13909482

**Comment by gianm** [comment]
Both of those two workarounds were suggested by different people in the JDK-8151366 ticket.

**Comment by himanshug** [comment]
there is not way to quantitatively select either of those. let us just go with "casting to Map" workaround . if we find similar issues in future then we can switch to "pass the jdk7 runtime to bootclasspath" later.

**Comment by gianm** [comment]
That Animal Sniffer thing @ben-manes mentioned looks like it has a maven plugin (http://www.mojohaus.org/animal-sniffer/animal-sniffer-maven-plugin/), maybe that would help verify.

**Comment by gianm** [comment]
PR in #3796.

**Comment by pjain1** [comment]
We use Java 8 to build and run druid code and facing this issue in our internal deployment. The way it manifests is that thread gets stuck at point where `JavaCompatUtils.keySet(<Map>)` is used. Using `entrySet` for iteration or explicitly casting to a Map like `((Map)m).keySet` as suggested in https://bugs.openjdk.java.net/browse/JDK-8151366 works. Explicit cast however leads to loss of Generic type for key and values in the map.
Any thoughts ?

**Comment by gianm** [comment]
What do you mean by "the thread gets stuck"? We use jdk 8 to build and run Druid code too and haven't seen anything like that.

**Comment by pjain1** [comment]
I mean the code beyond that point is not executed. For example, neither [this](https://github.com/druid-io/druid/blob/master/extensions-core/kafka-indexing-service/src/main/java/io/druid/indexing/kafka/supervisor/KafkaSupervisor.java#L1231) `for` loop gets executed nor the control goes beyond the loop. I took a thread dump but that suggests that the supervisor thread is waiting on `take` method. So I am not entirely sure what's happening.
```
"KafkaSupervisor-v2_metrics_cluster-Scheduler-0" #196 daemon prio=5 os_prio=0 tid=0x00007fe780180000 nid=0x74b0 waiting on condition [0x00007fe6f9da2000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000004e1c30bc8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"KafkaSupervisor-v2_metrics_cluster" #195 daemon prio=5 os_prio=0 tid=0x00007fe780173800 nid=0x74af waiting on condition [0x00007fe6f9ea3000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000004e1c30df8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by pjain1** [comment]
I added log statements to check how far the code is being executed.

**Comment by gianm** [comment]
Hmm, that seems like some sort of "Throwable gets thrown but not caught and thread dies" thing. Do you see interesting errors if you put a try/catch Throwable around whatever is calling keySet?

**Comment by pjain1** [comment]
I just tried that and do not see any exceptions

**Comment by pjain1** [comment]
Actually there is an `Error` thrown, I was just catching `Exception` and seems like I have an old version of `java-util` jar that does not have the `JavaCompatUtils` sorry for bothering. My mistake, I think it will work after I put in the new jar. Thanks
