### ISSUE TITLE
Null Handling

### ISSUE THREAD

**Issue by b-slim** [druid-io/druid#3846]
running manually tests on `SchemalessTestFull` and  `SchemalessTestSimple.testFullOnTimeseries` fail due to some null handling issue i guess. As @gianm mention those are not run by maven due to the name convention. 
```java
ava.lang.AssertionError: 
Expected :Result{timestamp=2011-01-12T00:00:00.000Z, value=TimeseriesResultValue{value=MetricValueExtractor{value={rows=11, index=900.0, addRowsIndexConstant=912.0, uniques=2.000977198748901, maxIndex=100.0, minIndex=0.0}}}}
Actual   :Result{timestamp=2011-01-12T00:00:00.000Z, value=TimeseriesResultValue{value=MetricValueExtractor{value={uniques=3.0021994137521975, addRowsIndexConstant=912.0, index=900.0, minIndex=0.0, maxIndex=100.0, rows=11}}}}
 <Click to see difference>


	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at io.druid.segment.TestHelper.assertResult(TestHelper.java:222)
	at io.druid.segment.TestHelper.assertResults(TestHelper.java:140)
	at io.druid.segment.TestHelper.assertExpectedResults(TestHelper.java:93)
	at io.druid.segment.SchemalessTestSimple.testFullOnTimeseries(SchemalessTestSimple.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by gianm** [comment]
Oh, cool. Also that class should be called SchemalessSimpleTest, since if it doesn't end in Test, it won't run through maven.

**Comment by b-slim** [comment]
@gianm i was banging my head how this was uncaught but i guess you have the answer ...

**Comment by b-slim** [comment]
FYI same for `SchemalessTestFull`
