### ISSUE TITLE
BUG: occasionally port confliction in peon

### ISSUE THREAD

**Issue by hamlet-lee** [druid-io/druid#3876]
My hadoop ingest task occasionally fail, exception:
```
2017-01-21T23:36:49,737 WARN [main] org.eclipse.jetty.util.component.AbstractLifeCycle - FAILED ServerConnector@2bc16fe2{HTTP/1.1}{0.0.0.0:28102}: java.net.BindException: Address already in use
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_77]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_77]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_77]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_77]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_77]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.5.v20141112.jar:9.2.5.v20141112]
	at org.eclipse.jetty.server.Server.doStart(Server.java:366) [jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.5.v20141112.jar:9.2.5.v20141112]
	at io.druid.server.initialization.jetty.JettyServerModule$1.start(JettyServerModule.java:204) [druid-server-0.9.2.jar:0.9.2]
	at com.metamx.common.lifecycle.Lifecycle.start(Lifecycle.java:259) [java-util-0.27.10.jar:?]
	at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:155) [druid-api-0.9.2.jar:0.9.2]
	at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:101) [druid-services-0.9.2.jar:0.9.2]
	at io.druid.cli.CliPeon.run(CliPeon.java:274) [druid-services-0.9.2.jar:0.9.2]
	at io.druid.cli.Main.main(Main.java:106) [druid-services-0.9.2.jar:0.9.2]
2017-01-21T23:36:49,743 WARN [main] org.eclipse.jetty.util.component.AbstractLifeCycle - FAILED org.eclipse.jetty.server.Server@32b112a1: java.net.BindException: Address already in use
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_77]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_77]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_77]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_77]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_77]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.5.v20141112.jar:9.2.5.v20141112]
	at org.eclipse.jetty.server.Server.doStart(Server.java:366) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.5.v20141112.jar:9.2.5.v20141112]
	at io.druid.server.initialization.jetty.JettyServerModule$1.start(JettyServerModule.java:204) [druid-server-0.9.2.jar:0.9.2]
	at com.metamx.common.lifecycle.Lifecycle.start(Lifecycle.java:259) [java-util-0.27.10.jar:?]
	at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:155) [druid-api-0.9.2.jar:0.9.2]
	at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:101) [druid-services-0.9.2.jar:0.9.2]
	at io.druid.cli.CliPeon.run(CliPeon.java:274) [druid-services-0.9.2.jar:0.9.2]
	at io.druid.cli.Main.main(Main.java:106) [druid-services-0.9.2.jar:0.9.2]
2017-01-21T23:36:49,744 ERROR [main] io.druid.cli.CliPeon - Error when starting up.  Failing.
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_77]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_77]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_77]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_77]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_77]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.2.5.v20141112.jar:9.2.5.v20141112]
	at org.eclipse.jetty.server.Server.doStart(Server.java:366) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.2.5.v20141112.jar:9.2.5.v20141112]
	at io.druid.server.initialization.jetty.JettyServerModule$1.start(JettyServerModule.java:204) ~[druid-server-0.9.2.jar:0.9.2]
	at com.metamx.common.lifecycle.Lifecycle.start(Lifecycle.java:259) ~[java-util-0.27.10.jar:?]
	at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:155) ~[druid-api-0.9.2.jar:0.9.2]
	at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:101) [druid-services-0.9.2.jar:0.9.2]
	at io.druid.cli.CliPeon.run(CliPeon.java:274) [druid-services-0.9.2.jar:0.9.2]
	at io.druid.cli.Main.main(Main.java:106) [druid-services-0.9.2.jar:0.9.2]
```

I suspect this is because multiple task are submitted concurrently and 'free port' may conflict.

e.g. sequence: 
1) task A submitted
2) task B submitted
3) task A peon started
4) task B peon started
5) task A peon judged free port as 11111
6) task B peon judged free port as 11111
7) task A try listen on 11111, succeeded
8) task B try listen on 11111, failed!

**Comment by nishantmonu51** [comment]
@hamlet-lee: The port assignment actually happens in middlemanager instead of peon. 
https://github.com/druid-io/druid/blob/master/indexing-service/src/main/java/io/druid/indexing/overlord/ForkingTaskRunner.java#L238

I wonder if you are running multiple middlemanagers on same node which might be causing this ? 
Or there is some other system process other than the peon which started after the middlemanager assigned the port to the peon and before the peon actually started ?

**Comment by hamlet-lee** [comment]
No multiple middlemanager found.  Maybe there is other reason caused this problem.  I will try to reproduce this problem.

**Comment by mitch-hulu** [comment]
Is there a reason the port scan logic doesnt just happen in the peon itself? Does middle manager need the port to announce the peon? Or does the peon announce itself?

**Comment by gianm** [comment]
The middleManager announces the location of the task peon. I would guess the same as @nishantmonu51, that something else started using this port (28102). Maybe double check that your OS doesn't include this in its ephemeral port range.

Closing the issue but feel free to reopen if it seems Druid related after more investigation.
