### ISSUE TITLE
Druid Ingestion fails throws exception at the end

### ISSUE THREAD

**Issue by NirajaM** [druid-io/druid#3887]
I am running ingestion job with druid (0.9.1.1) using druid local indexing.

Jobs are failing with the exception at the end.

op()] on object[io.druid.initialization.Log4jShutterDownerModule$Log4jShutterDowner@39393716].
2017-01-27 12:46:39,345 Thread-2 ERROR Unable to register shutdown hook because JVM is shutting down. java.lang.IllegalStateException: Not started
        at io.druid.common.config.Log4jShutdown.addShutdownCallback(Log4jShutdown.java:45)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.addShutdownCallback(Log4jContextFactory.java:273)
        at org.apache.logging.log4j.core.LoggerContext.setUpShutdownHook(LoggerContext.java:256)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:216)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:145)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:182)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:103)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:42)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:284)
        at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
        at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)
        at org.apache.hadoop.hdfs.LeaseRenewer.<clinit>(LeaseRenewer.java:72)
        at org.apache.hadoop.hdfs.DFSClient.getLeaseRenewer(DFSClient.java:639)
        at org.apache.hadoop.hdfs.DFSClient.close(DFSClient.java:792)
        at org.apache.hadoop.hdfs.DistributedFileSystem.close(DistributedFileSystem.java:847)
        at org.apache.hadoop.fs.FileSystem$Cache.closeAll(FileSystem.java:2524)
        at org.apache.hadoop.fs.FileSystem$Cache$ClientFinalizer.run(FileSystem.java:2541)
        at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:54)

**Comment by gianm** [comment]
Looks like the same issue as #3851; please watch that one.
