### ISSUE TITLE
Tasks run FAILED, all the time

### ISSUE THREAD

**Issue by aubdiy** [druid-io/druid#3934]
version: druid-0.9.2
I set up it up on a single machine by "Druid Quickstart",  all services are set up   ok,

when i  run 
```
curl -X 'POST' -H 'Content-Type:application/json' -d @/data/software/druid-0.9.2/quickstart/wikiticker-index.json localhost:8090/druid/indexer/v1/task
```
Coordinator Console  show   
```
Complete Tasks - Tasks recently completed
index_hadoop_wikiticker_2017-02-14T09:47:54.249Z	FAILED	13765	null	-1
```

the log show
```
2017-02-14T09:48:07,847 INFO [Thread-42] org.apache.hadoop.mapred.LocalJobRunner - reduce task executor complete.
2017-02-14T09:48:07,852 WARN [Thread-42] org.apache.hadoop.mapred.LocalJobRunner - job_local1458052272_0002
java.lang.Exception: java.io.IOException: æ²¡æœ‰é‚£ä¸ªæ–‡ä»¶æˆ–ç›®å½•
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462) ~[hadoop-mapreduce-client-common-2.3.0.jar:?]
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:529) [hadoop-mapreduce-client-common-2.3.0.jar:?]
Caused by: java.io.IOException: æ²¡æœ‰é‚£ä¸ªæ–‡ä»¶æˆ–ç›®å½•
	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_101]
	at java.io.File.createTempFile(File.java:2024) ~[?:1.8.0_101]
	at java.io.File.createTempFile(File.java:2070) ~[?:1.8.0_101]
	at io.druid.indexer.IndexGeneratorJob$IndexGeneratorReducer.reduce(IndexGeneratorJob.java:569) ~[druid-indexing-hadoop-0.9.2.jar:0.9.2]
	at io.druid.indexer.IndexGeneratorJob$IndexGeneratorReducer.reduce(IndexGeneratorJob.java:478) ~[druid-indexing-hadoop-0.9.2.jar:0.9.2]
	at org.apache.hadoop.mapreduce.Reducer.run(Reducer.java:171) ~[hadoop-mapreduce-client-core-2.3.0.jar:?]
	at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:627) ~[hadoop-mapreduce-client-core-2.3.0.jar:?]
	at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:389) ~[hadoop-mapreduce-client-core-2.3.0.jar:?]
	at org.apache.hadoop.mapred.LocalJobRunner$Job$ReduceTaskRunnable.run(LocalJobRunner.java:319) ~[hadoop-mapreduce-client-common-2.3.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_101]
```

who can help me ,  thanks

**Comment by aubdiy** [comment]
i forget run "bin/init"....
