### ISSUE TITLE
metadata table not exist when upgrade from 0.9.0 to 0.9.2

### ISSUE THREAD

**Issue by huangchaosuper** [druid-io/druid#3946]
table druid_meta.druid_supervisors not exist when upgrade from 0.9.0 to 0.9.2
how to upgrade from 0.9.0 to 0.9.2 , I am not sure how many tables need I do 

`Caused by: org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'druid_meta.druid_supervisors' doesn't exist [statement:"SELECT r.spec_id, r.payload FROM druid_supervisors r INNER JOIN(SELECT spec_id, max(id) as id FROM druid_supervisors GROUP BY spec_id) latest ON r.id = latest.id"
, located:"SELECT r.spec_id, r.payload FROM druid_supervisors r INNER JOIN(SELECT spec_id, max(id) as id FROM druid_supervisors GROUP BY spec_id) latest ON r.id = latest.id", rewritten:"SELECT r.spec_id, r.payload FROM druid_supervisors r INNER JOIN(SELECT spec_id, max(id) as id FROM druid_supervisors GROUP BY spec_id) latest ON r.id = latest.id", arguments
:{ positional:{}, named:{}, finder:[]}]`

**Comment by huangchaosuper** [comment]
need upgrade metadata scripts supports?

**Comment by gianm** [comment]
@huangchaosuper, what code is triggering this error and how much of your cluster is running 0.9.2? We do have code that creates the druid_supervisors table when an overlord starts up -- so after overlords are upgraded, you should be ok.

**Comment by huangchaosuper** [comment]
the error shown when I upgrade overlord. so I am not sure how to fix my issue.
my cluster is small, but in production. only one instance of each type service. only one overlord server.

below is the full log . could you please help me ?

2017-02-17T09:01:04,542 WARN [main] io.druid.metadata.SQLMetadataConnector - Exception creating table
org.skife.jdbi.v2.exceptions.CallbackFailedException: com.metamx.common.ISE: Database default character set is not UTF-8.
  Druid requires its MySQL database to be created using UTF-8 as default character set.
        at org.skife.jdbi.v2.DBI.withHandle(DBI.java:284) ~[jdbi-2.63.1.jar:2.63.1]
        at io.druid.metadata.SQLMetadataConnector$2.call(SQLMetadataConnector.java:124) ~[druid-server-0.9.2.jar:0.9.2]
        at com.metamx.common.RetryUtils.retry(RetryUtils.java:60) ~[java-util-0.27.10.jar:?]
        at com.metamx.common.RetryUtils.retry(RetryUtils.java:78) ~[java-util-0.27.10.jar:?]
        at io.druid.metadata.SQLMetadataConnector.retryWithHandle(SQLMetadataConnector.java:128) ~[druid-server-0.9.2.jar:0.9.2]
        at io.druid.metadata.SQLMetadataConnector.retryWithHandle(SQLMetadataConnector.java:137) ~[druid-server-0.9.2.jar:0.9.2]
        at io.druid.metadata.SQLMetadataConnector.createTable(SQLMetadataConnector.java:177) [druid-server-0.9.2.jar:0.9.2]
        at io.druid.metadata.SQLMetadataConnector.createConfigTable(SQLMetadataConnector.java:295) [druid-server-0.9.2.jar:0.9.2]
        at io.druid.metadata.SQLMetadataConnector.createConfigTable(SQLMetadataConnector.java:476) [druid-server-0.9.2.jar:0.9.2]
        at io.druid.guice.JacksonConfigManagerModule$1.start(JacksonConfigManagerModule.java:58) [druid-common-0.9.2.jar:0.9.2]
        at com.metamx.common.lifecycle.Lifecycle.start(Lifecycle.java:259) [java-util-0.27.10.jar:?]
        at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:155) [druid-api-0.9.2.jar:0.9.2]
        at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:101) [druid-services-0.9.2.jar:0.9.2]
        at io.druid.cli.ServerRunnable.run(ServerRunnable.java:40) [druid-services-0.9.2.jar:0.9.2]
        at io.druid.cli.Main.main(Main.java:106) [druid-services-0.9.2.jar:0.9.2]
Caused by: com.metamx.common.ISE: Database default character set is not UTF-8.
  Druid requires its MySQL database to be created using UTF-8 as default character set.
        at io.druid.metadata.storage.mysql.MySQLConnector.tableExists(MySQLConnector.java:97) ~[?:?]
        at io.druid.metadata.SQLMetadataConnector$4.withHandle(SQLMetadataConnector.java:183) ~[druid-server-0.9.2.jar:0.9.2]
        at io.druid.metadata.SQLMetadataConnector$4.withHandle(SQLMetadataConnector.java:179) ~[druid-server-0.9.2.jar:0.9.2]
        at org.skife.jdbi.v2.DBI.withHandle(DBI.java:281) ~[jdbi-2.63.1.jar:2.63.1]
        ... 14 more
2017-02-17T09:01:04,547 INFO [main] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking start method[public void io.druid.common.config.ConfigManager.start()] on object[io.druid.common.config.ConfigManager@b52b755].


2017-02-17T09:01:20,933 ERROR [Curator-LeaderSelector-0] io.druid.indexing.overlord.TaskMaster - Failed to lead: {class=io.druid.indexing.overlord.TaskMaster, exceptionType=class java.lang.reflect.InvocationTargetException, exceptionMessage=null}
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler.start(Lifecycle.java:350) ~[java-util-0.27.10.jar:?]
        at com.metamx.common.lifecycle.Lifecycle.start(Lifecycle.java:259) ~[java-util-0.27.10.jar:?]
        at io.druid.indexing.overlord.TaskMaster$1.takeLeadership(TaskMaster.java:141) [druid-indexing-service-0.9.2.jar:0.9.2]
        at org.apache.curator.framework.recipes.leader.LeaderSelector$WrappedListener.takeLeadership(LeaderSelector.java:534) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.leader.LeaderSelector.doWork(LeaderSelector.java:399) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.leader.LeaderSelector.doWorkLoop(LeaderSelector.java:441) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.leader.LeaderSelector.access$100(LeaderSelector.java:64) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:245) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:239) [curator-recipes-2.11.0.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: org.skife.jdbi.v2.exceptions.CallbackFailedException: org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'druid_meta.druid_supervisors' doesn't exist [statement:"SELECT r.spec_id, r.payload FROM druid_supervisors r INNER JOIN(SELECT spec_id, max(id) as id FROM druid_supervisors GROUP BY spec_id) latest ON r.id = latest.id", located:"SELECT r.spec_id, r.payload FROM druid_supervisors r INNER JOIN(SELECT spec_id, max(id) as id FROM druid_supervisors GROUP BY spec_id) latest ON r.id = latest.id", rewritten:"SELECT r.spec_id, r.payload FROM druid_supervisors r INNER JOIN(SELECT spec_id, max(id) as id FROM druid_supervisors GROUP BY spec_id) latest ON r.id = latest.id", arguments:{ positional:{}, named:{}, finder:[]}]
        at org.skife.jdbi.v2.DBI.withHandle(DBI.java:284) ~[jdbi-2.63.1.jar:2.63.1]
        at io.druid.metadata.SQLMetadataSupervisorManager.getLatest(SQLMetadataSupervisorManager.java:180) ~[druid-server-0.9.2.jar:0.9.2]
        at io.druid.indexing.overlord.supervisor.SupervisorManager.start(SupervisorManager.java:98) ~[druid-indexing-service-0.9.2.jar:0.9.2]
        ... 19 more
Caused by: org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'druid_meta.druid_supervisors' doesn't exist [statement:"SELECT r.spec_id, r.payload FROM druid_supervisors r INNER JOIN(SELECT spec_id, max(id) as id FROM druid_supervisors GROUP BY spec_id) latest ON r.id = latest.id", located:"SELECT r.spec_id, r.payload FROM druid_supervisors r INNER JOIN(SELECT spec_id, max(id) as id FROM druid_supervisors GROUP BY spec_id) latest ON r.id = latest.id", rewritten:"SELECT r.spec_id, r.payload FROM druid_supervisors r INNER JOIN(SELECT spec_id, max(id) as id FROM druid_supervisors GROUP BY spec_id) latest ON r.id = latest.id", arguments:{ positional:{}, named:{}, finder:[]}]
        at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1334) ~[jdbi-2.63.1.jar:2.63.1]
        at org.skife.jdbi.v2.Query.fold(Query.java:173) ~[jdbi-2.63.1.jar:2.63.1]
        at io.druid.metadata.SQLMetadataSupervisorManager$3.withHandle(SQLMetadataSupervisorManager.java:216) ~[druid-server-0.9.2.jar:0.9.2]
        at io.druid.metadata.SQLMetadataSupervisorManager$3.withHandle(SQLMetadataSupervisorManager.java:182) ~[druid-server-0.9.2.jar:0.9.2]
        at org.skife.jdbi.v2.DBI.withHandle(DBI.java:281) ~[jdbi-2.63.1.jar:2.63.1]
        at io.druid.metadata.SQLMetadataSupervisorManager.getLatest(SQLMetadataSupervisorManager.java:180) ~[druid-server-0.9.2.jar:0.9.2]
        at io.druid.indexing.overlord.supervisor.SupervisorManager.start(SupervisorManager.java:98) ~[druid-indexing-service-0.9.2.jar:0.9.2]
        ... 19 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'druid_meta.druid_supervisors' doesn't exist
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[?:?]
        at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[?:?]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:939) ~[?:?]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878) ~[?:?]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814) ~[?:?]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478) ~[?:?]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625) ~[?:?]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551) ~[?:?]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861) ~[?:?]
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192) ~[?:?]
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:198) ~[commons-dbcp2-2.0.1.jar:2.0.1]
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:198) ~[commons-dbcp2-2.0.1.jar:2.0.1]
        at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1328) ~[jdbi-2.63.1.jar:2.63.1]
        at org.skife.jdbi.v2.Query.fold(Query.java:173) ~[jdbi-2.63.1.jar:2.63.1]
        at io.druid.metadata.SQLMetadataSupervisorManager$3.withHandle(SQLMetadataSupervisorManager.java:216) ~[druid-server-0.9.2.jar:0.9.2]
        at io.druid.metadata.SQLMetadataSupervisorManager$3.withHandle(SQLMetadataSupervisorManager.java:182) ~[druid-server-0.9.2.jar:0.9.2]
        at org.skife.jdbi.v2.DBI.withHandle(DBI.java:281) ~[jdbi-2.63.1.jar:2.63.1]
        at io.druid.metadata.SQLMetadataSupervisorManager.getLatest(SQLMetadataSupervisorManager.java:180) ~[druid-server-0.9.2.jar:0.9.2]
        at io.druid.indexing.overlord.supervisor.SupervisorManager.start(SupervisorManager.java:98) ~[druid-indexing-service-0.9.2.jar:0.9.2]
        ... 19 more

**Comment by huangchaosuper** [comment]
I manual execute below sql `create table druid_meta.druid_supervisors (
	id BIGINT(20) not NULL,
    spec_id VARCHAR(255) NOT NULL,
    created_date VARCHAR(255) NOT NULL,
    payload LONGBLOB  NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX idx_druid_supervisors_spec_id ON druid_meta.druid_supervisors(spec_id);`

the issue disappeared
