### ISSUE TITLE
parsing timestamp with fractional seconds fails

### ISSUE THREAD

**Issue by gallamine** [druid-io/druid#3952]
I am running `druid-0.9.2` on `osx 10.10.5`. I am running all the services locally according to the http://druid.io/docs/0.9.1.1/tutorials/quickstart.html example.

I created a sample TSV and wrote a new index to ingest the data. 

The sample data is as follows:

```
 1421	3929	123.765.432.74	1487249458.633	GET /eu_cookie_notice HTTP/1.1
 1421	3929	123.456.123.6	1487249458.634	GET / HTTP/1.1
```
The index is following:

```
{
  "type" : "index_hadoop",
  "spec" : {
    "ioConfig" : {
      "type" : "hadoop",
      "inputSpec" : {
        "type" : "static",
        "paths" : "quickstart/sample-test.log"
      }
    },
    "dataSchema" : {
      "dataSource" : "web-logs",
      "granularitySpec" : {
        "type" : "uniform",
        "segmentGranularity" : "day",
        "queryGranularity" : "none",
        "intervals" : ["2015-09-12/2015-09-13"]
      },
      "parser" : {
        "type" : "hadoopyString",
        "parseSpec" : {
          "format" : "tsv",
          "columns" : [
              "account_id",
              "domain_id",
              "ip",
              "access_time",
              "request"
            ],
          "delimiter" : "\t",
          "dimensionsSpec" : {
            "dimensions" : [
              "account_id",
              "domain_id",
              "ip"
            ]
          },
          "timestampSpec" : {
            "format" : "posix",
            "column" : "access_time"
          }
        }
      },
      "metricsSpec" : [
        {
          "name" : "count",
          "type" : "count"
        }
      ]
    },
    "tuningConfig" : {
      "type" : "hadoop",
      "partitionsSpec" : {
        "type" : "hashed",
        "targetPartitionSize" : 5000000
      },
      "jobProperties" : {}
    }
  }
}
```

My systems uses a timestamp with a fractional seconds value at the end `1487249458.633` which causes the job to fail. I have tried all the various `timestampSpec` I could find in the documents without success.

When I submit the job with

```
$ curl -X 'POST' -H 'Content-Type:application/json' -d @sample-test-index.json
```

my job fails with the following error:

```
2017-02-17T21:13:26,569 WARN [Thread-20] org.apache.hadoop.mapred.LocalJobRunner - job_local316914273_0001
java.lang.Exception: com.metamx.common.RE: Failure on row[ 1421	3929	123.765.432.74	1487249458.633	GET /eu_cookie_notice HTTP/1.1]
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462) ~[hadoop-mapreduce-client-common-2.3.0.jar:?]
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:522) [hadoop-mapreduce-client-common-2.3.0.jar:?]
Caused by: com.metamx.common.RE: Failure on row[ 1421	3929	123.765.432.74	1487249458.633	GET /eu_cookie_notice HTTP/1.1]
	at io.druid.indexer.HadoopDruidIndexerMapper.map(HadoopDruidIndexerMapper.java:91) ~[druid-indexing-hadoop-0.9.2.jar:0.9.2]
	at io.druid.indexer.DetermineHashedPartitionsJob$DetermineCardinalityMapper.run(DetermineHashedPartitionsJob.java:285) ~[druid-indexing-hadoop-0.9.2.jar:0.9.2]
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:764) ~[hadoop-mapreduce-client-core-2.3.0.jar:?]
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:340) ~[hadoop-mapreduce-client-core-2.3.0.jar:?]
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243) ~[hadoop-mapreduce-client-common-2.3.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_73]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_73]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_73]
Caused by: com.metamx.common.parsers.ParseException: Unparseable timestamp found!
	at io.druid.data.input.impl.MapInputRowParser.parse(MapInputRowParser.java:72) ~[druid-api-0.9.2.jar:0.9.2]
	at io.druid.data.input.impl.StringInputRowParser.parseMap(StringInputRowParser.java:136) ~[druid-api-0.9.2.jar:0.9.2]
	at io.druid.data.input.impl.StringInputRowParser.parse(StringInputRowParser.java:131) ~[druid-api-0.9.2.jar:0.9.2]
	at io.druid.indexer.HadoopyStringInputRowParser.parse(HadoopyStringInputRowParser.java:48) ~[druid-indexing-hadoop-0.9.2.jar:0.9.2]
	at io.druid.indexer.HadoopDruidIndexerMapper.parseInputRow(HadoopDruidIndexerMapper.java:105) ~[druid-indexing-hadoop-0.9.2.jar:0.9.2]
	at io.druid.indexer.HadoopDruidIndexerMapper.map(HadoopDruidIndexerMapper.java:72) ~[druid-indexing-hadoop-0.9.2.jar:0.9.2]
	at io.druid.indexer.DetermineHashedPartitionsJob$DetermineCardinalityMapper.run(DetermineHashedPartitionsJob.java:285) ~[druid-indexing-hadoop-0.9.2.jar:0.9.2]
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:764) ~[hadoop-mapreduce-client-core-2.3.0.jar:?]
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:340) ~[hadoop-mapreduce-client-core-2.3.0.jar:?]
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243) ~[hadoop-mapreduce-client-common-2.3.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_73]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_73]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_73]
Caused by: java.lang.NumberFormatException: For input string: "1487249458.633"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_73]
	at java.lang.Long.parseLong(Long.java:589) ~[?:1.8.0_73]
	at java.lang.Long.parseLong(Long.java:631) ~[?:1.8.0_73]
	at com.metamx.common.parsers.TimestampParser$3.apply(TimestampParser.java:73) ~[java-util-0.27.10.jar:?]
	at com.metamx.common.parsers.TimestampParser$3.apply(TimestampParser.java:68) ~[java-util-0.27.10.jar:?]
	at com.metamx.common.parsers.TimestampParser$9.apply(TimestampParser.java:159) ~[java-util-0.27.10.jar:?]
	at com.metamx.common.parsers.TimestampParser$9.apply(TimestampParser.java:150) ~[java-util-0.27.10.jar:?]
	at io.druid.data.input.impl.TimestampSpec.extractTimestamp(TimestampSpec.java:97) ~[druid-api-0.9.2.jar:0.9.2]
	at io.druid.data.input.impl.MapInputRowParser.parse(MapInputRowParser.java:60) ~[druid-api-0.9.2.jar:0.9.2]
	at io.druid.data.input.impl.StringInputRowParser.parseMap(StringInputRowParser.java:136) ~[druid-api-0.9.2.jar:0.9.2]
	at io.druid.data.input.impl.StringInputRowParser.parse(StringInputRowParser.java:131) ~[druid-api-0.9.2.jar:0.9.2]
	at io.druid.indexer.HadoopyStringInputRowParser.parse(HadoopyStringInputRowParser.java:48) ~[druid-indexing-hadoop-0.9.2.jar:0.9.2]
	at io.druid.indexer.HadoopDruidIndexerMapper.parseInputRow(HadoopDruidIndexerMapper.java:105) ~[druid-indexing-hadoop-0.9.2.jar:0.9.2]
	at io.druid.indexer.HadoopDruidIndexerMapper.map(HadoopDruidIndexerMapper.java:72) ~[druid-indexing-hadoop-0.9.2.jar:0.9.2]
	at io.druid.indexer.DetermineHashedPartitionsJob$DetermineCardinalityMapper.run(DetermineHashedPartitionsJob.java:285) ~[druid-indexing-hadoop-0.9.2.jar:0.9.2]
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:764) ~[hadoop-mapreduce-client-core-2.3.0.jar:?]
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:340) ~[hadoop-mapreduce-client-core-2.3.0.jar:?]
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243) ~[hadoop-mapreduce-client-common-2.3.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_73]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_73]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_73]
```

I am posting this issue at the request of B-Slim on the Druid users mailing list (https://groups.google.com/d/msgid/druid-user/f2adf167-9519-4aaf-bf61-f66405adc998%40googlegroups.com?utm_medium=email&utm_source=footer).

**Comment by b-slim** [comment]
@gallamine after looking at the posix specification it clearly states that is the number of second from the epoch, hence this number by construction is not fractional. Looking into the druid code i found out that the input will be read as a string which cause the exception. Now i am not sure that rounding of the fraction is a good idea if i were to fix that. i know that you can argue that there is no need to round the number since we are doing the X 1000 later on,  but doing a major change to move from long to double is not that easy. IMO the best maybe is to add another format or/and spec that can deal with such cases.

**Comment by b-slim** [comment]
@gallamine also was wondering how hard is it to convert that into `millis` and let druid parse it that way ? would that be very expensive ?

**Comment by gallamine** [comment]
Changing the value before it arrives in the log is expensive as it requires major system changes.  My understanding is that this is the standard time representation for NGINX (the `msec` variable), so it's possibly worth supporting by Druid in the future.

For the time being, I'll investigate writing a custom parser to deal with it.
Thanks for the help!

**Comment by b-slim** [comment]
@gallamine thanks ! let me know if you need help.

**Comment by kaijianding** [comment]
I think you should use ruby, https://github.com/metamx/java-util/blob/master/src/main/java/com/metamx/common/parsers/TimestampParser.java#L84

**Comment by fjy** [comment]
@kaijianding just an FYI that java-util was moved into Druid

**Comment by gallamine** [comment]
Posting here to confirm that choosing the `ruby` spec for timestampSpec seems to work fine. As of yet this spec isn't documented yet.
