### ISSUE TITLE
EOFException in `Avro-Extension`

### ISSUE THREAD

**Issue by asdf2014** [druid-io/druid#4098]
```
"KafkaConsumer-2" #33 daemon prio=5 os_prio=0 tid=0x00007f421922b000 nid=0x5a5 runnable [0x00007f414935e000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.Throwable.fillInStackTrace(Native Method)
        at java.lang.Throwable.fillInStackTrace(Throwable.java:783)
        - locked <0x0000000693455340> (a java.io.EOFException)
        at java.lang.Throwable.<init>(Throwable.java:250)
        at java.lang.Exception.<init>(Exception.java:54)
        at java.io.IOException.<init>(IOException.java:47)
        at java.io.EOFException.<init>(EOFException.java:50)
        at org.apache.avro.util.ByteBufferInputStream.getBuffer(ByteBufferInputStream.java:86)
        at org.apache.avro.util.ByteBufferInputStream.read(ByteBufferInputStream.java:48)
        at org.apache.avro.io.BinaryDecoder$InputStreamByteSource.tryReadRaw(BinaryDecoder.java:839)
        at org.apache.avro.io.BinaryDecoder$ByteSource.compactAndFill(BinaryDecoder.java:692)
        at org.apache.avro.io.BinaryDecoder.ensureBounds(BinaryDecoder.java:471)
        at org.apache.avro.io.BinaryDecoder.readLong(BinaryDecoder.java:160)
        at org.apache.avro.io.ResolvingDecoder.readLong(ResolvingDecoder.java:162)
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:160)
        at org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:193)
        at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:183)
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:151)
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:142)
        at io.druid.data.input.avro.InlineSchemaAvroBytesDecoder.parse(InlineSchemaAvroBytesDecoder.java:86)
        at io.druid.data.input.AvroStreamInputRowParser.parse(AvroStreamInputRowParser.java:53)
        at io.druid.data.input.AvroStreamInputRowParser.parse(AvroStreamInputRowParser.java:33)
        at com.metamx.tranquility.druid.DruidBeams$$anonfun$1$$anonfun$7.apply(DruidBeams.scala:182)
        at com.metamx.tranquility.druid.DruidBeams$$anonfun$1$$anonfun$7.apply(DruidBeams.scala:182)
        at com.metamx.tranquility.druid.DruidBeams$$anonfun$1$$anonfun$apply$1.apply(DruidBeams.scala:200)
        at com.metamx.tranquility.druid.DruidBeams$$anonfun$1$$anonfun$apply$1.apply(DruidBeams.scala:200)
        at com.metamx.tranquility.beam.TransformingBeam$$anonfun$sendAll$2$$anonfun$2.apply(TransformingBeam.scala:36)
        at com.twitter.util.Try$.apply(Try.scala:13)
        at com.metamx.tranquility.beam.TransformingBeam$$anonfun$sendAll$2.apply(TransformingBeam.scala:36)
        at com.metamx.tranquility.beam.TransformingBeam$$anonfun$sendAll$2.apply(TransformingBeam.scala:35)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
        at com.metamx.tranquility.beam.TransformingBeam.sendAll(TransformingBeam.scala:35)
        at com.metamx.tranquility.tranquilizer.Tranquilizer.com$metamx$tranquility$tranquilizer$Tranquilizer$$sendBuffer(Tranquilizer.scala:301)
        at com.metamx.tranquility.tranquilizer.Tranquilizer$$anonfun$send$1.apply(Tranquilizer.scala:202)
        at com.metamx.tranquility.tranquilizer.Tranquilizer$$anonfun$send$1.apply(Tranquilizer.scala:202)
        at scala.Option.foreach(Option.scala:236)
        at com.metamx.tranquility.tranquilizer.Tranquilizer.send(Tranquilizer.scala:202)
        at com.metamx.tranquility.kafka.writer.TranquilityEventWriter.send(TranquilityEventWriter.java:76)
        at com.metamx.tranquility.kafka.KafkaConsumer$2.run(KafkaConsumer.java:231)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by asdf2014** [comment]
I found a isssue in `Avro` (https://issues.apache.org/jira/browse/AVRO-813). I think it could be the reason. Should we log some to explain it for `Druid` user?
