### ISSUE TITLE
java.lang.OutOfMemoryError: Requested array size exceeds VM limit

### ISSUE THREAD

**Issue by asdf2014** [druid-io/druid#4108]
I run `tranquility` instance for a few days, then the process throw `OOM` exception...
```
2017-03-24 00:25:45,049 [KafkaConsumer-3] ERROR c.m.tranquility.kafka.KafkaConsumer - Exception:
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
        at org.apache.avro.util.Utf8.setByteLength(Utf8.java:78) ~[na:na]
        at org.apache.avro.io.BinaryDecoder.readString(BinaryDecoder.java:261) ~[na:na]
        at org.apache.avro.io.ResolvingDecoder.readString(ResolvingDecoder.java:201) ~[na:na]
        at org.apache.avro.generic.GenericDatumReader.readString(GenericDatumReader.java:363) ~[na:na]
        at org.apache.avro.generic.GenericDatumReader.readString(GenericDatumReader.java:355) ~[na:na]
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:157) ~[na:na]
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:155) ~[na:na]
        at org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:193) ~[na:na]
        at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:183) ~[na:na]
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:151) ~[na:na]
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:142) ~[na:na]
        at io.druid.data.input.avro.InlineSchemaAvroBytesDecoder.parse(InlineSchemaAvroBytesDecoder.java:86) ~[na:na]
        at io.druid.data.input.AvroStreamInputRowParser.parse(AvroStreamInputRowParser.java:53) ~[na:na]
        at io.druid.data.input.AvroStreamInputRowParser.parse(AvroStreamInputRowParser.java:33) ~[na:na]
        at com.metamx.tranquility.druid.DruidBeams$$anonfun$1$$anonfun$7.apply(DruidBeams.scala:182) ~[io.druid.tranquility-core-0.8.2.1.jar:0.8.2.1]
        at com.metamx.tranquility.druid.DruidBeams$$anonfun$1$$anonfun$7.apply(DruidBeams.scala:182) ~[io.druid.tranquility-core-0.8.2.1.jar:0.8.2.1]
        at com.metamx.tranquility.druid.DruidBeams$$anonfun$1$$anonfun$apply$1.apply(DruidBeams.scala:200) ~[io.druid.tranquility-core-0.8.2.1.jar:0.8.2.1]
        at com.metamx.tranquility.druid.DruidBeams$$anonfun$1$$anonfun$apply$1.apply(DruidBeams.scala:200) ~[io.druid.tranquility-core-0.8.2.1.jar:0.8.2.1]
        at com.metamx.tranquility.beam.TransformingBeam$$anonfun$sendAll$2$$anonfun$2.apply(TransformingBeam.scala:36) ~[io.druid.tranquility-core-0.8.2.1.jar:0.8.2.1]
        at com.twitter.util.Try$.apply(Try.scala:13) ~[com.twitter.util-core_2.10-6.30.0.jar:6.30.0]
        at com.metamx.tranquility.beam.TransformingBeam$$anonfun$sendAll$2.apply(TransformingBeam.scala:36) ~[io.druid.tranquility-core-0.8.2.1.jar:0.8.2.1]
        at com.metamx.tranquility.beam.TransformingBeam$$anonfun$sendAll$2.apply(TransformingBeam.scala:35) ~[io.druid.tranquility-core-0.8.2.1.jar:0.8.2.1]
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772) ~[org.scala-lang.scala-library-2.10.5.jar:na]
        at scala.collection.Iterator$class.foreach(Iterator.scala:727) ~[org.scala-lang.scala-library-2.10.5.jar:na]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157) ~[org.scala-lang.scala-library-2.10.5.jar:na]
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[org.scala-lang.scala-library-2.10.5.jar:na]
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[org.scala-lang.scala-library-2.10.5.jar:na]
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771) ~[org.scala-lang.scala-library-2.10.5.jar:na]
        at com.metamx.tranquility.beam.TransformingBeam.sendAll(TransformingBeam.scala:35) ~[io.druid.tranquility-core-0.8.2.1.jar:0.8.2.1]
        at com.metamx.tranquility.tranquilizer.Tranquilizer.com$metamx$tranquility$tranquilizer$Tranquilizer$$sendBuffer(Tranquilizer.scala:301) ~[io.druid.tranquility-core-0.8.2.1.jar:0.8.2.1]
        at com.metamx.tranquility.tranquilizer.Tranquilizer$$anonfun$send$1.apply(Tranquilizer.scala:202) ~[io.druid.tranquility-core-0.8.2.1.jar:0.8.2.1]
        at com.metamx.tranquility.tranquilizer.Tranquilizer$$anonfun$send$1.apply(Tranquilizer.scala:202) ~[io.druid.tranquility-core-0.8.2.1.jar:0.8.2.1]
2017-03-24 00:25:45,050 [KafkaConsumer-3] INFO  c.m.tranquility.kafka.KafkaConsumer - Shutting down - attempting to flush buffers and commit final offsets
2017-03-24 01:15:00,000 [Curator-ServiceCache-0] INFO  c.m.c.s.net.finagle.DiscoResolver - Updating instances for service[firehose:druid:overlord:hbase_metrics2-016-0004-0000] to Set()
2017-03-24 01:15:00,008 [Curator-ServiceCache-0] INFO  c.m.c.s.net.finagle.DiscoResolver - Updating instances for service[firehose:druid:overlord:hbase_metrics2-016-0011-0000] to Set()

```

jmap -heap 29358
```
Attaching to process ID 29358, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 25.121-b13

using thread-local object allocation.
Parallel GC with 23 thread(s)

Heap Configuration:
   MinHeapFreeRatio         = 0
   MaxHeapFreeRatio         = 100
   MaxHeapSize              = 32210157568 (30718.0MB)
   NewSize                  = 704643072 (672.0MB)
   MaxNewSize               = 10736369664 (10239.0MB)
   OldSize                  = 1409286144 (1344.0MB)
   NewRatio                 = 2
   SurvivorRatio            = 8
   MetaspaceSize            = 21807104 (20.796875MB)
   CompressedClassSpaceSize = 1073741824 (1024.0MB)
   MaxMetaspaceSize         = 17592186044415 MB
   G1HeapRegionSize         = 0 (0.0MB)

Heap Usage:
PS Young Generation
Eden Space:
   capacity = 7862222848 (7498.0MB)
   used     = 3139594216 (2994.1503677368164MB)
   free     = 4722628632 (4503.849632263184MB)
   39.93265361078709% used
From Space:
   capacity = 1572864 (1.5MB)
   used     = 1130608 (1.0782318115234375MB)
   free     = 442256 (0.4217681884765625MB)
   71.88212076822917% used
To Space:
   capacity = 1480065024 (1411.5MB)
   used     = 0 (0.0MB)
   free     = 1480065024 (1411.5MB)
   0.0% used
PS Old Generation
   capacity = 21473787904 (20479.0MB)
   used     = 7276967000 (6939.85652923584MB)
   free     = 14196820904 (13539.14347076416MB)
   33.88767288068675% used

10004 interned Strings occupying 877688 bytes.
```

**Comment by asdf2014** [comment]
And the gc situation of them is such terrible.

jstat -gcutil -t 28142 1000
```
Timestamp         S0     S1     E      O      M     CCS    YGC     YGCT    FGC    FGCT     GCT   
       248238.9  50.75   0.00  77.53  25.45  98.42  97.72 249835 68829.134 10410 4343.484 73172.618
       248240.0   0.00   0.06  26.51  25.48  98.42  97.72 249838 68829.557 10410 4343.484 73173.041
       248241.0   0.00   0.06  47.48  25.48  98.42  97.72 249838 68829.557 10410 4343.484 73173.041
       248242.0   0.00   0.06  67.50  25.48  98.42  97.72 249838 68829.557 10410 4343.484 73173.041
       248243.0   0.00   0.06  80.33  25.48  98.42  97.72 249838 68829.557 10410 4343.484 73173.041
       248244.0   0.08   0.00   2.89  25.48  98.42  97.72 249839 68829.576 10410 4343.484 73173.060
       248245.0   0.08   0.00  14.08  25.48  98.42  97.72 249839 68829.576 10410 4343.484 73173.060
       248246.0   0.08   0.00  29.52  25.48  98.42  97.72 249839 68829.576 10410 4343.484 73173.060
       248247.0   0.08   0.00  55.89  25.48  98.42  97.72 249839 68829.576 10410 4343.484 73173.060
       248248.0   0.08   0.00  65.70  25.48  98.42  97.72 249839 68829.576 10410 4343.484 73173.060
       248249.0   0.08   0.00  73.62  25.48  98.42  97.72 249839 68829.576 10410 4343.484 73173.060
       248250.0   0.08   0.00  82.94  25.48  98.42  97.72 249839 68829.576 10410 4343.484 73173.060
       248251.0   0.08   0.00  92.47  25.48  98.42  97.72 249839 68829.576 10410 4343.484 73173.060
       248252.0   0.00   0.04   4.90  25.49  98.42  97.72 249840 68829.593 10410 4343.484 73173.076
       248253.0   0.00   0.04  20.91  25.49  98.42  97.72 249840 68829.593 10410 4343.484 73173.076
       248254.0   0.00   0.04  30.10  25.49  98.42  97.72 249840 68829.593 10410 4343.484 73173.076
       248255.0   0.00   0.04  44.31  25.49  98.42  97.72 249840 68829.593 10410 4343.484 73173.076
       248256.0   0.00   0.04  89.17  25.49  98.42  97.72 249840 68829.593 10410 4343.484 73173.076
       248257.0   0.00   0.04  97.49  25.49  98.42  97.72 249840 68829.593 10410 4343.484 73173.076
       248258.0   0.03   0.00  14.98  25.49  98.42  97.72 249841 68829.611 10410 4343.484 73173.094
       248259.0   0.03   0.00  19.33  25.49  98.42  97.72 249841 68829.611 10410 4343.484 73173.094
       248260.0   0.03   0.00  26.10  25.49  98.42  97.72 249841 68829.611 10410 4343.484 73173.094
       248261.0   0.03   0.00  33.74  25.49  98.42  97.72 249841 68829.611 10410 4343.484 73173.094
       248262.0   0.03   0.00  40.11  25.49  98.42  97.72 249841 68829.611 10410 4343.484 73173.094
       248263.0   0.03   0.00  43.94  25.49  98.42  97.72 249841 68829.611 10410 4343.484 73173.094
       248264.0   0.03   0.00  51.53  25.49  98.42  97.72 249841 68829.611 10410 4343.484 73173.094
       248265.0   0.03   0.00  61.97  25.49  98.42  97.72 249841 68829.611 10410 4343.484 73173.094
       248266.0   0.03   0.00  68.27  25.49  98.42  97.72 249841 68829.611 10410 4343.484 73173.094
       248267.0   0.03   0.00  77.17  25.49  98.42  97.72 249841 68829.611 10410 4343.484 73173.094
       248268.0   0.03   0.00  81.46  25.49  98.42  97.72 249841 68829.611 10410 4343.484 73173.094
       248268.9   0.03   0.00  87.33  25.49  98.42  97.72 249841 68829.611 10410 4343.484 73173.094
       248269.9   0.03   0.00  95.85  25.49  98.42  97.72 249841 68829.611 10410 4343.484 73173.094
       248271.0   0.00   0.25  18.40  25.49  98.42  97.72 249842 68829.627 10410 4343.484 73173.110
       248272.0   0.00   0.25  25.18  25.49  98.42  97.72 249842 68829.627 10410 4343.484 73173.110
       248273.0   0.00   0.25  85.50  25.49  98.42  97.72 249842 68829.627 10410 4343.484 73173.110
       248274.0   0.00   0.25  93.04  25.49  98.42  97.72 249842 68829.627 10410 4343.484 73173.110
       248275.0   0.04   0.00   3.98  25.49  98.42  97.72 249843 68829.639 10410 4343.484 73173.123
       248276.0   0.04   0.00  13.74  25.49  98.42  97.72 249843 68829.639 10410 4343.484 73173.123
       248277.0   0.04   0.00  23.91  25.49  98.42  97.72 249843 68829.639 10410 4343.484 73173.123

```

**Comment by gianm** [comment]
The stack trace looks like you have strings in your avro objects that are really super long.

**Comment by asdf2014** [comment]
Yep, it could be. But the length of string must longer than `Integer.MAX_VALUE-2`. I think it cannot happened in my situation.

**Comment by gianm** [comment]
Is it possible there's some corrupt data or an issue with the avro parser? The stack trace looks like it's more likely one of those two than a problem with druid code.

**Comment by asdf2014** [comment]
Maybe... Is it due to https://github.com/druid-io/druid/pull/4100? There are too many nessnary `EOFException` from `ByteBufferInputStream` in `avro`. That will hurt the performance of `tranquility`. I will fix it in our Druid cluster by adding the patch https://issues.apache.org/jira/secure/attachment/12477556/avro-813-patch.txt.

**Comment by asdf2014** [comment]
@gianm `Tranquility` is totally fine after i add those patches [AVRO-813](https://issues.apache.org/jira/browse/AVRO-813) and https://github.com/druid-io/druid/pull/4092 to fix the `EOFException` problem.

jstat -gcutil -t 27545 1000
```
Timestamp         S0     S1     E      O      M     CCS    YGC     YGCT    FGC    FGCT     GCT   
        55082.4  56.52   0.00  25.88  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55083.4  56.52   0.00  25.90  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55084.4  56.52   0.00  25.90  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55085.4  56.52   0.00  25.90  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55086.4  56.52   0.00  25.96  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55087.4  56.52   0.00  27.00  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55088.4  56.52   0.00  32.46  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55089.4  56.52   0.00  36.39  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55090.4  56.52   0.00  37.92  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55091.4  56.52   0.00  52.91  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55092.4  56.52   0.00  55.03  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55093.4  56.52   0.00  55.03  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55094.4  56.52   0.00  55.30  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55095.4  56.52   0.00  56.00  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55096.4  56.52   0.00  56.77  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55097.4  56.52   0.00  57.52  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55098.4  56.52   0.00  57.53  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55099.4  56.52   0.00  60.59  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55100.4  56.52   0.00  60.59  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55101.4  56.52   0.00  61.15  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55102.4  56.52   0.00  62.79  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55103.4  56.52   0.00  66.72  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55104.4  56.52   0.00  70.26  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55105.4  56.52   0.00  75.26  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55106.4  56.52   0.00  76.63  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55107.4  56.52   0.00  76.63  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55108.4  56.52   0.00  77.38  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
        55109.4  56.52   0.00  77.98  19.54  98.78  98.07   1196    9.725     2    0.077    9.802
```

**Comment by asdf2014** [comment]
Btw, i tuning the `JVM` to increase the capacity of `Eden Space` with those options that `-J-XX:NewSize=12G -J-XX:MaxNewSize=12G` for reducing the performance lose because of copying the large object into `Old Generation` even the `Allocation Failure` problem.

**Comment by asdf2014** [comment]
Btw, i tune the `JVM` of `Tranquility` to increase the capacity of `Eden Space` with those options that `-J-XX:NewSize=12G -J-XX:MaxNewSize=12G` for reducing the performance lose because of copying the large object into `Old Generation` even the `Allocation Failure` problem.
