### ISSUE TITLE
`Unable to close file because the last block does not have enough number of replicas` IOException in `HdfsTaskLogs`

### ISSUE THREAD

**Issue by asdf2014** [druid-io/druid#4140]
Some problems happened in `MiddleManager`...
```
java.lang.OutOfMemoryError: Direct buffer memory
        at java.nio.Bits.reserveMemory(Bits.java:693) ~[?:1.8.0_121]
        at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123) ~[?:1.8.0_121]
        at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311) ~[?:1.8.0_121]
        at sun.nio.ch.Util.getTemporaryDirectBuffer(Util.java:241) ~[?:1.8.0_121]
        at sun.nio.ch.IOUtil.write(IOUtil.java:58) ~[?:1.8.0_121]
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[?:1.8.0_121]
        at org.apache.hadoop.net.SocketOutputStream$Writer.performIO(SocketOutputStream.java:63) ~[hadoop-common-2.4.0.10.jar:?]
        at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:142) ~[hadoop-common-2.4.0.10.jar:?]
        at org.apache.hadoop.net.SocketOutputStream.write(SocketOutputStream.java:159) ~[hadoop-common-2.4.0.10.jar:?]
        at org.apache.hadoop.net.SocketOutputStream.write(SocketOutputStream.java:117) ~[hadoop-common-2.4.0.10.jar:?]
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122) ~[?:1.8.0_121]
        at java.io.DataOutputStream.write(DataOutputStream.java:107) ~[?:1.8.0_121]
        at org.apache.hadoop.hdfs.DFSOutputStream$Packet.writeTo(DFSOutputStream.java:279) ~[hadoop-hdfs-2.4.0.10.jar:?]
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:579) [hadoop-hdfs-2.4.0.10.jar:?]
2017-03-31T15:19:17,434 INFO [forking-task-runner-7] org.apache.hadoop.hdfs.DFSClient:completeFile:2138 - Could not complete /druid/common/indexing-logs/index_realtime_hbase_metrics2_2017-03-31T06_00_00.000Z_0_0 retrying...
2017-03-31T15:19:23,835 INFO [forking-task-runner-7] org.apache.hadoop.hdfs.DFSClient:completeFile:2138 - Could not complete /druid/common/indexing-logs/index_realtime_hbase_metrics2_2017-03-31T06_00_00.000Z_0_0 retrying...
2017-03-31T15:19:36,637 INFO [forking-task-runner-7] io.druid.indexing.overlord.ForkingTaskRunner:info:76 - Exception caught during execution
java.io.IOException: Unable to close file because the last block does not have enough number of replicas.
        at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:2132) ~[?:?]
        at org.apache.hadoop.hdfs.DFSOutputStream.close(DFSOutputStream.java:2100) ~[?:?]
        at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:70) ~[?:?]
        at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:103) ~[?:?]
        at io.druid.storage.hdfs.tasklog.HdfsTaskLogs.pushTaskLog(HdfsTaskLogs.java:68) ~[?:?]
        at io.druid.indexing.overlord.ForkingTaskRunner$1.call(ForkingTaskRunner.java:447) [druid-indexing-service-0.9.2.jar:0.9.2]
        at io.druid.indexing.overlord.ForkingTaskRunner$1.call(ForkingTaskRunner.java:219) [druid-indexing-service-0.9.2.jar:0.9.2]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by asdf2014** [comment]
Is it could due to `FileSystem` didn't close the stream?

`final FileSystem fs = path.getFileSystem(hadoopConfig);`

(https://github.com/druid-io/druid/blob/master/extensions-core/hdfs-storage/src/main/java/io/druid/storage/hdfs/tasklog/HdfsTaskLogs.java#L63)

**Comment by jihoonson** [comment]
Seems you need more memory. The first exception means writing on hdfs failed due to insufficient memory, and it looks to cause the second exception.

**Comment by asdf2014** [comment]
@jihoonson You are right, we are checking the `HDFS`. I close the issues.
