### ISSUE TITLE
Having duplicate entries in metricsSpec causes ArrayIndexOutOfBoundsException during index generation

### ISSUE THREAD

**Issue by dclim** [druid-io/druid#4149]
It would be a nicer user experience if this situation could be validated when the ingestion spec is received and either fail immediately with a more helpful error message or where possible auto de-dupe identical redundant fields.

```
Error: java.lang.ArrayIndexOutOfBoundsException: 198
at io.druid.segment.IndexMerger$13.apply(IndexMerger.java:968)
at io.druid.segment.IndexMerger$13.apply(IndexMerger.java:945)
at com.google.common.collect.Iterators$8.transform(Iterators.java:794)
at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
at com.google.common.collect.Iterators$PeekingImpl.next(Iterators.java:1145)
at com.metamx.common.guava.MergeIterator.next(MergeIterator.java:75)
at io.druid.segment.IndexMerger.makeIndexFiles(IndexMerger.java:762)
at io.druid.segment.IndexMerger.merge(IndexMerger.java:438)
at io.druid.segment.IndexMerger.persist(IndexMerger.java:186)
at io.druid.indexer.IndexGeneratorJob$IndexGeneratorReducer.persist(IndexGeneratorJob.java:510)
at io.druid.indexer.IndexGeneratorJob$IndexGeneratorReducer.reduce(IndexGeneratorJob.java:684)
at io.druid.indexer.IndexGeneratorJob$IndexGeneratorReducer.reduce(IndexGeneratorJob.java:478)
at org.apache.hadoop.mapreduce.Reducer.run(Reducer.java:171)
at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:627)
at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:389)
at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:422)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1693)
at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
```

**Comment by gianm** [comment]
Fixed in #3917
