### ISSUE TITLE
Why druid can't ingest data from another HDFS cluster which is not used as its deep storage?

### ISSUE THREAD

**Issue by elloooooo** [druid-io/druid#4150]

**Comment by b-slim** [comment]
It certainly can if the hadoop tasks executors will be able to read this data. You can point to that data via `inputSpec` that is part of `IoConfig`

**Comment by b-slim** [comment]
you need to provide the full URI like `hdfs://nn1.example.com/file1`.

**Comment by elloooooo** [comment]
@b-slim Thank you very much. I will try it.

**Comment by elloooooo** [comment]
@b-slim when I provide the full URI like hdfs://mycluster-tj/XXX/XXX, I got the the exception below:

> Caused by: java.lang.IllegalArgumentException: java.net.UnknownHostException: mycluster-tj
	at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:377) ~[?:?]
	at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:237) ~[?:?]
	at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:141) ~[?:?]
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:569) ~[?:?]
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:512) ~[?:?]
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:142) ~[?:?]
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2316) ~[?:?]
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:90) ~[?:?]
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2350) ~[?:?]
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2332) ~[?:?]
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:369) ~[?:?]
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:296) ~[?:?]
	at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.setInputPaths(FileInputFormat.java:446) ~[?:?]
	at org.apache.hadoop.mapreduce.lib.input.DelegatingInputFormat.getSplits(DelegatingInputFormat.java:110) ~[?:?]
	at org.apache.hadoop.mapreduce.JobSubmitter.writeNewSplits(JobSubmitter.java:493) ~[?:?]
	at org.apache.hadoop.mapreduce.JobSubmitter.writeSplits(JobSubmitter.java:510) ~[?:?]
	at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:394) ~[?:?]
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1285) ~[?:?]
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1282) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_65]
	at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_65]
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548) ~[?:?]
	at org.apache.hadoop.mapreduce.Job.submit(Job.java:1282) ~[?:?]
	at io.druid.indexer.DetermineHashedPartitionsJob.run(DetermineHashedPartitionsJob.java:116) ~[druid-indexing-hadoop-0.9.2.jar:0.9.2]
	at io.druid.indexer.JobHelper.runJobs(JobHelper.java:349) ~[druid-indexing-hadoop-0.9.2.jar:0.9.2]
	at io.druid.indexer.HadoopDruidDetermineConfigurationJob.run(HadoopDruidDetermineConfigurationJob.java:91) ~[druid-indexing-hadoop-0.9.2.jar:0.9.2]
	at io.druid.indexing.common.task.HadoopIndexTask$HadoopDetermineConfigInnerProcessing.runTask(HadoopIndexTask.java:291) ~[druid-indexing-service-0.9.2.jar:0.9.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_65]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:201) ~[druid-indexing-service-0.9.2.jar:0.9.2]
	... 7 more

Do I miss something? I think there must be somewhere I should provide the core-site.xml and hdfs-site.xml to let druid know what the "mycluster-tj" means and where to get data from.

**Comment by b-slim** [comment]
is `mycluster-tj` a fully qualified domain name ?  can you try to use the ip address instead  ? 
to debug this you can try from one of the nodes `hdfs dfs -ls  hdfs://mycluster-tj/XXX/XXX`

**Comment by elloooooo** [comment]
Thank you for your replay. After I use the ip instead the namespace(mycluster-tj), the MapReduce job works.
