### ISSUE TITLE
maven test fails with timeout error

### ISSUE THREAD

**Issue by knoguchi** [druid-io/druid#4152]
The maven test failed for me.  It could be very well my environment, but I'm seeing this error.   BlockingPoolTest was added in Feb 2017.   Can we [increase the timeout](https://github.com/druid-io/druid/blame/7200dce112d8f69f3f59d16b2b8290d69459aa5e/common/src/test/java/io/druid/collections/BlockingPoolTest.java#L103) unless the 1000 milli sec is the hard requirement?

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.druid.collections.BlockingPoolTest
Tests run: 11, Failures: 5, Errors: 3, Skipped: 0, Time elapsed: 1.812 sec <<< FAILURE! - in io.druid.collections.BlockingPoolTest
testWaitAndTakeBatch(io.druid.collections.BlockingPoolTest)  Time elapsed: 1.011 sec  <<< ERROR!
java.lang.Exception: test timed out after 1000 milliseconds
	at io.druid.collections.BlockingPoolTest.testWaitAndTakeBatch(BlockingPoolTest.java:106)

testConcurrentTakeBatchClose(io.druid.collections.BlockingPoolTest)  Time elapsed: 0.116 sec  <<< ERROR!
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at io.druid.collections.BlockingPoolTest.testConcurrentTakeBatchClose(BlockingPoolTest.java:364)
Caused by: java.lang.NullPointerException

testConcurrentTakeBatch(io.druid.collections.BlockingPoolTest)  Time elapsed: 0.014 sec  <<< FAILURE!
java.lang.AssertionError
	at io.druid.collections.BlockingPoolTest.testConcurrentTakeBatch(BlockingPoolTest.java:263)

testTake(io.druid.collections.BlockingPoolTest)  Time elapsed: 0.106 sec  <<< FAILURE!
java.lang.AssertionError
	at io.druid.collections.BlockingPoolTest.testTake(BlockingPoolTest.java:77)

testTakeTimeout(io.druid.collections.BlockingPoolTest)  Time elapsed: 0.211 sec  <<< ERROR!
java.lang.NullPointerException
	at io.druid.collections.BlockingPoolTest.testTakeTimeout(BlockingPoolTest.java:89)

testConcurrentTake(io.druid.collections.BlockingPoolTest)  Time elapsed: 0.075 sec  <<< FAILURE!
java.lang.AssertionError: expected:<10> but was:<0>
	at io.druid.collections.BlockingPoolTest.testConcurrentTake(BlockingPoolTest.java:193)

testConcurrentBatchClose(io.druid.collections.BlockingPoolTest)  Time elapsed: 0.012 sec  <<< FAILURE!
java.lang.AssertionError
	at io.druid.collections.BlockingPoolTest.testConcurrentBatchClose(BlockingPoolTest.java:303)

testTakeBatch(io.druid.collections.BlockingPoolTest)  Time elapsed: 0.107 sec  <<< FAILURE!
java.lang.AssertionError
	at io.druid.collections.BlockingPoolTest.testTakeBatch(BlockingPoolTest.java:96)
```

**Comment by knoguchi** [comment]
It was actually log4j taking up the time trying to lookup DNS for non existing host name.  
I added /etc/hosts entry for the host.  Now the test finishes in 0.6sec.

I don't know the solution but it'd be great if we could segregate the tests from the environment. 

```
java.lang.Exception: test timed out after 1000 milliseconds

	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
	at org.apache.logging.log4j.core.util.NetUtils.getLocalHostname(NetUtils.java:53)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:486)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:562)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:578)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:214)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:145)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:182)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:103)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:42)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:253)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:265)
	at io.druid.java.util.common.logger.Logger.<init>(Logger.java:38)
	at io.druid.collections.ReferenceCountingResourceHolder.<clinit>(ReferenceCountingResourceHolder.java:35)
	at io.druid.collections.BlockingPool.takeBatch(BlockingPool.java:171)
	at io.druid.collections.BlockingPoolTest.testWaitAndTakeBatch(BlockingPoolTest.java:106)
```

**Comment by knoguchi** [comment]
log4j web page said:
> Note that if your /etc/hosts file does not include an entry for your computer’s hostname, then many unit tests may execute slowly due to DNS lookups to translate your hostname to an IP address in InetAddress::getLocalHost. To remedy this, you can execute the following:
>
> printf '127.0.0.1 %s\n::1 %s\n' `hostname` `hostname` | sudo tee -a /etc/hosts
