### ISSUE TITLE
0.10.0 : Kafka indexing : can not combine streams for version v2

### ISSUE THREAD

**Issue by arpankhagram** [druid-io/druid#4183]
Hi Team,

We upgraded to 0.10.0 version today and have been facing issues with one of the Kafka supervisor job

We tried to looks at the code but haven't been able to figure out anything yet.

Please note we upgraded Kafka broker as well from 0.10.0.1 to 0.10.2.0 as well.

Would be good if you can have a look at this once and guide urgently. Thanks in advance.

2017-04-19T10:24:45,369 WARN [appenderator_merge_0] io.druid.segment.realtime.appenderator.AppenderatorImpl - Failed to push merged index f

or segment[SEGMENT_2017-04-18T12:00:00.000Z_2017-04-18T13:00:00.000Z_2017-04-18T21:30:40.086Z_10].

io.druid.java.util.common.ISE: Can not combine streams for version 2.

        at io.druid.segment.data.GenericIndexedWriter.combineStreams(GenericIndexedWriter.java:327) ~[druid-processing-0.10.0.jar:0.10.0]

        at io.druid.segment.StringDimensionMergerV9.writeIndexes(StringDimensionMergerV9.java:290) ~[druid-processing-0.10.0.jar:0.10.0]

        at io.druid.segment.IndexMergerV9.makeIndexFiles(IndexMergerV9.java:219) ~[druid-processing-0.10.0.jar:0.10.0]

        at io.druid.segment.IndexMerger.merge(IndexMerger.java:437) ~[druid-processing-0.10.0.jar:0.10.0]

        at io.druid.segment.IndexMerger.mergeQueryableIndex(IndexMerger.java:241) ~[druid-processing-0.10.0.jar:0.10.0]

        at io.druid.segment.IndexMerger.mergeQueryableIndex(IndexMerger.java:213) ~[druid-processing-0.10.0.jar:0.10.0]

        at io.druid.segment.realtime.appenderator.AppenderatorImpl.mergeAndPush(AppenderatorImpl.java:565) [druid-server-0.10.0.jar:0.10.0]

        at io.druid.segment.realtime.appenderator.AppenderatorImpl.access$600(AppenderatorImpl.java:95) [druid-server-0.10.0.jar:0.10.0]

        at io.druid.segment.realtime.appenderator.AppenderatorImpl$3.apply(AppenderatorImpl.java:471) [druid-server-0.10.0.jar:0.10.0]

        at io.druid.segment.realtime.appenderator.AppenderatorImpl$3.apply(AppenderatorImpl.java:459) [druid-server-0.10.0.jar:0.10.0]

        at com.google.common.util.concurrent.Futures$1.apply(Futures.java:713) [guava-16.0.1.jar:?]

        at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:861) [guava-16.0.1.jar:?]

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]

        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

2017-04-19T10:24:45,422 WARN [task-runner-0-priority-0] io.druid.segment.realtime.appenderator.FiniteAppenderatorDriver - Failed publishAll (try 1), retrying in 1,687ms.

java.util.concurrent.ExecutionException: io.druid.java.util.common.ISE: Can not combine streams for version 2.

        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299) ~[guava-16.0.1.jar:?]

        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286) ~[guava-16.0.1.jar:?]

        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116) ~[guava-16.0.1.jar:?]

        at io.druid.segment.realtime.appenderator.FiniteAppenderatorDriver.publishAll(FiniteAppenderatorDriver.java:423) [druid-server-0.10.0.jar:0.10.0]

        at io.druid.segment.realtime.appenderator.FiniteAppenderatorDriver.finish(FiniteAppenderatorDriver.java:262) [druid-server-0.10.0.jar:0.10.0]

        at io.druid.indexing.kafka.KafkaIndexTask.run(KafkaIndexTask.java:515) [druid-kafka-indexing-service-0.10.0.jar:0.10.0]

        at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:436) [druid-indexing-service-0.10.0.jar:0.10.0]

        at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:408) [druid-indexing-service-0.10.0.jar:0.10.0]

**Comment by gianm** [comment]
Looks probably related to the large column code path from #3743. @akashdw, @cheddar, any ideas?

@arpankhagram, the large column code path should only get activated if a single column is >2GB. In this case it looks like it's a file for one of your string columns. You might be able to work around this by lowering maxRowsPerSegment in your tuningConfig.

Fwiw, in 0.9.2 trying to write a large string column would have failed too, with a different error: columns >2GB weren't supported at all. I'm surprised you only saw this after upgrading. Maybe something else happened to trigger a really large column getting generated. Perhaps just having the system stopped for a while led to a data backlog that led to large segments.

At any rate -- I'd suggest try lowering maxRowsPerSegment and see if that helps.

**Comment by arpankhagram** [comment]
@gianm Thanks for replying.

We were using 0.10-snapahot (taken on 23rd March) until now and it looks to have broke after Kafka upgrade to 0.10.2.0.

Yes we are having very large columns - anyways I shall try with lowering maxRowsPerSegment and let you know if that works fine.

Looks nobody have received this error earlier - I tried searching in forums.

Thanks.

**Comment by arpankhagram** [comment]
Hi @gianm It has worked after changing the maxRowsPerSegment parameter as part of Kafka indexing service.

Thanks for your support.

Regards,
Arpan Khagram
