### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by rahulsingh303** [druid-io/druid#4186]
I am getting this error when I try starting druid services 
command : java `cat conf-quickstart/druid/historical/jvm.config | xargs` -cp "conf-quickstart/druid/_common:conf-quickstart/druid/historical:lib/*" io.druid.cli.Main server historical

error:
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/druid/cli/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

My versions are : 
Druid version = druid-0.10.0
JDK Version = jdk1.8.0_131
Zookeeper version = zookeeper-3.4.6
Linux version : 3.8.13-118.8.1.el6uek.x86_64

Please let me know if someone can help.

-Rahul

**Comment by erikdubbelboer** [comment]
This means you are trying to run druid on java 1.7 which is not supported anymore.

**Comment by hack-r** [comment]
Yes I got this error and I was using Java 1.7. Thanks. What version do we need, 1.8?

**Comment by windbender** [comment]
seems closable.... ?
