### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by rahulsingh303** [druid-io/druid#4190]
Hi,

When I try to start  middleManager service , using below command , I get this error : 

**Command :** 
java `cat conf-quickstart/druid/middleManager/jvm.config | xargs` -cp "conf-quickstart/druid/_common:conf-quickstart/druid/middleManager:lib/*" io.druid.cli.Main server middleManager

**Error :** 
2017-04-20T21:49:41,648 ERROR [main] io.druid.cli.CliMiddleManager - Error when starting up.  Failing.
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_121]
        at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_121]
        at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_121]
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_121]
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_121]
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:317) ~[jetty-server-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[jetty-server-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235) ~[jetty-server-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.server.Server.doStart(Server.java:401) ~[jetty-server-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.3.16.v20170120.jar:9.3.16.v20170120]
        at io.druid.server.initialization.jetty.JettyServerModule$1.start(JettyServerModule.java:206) ~[druid-server-0.10.0.jar:0.10.0]
        at io.druid.java.util.common.lifecycle.Lifecycle.start(Lifecycle.java:263) ~[java-util-0.10.0.jar:0.10.0]
        at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:156) ~[druid-api-0.10.0.jar:0.10.0]
        at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:102) [druid-services-0.10.0.jar:0.10.0]
        at io.druid.cli.ServerRunnable.run(ServerRunnable.java:41) [druid-services-0.10.0.jar:0.10.0]
        at io.druid.cli.Main.main(Main.java:108) [druid-services-0.10.0.jar:0.10.0]

I am not sure which port it is trying to use , so that I can stop the process .

Please help.

**Comment by rahulsingh303** [comment]
I found the port used was 8091 , it's in conf file for middleManager , I changed it to 8092 and service started fine .

-Rahul
