### ISSUE TITLE
Compatibility issue with aws-java-sdk:1.10.77 and httpclient:4.5.3

### ISSUE THREAD

**Issue by dclim** [druid-io/druid#4456]
Calls to com.amazonaws.http.AmazonHttpClient.execute() may fail with the following exception:

```
java.lang.IllegalStateException: Socket not created by this factory
	at org.apache.http.util.Asserts.check(Asserts.java:34) ~[httpcore-4.4.6.jar:4.4.6]
	at org.apache.http.conn.ssl.SSLSocketFactory.isSecure(SSLSocketFactory.java:435) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:186) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.3.jar:4.5.3]
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:837) ~[aws-java-sdk-core-1.10.77.jar:?]
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607) ~[aws-java-sdk-core-1.10.77.jar:?]
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376) ~[aws-java-sdk-core-1.10.77.jar:?]
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338) ~[aws-java-sdk-core-1.10.77.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287) ~[aws-java-sdk-core-1.10.77.jar:?]
```

I'm seeing issues with the aws-java-sdk in one of our extensions and believe that it might affect the S3 extension as well. I haven't yet seen any issues in S3, but it uses similar method calls so the version bump might have introduced lurking issues. The aws-java-sdk extends `SSLSocketFactory` as `SdkTLSSocketFactory`, and when the factory is asked to create a socket and calls into the incompatible httpclient, it returns a standard `Socket` instead of an `SSLSocket` which causes the assertion in `isSecure` to fail.

Similar issues between aws-java-sdk and httpclient have been reported by others:
  - https://groups.google.com/forum/#!topic/dropwizard-user/5-zjo5N32Tg
  - https://github.com/aws/aws-sdk-java/issues/1032

I'd like to revert to httpclient:4.5.1 and httpcore:4.4.3 unless there's a particular reason these need to be upgraded.

**Comment by tralfredochua** [comment]
WORKS LIKE A CHARM!!!!!!!!! :* :* :* :*
