### ISSUE TITLE
SQL:Druid (0.10.0) failed during the run of the sql

### ISSUE THREAD

**Issue by JingJunShen** [druid-io/druid#4652]
```
Exception in thread "main" org.apache.calcite.avatica.AvaticaSqlException: Error -1 (00000) : Error while executing SQL "SELECT event_day AS eventDay,SUM(new_user_nums) AS dayNewUser,SUM(week_new_user_nums) AS weekNewUser,SUM(month_new_user_nums) AS monthNewUser FROM bi_overview_day_fact_new WHERE 1 = 1 AND __time >= TIMESTAMP '2017-06-07 00:00:00.0' AND __time <= TIMESTAMP '2017-08-05 00:00:00.0' AND appid = '110003' GROUP BY event_day ORDER BY event_day": Remote driver error: IAE: Cannot add row[MapBasedInputRow{timestamp=2017-06-06T00:00:00.000Z, event={d0=20170701, a0=48152, a1=255681, a2=792503}, dimensions=[d0]}] because it is below the minTimestamp[2017-06-07T00:00:00.000Z]
	at org.apache.calcite.avatica.Helper.createException(Helper.java:53)
	at org.apache.calcite.avatica.Helper.createException(Helper.java:41)
	at org.apache.calcite.avatica.AvaticaStatement.executeInternal(AvaticaStatement.java:156)
	at org.apache.calcite.avatica.AvaticaStatement.executeQuery(AvaticaStatement.java:218)
	at com.company.App.main(App.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
io.druid.java.util.common.IAE: Cannot add row[MapBasedInputRow{timestamp=2017-06-06T00:00:00.000Z, event={d0=20170701, a0=48152, a1=255681, a2=792503}, dimensions=[d0]}] because it is below the minTimestamp[2017-06-07T00:00:00.000Z]
	at io.druid.segment.incremental.IncrementalIndex.toTimeAndDims(IncrementalIndex.java:402)
	at io.druid.segment.incremental.IncrementalIndex.add(IncrementalIndex.java:382)
	at io.druid.query.groupby.GroupByQueryHelper$3.accumulate(GroupByQueryHelper.java:150)
	at io.druid.query.groupby.GroupByQueryHelper$3.accumulate(GroupByQueryHelper.java:142)
	at io.druid.java.util.common.guava.YieldingAccumulators$1.accumulate(YieldingAccumulators.java:35)
	at io.druid.java.util.common.guava.MergeSequence.makeYielder(MergeSequence.java:111)
	at io.druid.java.util.common.guava.MergeSequence.toYielder(MergeSequence.java:99)
	at io.druid.java.util.common.guava.LazySequence.toYielder(LazySequence.java:46)
	at io.druid.query.RetryQueryRunner$1.toYielder(RetryQueryRunner.java:108)
	at io.druid.java.util.common.guava.YieldingSequenceBase.accumulate(YieldingSequenceBase.java:32)
	at io.druid.query.groupby.GroupByQueryHelper.makeIncrementalIndex(GroupByQueryHelper.java:206)
	at io.druid.query.groupby.strategy.GroupByStrategyV1.mergeResults(GroupByStrategyV1.java:117)
	at io.druid.query.groupby.GroupByQueryQueryToolChest.mergeGroupByResults(GroupByQueryQueryToolChest.java:210)
	at io.druid.query.groupby.GroupByQueryQueryToolChest.initAndMergeGroupByResults(GroupByQueryQueryToolChest.java:134)
	at io.druid.query.groupby.GroupByQueryQueryToolChest.access$100(GroupByQueryQueryToolChest.java:74)
	at io.druid.query.groupby.GroupByQueryQueryToolChest$3.run(GroupByQueryQueryToolChest.java:113)
	at io.druid.query.FinalizeResultsQueryRunner.run(FinalizeResultsQueryRunner.java:103)
	at io.druid.query.CPUTimeMetricQueryRunner.run(CPUTimeMetricQueryRunner.java:68)
	at io.druid.query.FluentQueryRunnerBuilder$FluentQueryRunner.run(FluentQueryRunnerBuilder.java:58)
	at io.druid.query.BaseQuery.run(BaseQuery.java:151)
	at io.druid.query.BaseQuery.run(BaseQuery.java:146)
	at io.druid.sql.calcite.rel.QueryMaker.executeGroupBy(QueryMaker.java:338)
	at io.druid.sql.calcite.rel.QueryMaker.runQuery(QueryMaker.java:133)
	at io.druid.sql.calcite.rel.DruidQueryRel.runQuery(DruidQueryRel.java:168)
	at io.druid.sql.calcite.planner.DruidPlanner$1.get(DruidPlanner.java:127)
	at io.druid.sql.calcite.planner.DruidPlanner$1.get(DruidPlanner.java:122)
	at io.druid.sql.calcite.planner.PlannerResult.run(PlannerResult.java:46)
	at io.druid.sql.avatica.DruidStatement.execute(DruidStatement.java:156)
	at io.druid.sql.avatica.DruidMeta.prepareAndExecute(DruidMeta.java:193)
	at org.apache.calcite.avatica.remote.LocalService.apply(LocalService.java:219)
	at org.apache.calcite.avatica.remote.Service$PrepareAndExecuteRequest.accept(Service.java:928)
	at org.apache.calcite.avatica.remote.Service$PrepareAndExecuteRequest.accept(Service.java:880)
	at org.apache.calcite.avatica.remote.AbstractHandler.apply(AbstractHandler.java:95)
	at org.apache.calcite.avatica.remote.JsonHandler.apply(JsonHandler.java:52)
	at org.apache.calcite.avatica.server.AvaticaJsonHandler.handle(AvaticaJsonHandler.java:129)
	at io.druid.sql.avatica.DruidAvaticaHandler.handle(DruidAvaticaHandler.java:63)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by thomask** [comment]
How did you fix this?

**Comment by gianm** [comment]
I bet this could be fixed by switching to groupBy v2 (which is the default now anyway)

**Comment by thomask** [comment]
Yeah, we actually switched back to v1 because we couldn't get v2 to perform. Would you mind taking a look at our config? If so, what would be the appropriate channel?

**Comment by gianm** [comment]
Could you please elaborate a bit about what kinds of queries you can't get good performance using v2?

groupBy v1 had a bunch of shortcomings due to its use of IncrementalIndex (in fact, in the unit tests, a number of them are disabled for v1 since they can't pass). It's possible this issue is another of those problems with v1. And v2 is faster in all the tests we had done while developing it. So if you have a case where v2 is slower than v1, I'd like to understand it and improve v2.

**Comment by thomask** [comment]
I think it's primarily not being able to cache on the broker. We use mMemcached and see huge differences in query times (sub-second vs +30s) between v1 with broker cache and v2 without

**Comment by thomask** [comment]
If it helps: We run a very small cluster with only 3-6 historical nodes (r3.large).

**Comment by thomask** [comment]
Okay, as it turned out, broker caching was masking a whole different issue. We had 30k+ segments which was the root cause of the slowness. We turned on `druid.coordinator.merge.on` and everything was automagically resolved.

**Comment by gianm** [comment]
@thomask thanks for getting back to us about that!
