### ISSUE TITLE
null pointer exception when IDEA 2017.2 generate ANTLR code 

### ISSUE THREAD

**Issue by PamodLen** [druid-io/druid#4748]
my IDEA version is IntelliJ IDEA 2017.2
java.version: 1.8.0_51-b16
the plugin version is 1.8.4

When i generate druid  ANTLR code(https://github.com/druid-io/druid/blob/master/common/src/main/antlr4/io/druid/math/expr/antlr/Expr.g4)

the "Tool output" should show:
error(31):  ANTLR cannot generate java code as of version 4.7
2017-09-03 18:33:11: antlr4 java.lang.NullPointerException
	at org.antlr.v4.analysis.LeftRecursiveRuleAnalyzer.getArtificialOpPrecRule(LeftRecursiveRuleAnalyzer.java:211)
	at org.antlr.v4.analysis.LeftRecursiveRuleTransformer.translateLeftRecursiveRule(LeftRecursiveRuleTransformer.java:116)
	at org.antlr.v4.analysis.LeftRecursiveRuleTransformer.translateLeftRecursiveRules(LeftRecursiveRuleTransformer.java:71)
	at org.antlr.v4.semantics.SemanticPipeline.process(SemanticPipeline.java:71)
	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:375)
	at org.antlr.v4.Tool.process(Tool.java:362)
	at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:321)
	at org.antlr.intellij.plugin.parsing.RunANTLROnGrammarFile.antlr(RunANTLROnGrammarFile.java:145)
	at org.antlr.intellij.plugin.parsing.RunANTLROnGrammarFile.run(RunANTLROnGrammarFile.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:602)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:342)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by PamodLen** [comment]
change eclipse generate success.

**Comment by dyanarose** [comment]
though closed because the reporter changed to eclipse, I thought I'd post a cause and solution to this issue when using IntelliJ.

The problem is noted on this line of the error logging:
`error(31): ANTLR cannot generate java code as of version 4.7`

the ANTLR v4 grammar plugin, version 1.8.4, runs ANTLR version 4.7. Druid's ANTLR looks to be 4.5.1

in order to compile ANTLR 4.5.1, you need to download ANTLR v4 grammar plugin version 1.7 and install it from disk.
