### ISSUE TITLE
一个莫名其妙的错误

### ISSUE THREAD

**Issue by jounzhang** [druid-io/druid#4763]
2017-09-08 15:14:21:168 ERROR [com.jfinal.core.Config.startPlugins] - <Plugin start error: com.jfinal.plugin.activerecord.ActiveRecordPlugin. 
java.lang.ClassCastException: java.util.Collections$SynchronizedMap cannot be cast to java.util.IdentityHashMap>
com.jfinal.plugin.activerecord.ActiveRecordException: java.lang.ClassCastException: java.util.Collections$SynchronizedMap cannot be cast to java.util.IdentityHashMap
	at com.jfinal.plugin.activerecord.TableBuilder.build(TableBuilder.java:54)
	at com.jfinal.plugin.activerecord.ActiveRecordPlugin.start(ActiveRecordPlugin.java:225)
	at com.jfinal.core.Config.startPlugins(Config.java:88)
	at com.jfinal.core.Config.configJFinal(Config.java:49)
	at com.jfinal.core.JFinal.init(JFinal.java:62)
	at com.jfinal.core.JFinalFilter.init(JFinalFilter.java:49)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4958)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5652)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1092)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1984)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: java.util.Collections$SynchronizedMap cannot be cast to java.util.IdentityHashMap
	at com.alibaba.druid.stat.DruidDataSourceStatManager.getInstances0(DruidDataSourceStatManager.java:113)
	at com.alibaba.druid.stat.DruidDataSourceStatManager.getInstances(DruidDataSourceStatManager.java:92)
	at com.alibaba.druid.stat.DruidDataSourceStatManager.addDataSource(DruidDataSourceStatManager.java:130)
	at com.alibaba.druid.pool.DruidDataSource$1.run(DruidDataSource.java:1411)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.alibaba.druid.pool.DruidDataSource.registerMbean(DruidDataSource.java:1407)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:671)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:951)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:947)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:102)
	at com.jfinal.plugin.activerecord.TableBuilder.build(TableBuilder.java:42)
	... 21 more

**Comment by jounzhang** [comment]
升级到1.1.3后，该问题自动恢复正常了。什么情况这是。。。

**Comment by chitin** [comment]
You should discuss the problem in https://github.com/alibaba/druid.
