### ISSUE TITLE
Problem with GET on /druid/indexer/v1/supervisor

### ISSUE THREAD

**Issue by pjain1** [druid-io/druid#4813]
```
2017-09-16T17:10:52,782 WARN [qtp883035926-144] org.eclipse.jetty.servlet.ServletHandler - /druid/indexer/v1/supervisor
io.druid.java.util.common.ISE: Request already had authorization check.
        at io.druid.server.security.AuthorizationUtils.authorizeAllResourceActions(AuthorizationUtils.java:135) ~[druid-server-0.11.0-1505579318-d980451-48.jar:0.11.0-1505579318-d980451-48]
        at io.druid.indexing.overlord.supervisor.SupervisorResource$2.apply(SupervisorResource.java:127) ~[druid-indexing-service-0.11.0-1505579318-d980451-48.jar:0.11.0-1505579318-d980451-48]
        at io.druid.indexing.overlord.supervisor.SupervisorResource$2.apply(SupervisorResource.java:118) ~[druid-indexing-service-0.11.0-1505579318-d980451-48.jar:0.11.0-1505579318-d980451-48]
        at io.druid.indexing.overlord.supervisor.SupervisorResource.asLeaderWithSupervisorManager(SupervisorResource.java:334) ~[druid-indexing-service-0.11.0-1505579318-d980451-48.jar:0.11.0-1505579318-d980451-48]
        at io.druid.indexing.overlord.supervisor.SupervisorResource.specGetAll(SupervisorResource.java:116) ~[druid-indexing-service-0.11.0-1505579318-d980451-48.jar:0.11.0-1505579318-d980451-48]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
```

Following exception gets thrown while getting information for multiple supervisors from the endpoint `/druid/indexer/v1/supervisor`. If there are multiple supervisors then `AuthorizationUtils.authorizeAllResourceActions` will be called for them in loop [here](https://github.com/druid-io/druid/blob/master/indexing-service/src/main/java/io/druid/indexing/overlord/supervisor/SupervisorResource.java#L124), when the method is called first time for first supervisor then it will set the `request` attribute `AuthConfig.DRUID_AUTHORIZATION_CHECKED` [here](https://github.com/druid-io/druid/blob/master/server/src/main/java/io/druid/server/security/AuthorizationUtils.java#L151) and therefore from next call for remaining supervisors, above mentioned exception will be thrown.

@jon-wei Can you please check ?

**Comment by jon-wei** [comment]
@pjain1 Thanks for reporting, made a PR that removes that check https://github.com/druid-io/druid/pull/4816

**Comment by pjain1** [comment]
@jon-wei thanks for taking a look. I think I found one more issue -
`HttpClientProvider` in the `JettyHttpClientModule` does not have method to create escalated clients. Is this OK or need to be fixed ?

**Comment by jon-wei** [comment]
The client escalation for JettyHttpClient (only used in the Router) is handled in AsyncQueryForwardingServlet instead
