### ISSUE TITLE
RemoteTaskRunner java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by hexian55** [druid-io/druid#5000]
druid version:0.10.0

ERROR i.d.j.u.c.c.ScheduledExecutors [RemoteTaskRunner-Scheduled-Cleanup--0] Uncaught exception.
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[?:1.8.0_31]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1453) ~[?:1.8.0_31]
        at io.druid.indexing.overlord.RemoteTaskRunner$8.run(RemoteTaskRunner.java:1088) ~[druid-indexing-service-0.10.0.jar:0.10.0]
        at io.druid.java.util.common.concurrent.ScheduledExecutors$3.call(ScheduledExecutors.java:143) ~[java-util-0.10.0.jar:0.10.0]
        at io.druid.java.util.common.concurrent.ScheduledExecutors$3.call(ScheduledExecutors.java:139) ~[java-util-0.10.0.jar:0.10.0]
at io.druid.java.util.common.concurrent.ScheduledExecutors$4.run(ScheduledExecutors.java:176) [java-util-0.10.0.jar:0.10.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_31]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_31]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_31]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_31]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_31]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_31]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_31]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_31]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]

**Comment by hexian55** [comment]
fix in 0.10.1
