### ISSUE TITLE
druid-google-extensions, ClassNotFoundException: PrefetchableTextFilesFirehoseFactory

### ISSUE THREAD

**Issue by stingerpk** [druid-io/druid#5021]
Hey Guys

I am building a druid docker image with druid-google-extensions baked in. I have added druid-google-extensions to my Druid image using the following:

```
WORKDIR /usr/local/druid
  
RUN java \
  -cp "lib/*" \
  -Ddruid.extensions.directory="extensions" \
  -Ddruid.extensions.hadoopDependenciesDir="hadoop-dependencies" \
  io.druid.cli.Main tools pull-deps \
  --no-default-hadoop \
  -c "io.druid.extensions.contrib:druid-google-extensions:0.10.1"
```

I have druid-google-extensions in my druid.extensions.loadList passed as an argument in the server start command. When I start the container, the following errors are thrown out:

```
... 18 more
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
Caused by: java.lang.ClassNotFoundException: io.druid.data.input.impl.PrefetchableTextFilesFirehoseFactory
at io.druid.cli.Main.main(Main.java:116)
at io.druid.cli.ServerRunnable.run(ServerRunnable.java:49)
at io.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:62)
at io.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:398)
at io.druid.initialization.Initialization$ModuleList.addModule(Initialization.java:433)
at io.druid.initialization.Initialization$ModuleList.registerJacksonModules(Initialization.java:476)
at io.druid.storage.google.GoogleStorageDruidModule.getJacksonModules(GoogleStorageDruidModule.java:59)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
at java.lang.ClassLoader.defineClass1(Native Method)
Exception in thread "main" java.lang.NoClassDefFoundError: io/druid/data/input/impl/PrefetchableTextFilesFirehoseFactory
```

I do see that there have been some [recent refactoring](https://github.com/druid-io/druid/commit/8d9902831ef344b9c4c29f5d9d07e69e37edd706) related to `PrefetchableTextFilesFirehoseFactory`. The latest version available in [maven repository](https://mvnrepository.com/artifact/io.druid.extensions.contrib/druid-google-extensions) is 0.10.1 which still refers to old path for the class. Any idea of when the new version will make its way into the repository?

**Comment by stingerpk** [comment]
I faced the problem due to version mismatch. Using the corresponding druid version solves the problem.
