### ISSUE TITLE
Command Line Hadoop Indexer 0.11rc2 and Curator

### ISSUE THREAD

**Issue by klamouri** [druid-io/druid#5125]
Hi all,

I'm testing out Druid 0.11.0rc2 in order to upgrade asap to it asap in my organization.

We ingest the batch pipeline every hour in our Druid Cluster.

We use the Command Line Hadoop Indexer for this purpose, however with Druid 0.11.0rc2 I get the following exception (When I didn't have it on 0.10.1).

I suspected a dependency issue so turned on the class verbose on Java but all the curator and zookeeper related classes are coming from one of those jar:

- lib/curator-framework-4.0.0.jar
- lib/curator-client-4.0.0.jar
- lib/druid-server-0.11.0-rc2.jar
- lib/zookeeper-3.4.10.jar

Did anyone noticed those when you upgraded the curator version?

~~~~
Error: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error in custom provider, java.lang.NoSuchMethodError: org.apache.curator.CuratorZookeeperClient.<init>(Lorg/apache/curator/utils/ZookeeperFactory;Lorg/apache/curator/ensemble/EnsembleProvider;IILorg/apache/zookeeper/Watcher;Lorg/apache/curator/RetryPolicy;ZLorg/apache/curator/connection/ConnectionHandlingPolicy;)V
  at io.druid.curator.CuratorModule.makeCurator(CuratorModule.java:75) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.curator.CuratorModule)
  at io.druid.curator.CuratorModule.makeCurator(CuratorModule.java:75) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.curator.CuratorModule)
  while locating org.apache.curator.framework.CuratorFramework
    for field at io.druid.curator.discovery.DiscoveryModule$DruidLeaderSelectorProvider.curatorFramework(DiscoveryModule.java:511)
  at io.druid.curator.discovery.DiscoveryModule.configure(DiscoveryModule.java:192) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.curator.discovery.DiscoveryModule)

2) Error in custom provider, java.lang.NoSuchMethodError: org.apache.curator.CuratorZookeeperClient.<init>(Lorg/apache/curator/utils/ZookeeperFactory;Lorg/apache/curator/ensemble/EnsembleProvider;IILorg/apache/zookeeper/Watcher;Lorg/apache/curator/RetryPolicy;ZLorg/apache/curator/connection/ConnectionHandlingPolicy;)V
  at io.druid.curator.CuratorModule.makeCurator(CuratorModule.java:75) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.curator.CuratorModule)
  at io.druid.curator.CuratorModule.makeCurator(CuratorModule.java:75) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.curator.CuratorModule)
  while locating org.apache.curator.framework.CuratorFramework
    for field at io.druid.curator.discovery.DiscoveryModule$DruidLeaderSelectorProvider.curatorFramework(DiscoveryModule.java:511)
  at io.druid.curator.discovery.DiscoveryModule.configure(DiscoveryModule.java:199) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.curator.discovery.DiscoveryModule)

2 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:176)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at io.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:401)
	at io.druid.indexer.HadoopDruidIndexerConfig.<clinit>(HadoopDruidIndexerConfig.java:104)
	at io.druid.indexer.HadoopDruidIndexerMapper.setup(HadoopDruidIndexerMapper.java:48)
	at io.druid.indexer.IndexGeneratorJob$IndexGeneratorMapper.setup(IndexGeneratorJob.java:266)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:143)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:796)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:342)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: java.lang.NoSuchMethodError: org.apache.curator.CuratorZookeeperClient.<init>(Lorg/apache/curator/utils/ZookeeperFactory;Lorg/apache/curator/ensemble/EnsembleProvider;IILorg/apache/zookeeper/Watcher;Lorg/apache/curator/RetryPolicy;ZLorg/apache/curator/connection/ConnectionHandlingPolicy;)V
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.<init>(CuratorFrameworkImpl.java:132)
	at org.apache.curator.framework.CuratorFrameworkFactory$Builder.build(CuratorFrameworkFactory.java:158)
	at io.druid.curator.CuratorModule.makeCurator(CuratorModule.java:82)
	at io.druid.curator.CuratorModule$$FastClassByGuice$$7ca37876.invoke(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
	at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401)
	at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:93)
	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:80)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:80)
	at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:223)
	at com.google.inject.internal.Initializer.injectAll(Initializer.java:132)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:174)
	... 16 more
~~~~

**Comment by gianm** [comment]
Hi @klamouri, I'm not aware of this issue being reported before. I think there are a number of people doing hadoop ingestion successfully with 0.11.0-rc2 though. Maybe they are all using the index_hadoop task. It could be some difference in classloading between the task and the cli version.

When I look at the distro I see a few files that are other versions of curator. Maybe there is a mismatch of some sort:

```
hadoop-dependencies/hadoop-client/2.7.3/curator-client-2.7.1.jar
hadoop-dependencies/hadoop-client/2.7.3/curator-framework-2.7.1.jar
hadoop-dependencies/hadoop-client/2.7.3/curator-recipes-2.7.1.jar
```

@klamouri what happens if you remove these files? Or try using the task instead of the cli?

@himanshug (or someone else with relevant experience) could you please comment on how you have been running 0.11.0 with hadoop?

**Comment by himanshug** [comment]
In our case we have custom hadoop client jars deployed independent of druid based on hadoop version on our hadoop grids, but that is very much same as open source hadoop except for some Yahoo-isms.

We use HadoopIndexTask , and druid process classpath  looks like "druid core jars , druid conf, hadoop jars"
we also add following properties to druid config...

druid.indexer.task.defaultHadoopCoordinates=[]
druid.extensions.addExtensionsToHadoopContainer=true
druid.indexer.fork.property.hadoop.mapreduce.job.classloader=true
druid.extensions.hadoopContainerDruidClasspath="druid core jars, druid conf"

above setup works fine for all my users. hope that helps.

**Comment by klamouri** [comment]
Hi all,

Thanks for your help.

Just removing those jar wasn't enough since I'm running the CLI on an EMR cluster. 

~~~~
hadoop-dependencies/hadoop-client/2.7.3/curator-client-2.7.1.jar
hadoop-dependencies/hadoop-client/2.7.3/curator-framework-2.7.1.jar
hadoop-dependencies/hadoop-client/2.7.3/curator-recipes-2.7.1.jar
~~~~

So I also removed all those files:

~~~~
/home/hadoop/.m2/repository/org/apache/curator/apache-curator/2.7.1/apache-curator-2.7.1.pom
/home/hadoop/.m2/repository/org/apache/curator/apache-curator/2.7.1/apache-curator-2.7.1.pom.sha1
/home/hadoop/.m2/repository/org/apache/curator/apache-curator/2.7.1/apache-curator-2.7.1.pom.md5
/home/hadoop/.m2/repository/org/apache/curator/curator-client
/home/hadoop/.m2/repository/org/apache/curator/curator-client/2.7.1/curator-client-2.7.1.pom.sha1
/home/hadoop/.m2/repository/org/apache/curator/curator-client/2.7.1/curator-client-2.7.1.jar.md5
/home/hadoop/.m2/repository/org/apache/curator/curator-client/2.7.1/curator-client-2.7.1.pom.md5
/home/hadoop/.m2/repository/org/apache/curator/curator-client/2.7.1/curator-client-2.7.1.jar.sha1
/home/hadoop/.m2/repository/org/apache/curator/curator-client/2.7.1/curator-client-2.7.1.jar
/home/hadoop/.m2/repository/org/apache/curator/curator-client/2.7.1/curator-client-2.7.1.pom
/home/hadoop/.m2/repository/org/apache/curator/curator-framework
/home/hadoop/.m2/repository/org/apache/curator/curator-framework/2.7.1/curator-framework-2.7.1.jar
/home/hadoop/.m2/repository/org/apache/curator/curator-framework/2.7.1/curator-framework-2.7.1.pom
/home/hadoop/.m2/repository/org/apache/curator/curator-framework/2.7.1/curator-framework-2.7.1.pom.md5
/home/hadoop/.m2/repository/org/apache/curator/curator-framework/2.7.1/curator-framework-2.7.1.pom.sha1
/home/hadoop/.m2/repository/org/apache/curator/curator-framework/2.7.1/curator-framework-2.7.1.jar.md5
/home/hadoop/.m2/repository/org/apache/curator/curator-framework/2.7.1/curator-framework-2.7.1.jar.sha1
/home/hadoop/.m2/repository/org/apache/curator/curator-recipes
/home/hadoop/.m2/repository/org/apache/curator/curator-recipes/2.7.1/curator-recipes-2.7.1.jar.sha1
/home/hadoop/.m2/repository/org/apache/curator/curator-recipes/2.7.1/curator-recipes-2.7.1.pom
/home/hadoop/.m2/repository/org/apache/curator/curator-recipes/2.7.1/curator-recipes-2.7.1.jar
/home/hadoop/.m2/repository/org/apache/curator/curator-recipes/2.7.1/curator-recipes-2.7.1.pom.md5
/home/hadoop/.m2/repository/org/apache/curator/curator-recipes/2.7.1/curator-recipes-2.7.1.jar.md5
/home/hadoop/.m2/repository/org/apache/curator/curator-recipes/2.7.1/curator-recipes-2.7.1.pom.sha1
/usr/lib/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/curator-framework-2.7.1.jar
/usr/lib/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/curator-recipes-2.7.1.jar
/usr/lib/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/curator-client-2.7.1.jar
/usr/lib/pig/lib/spark/curator-client-2.4.0.jar
/usr/lib/pig/lib/spark/curator-framework-2.4.0.jar
/usr/lib/pig/lib/spark/curator-recipes-2.4.0.jar
/usr/lib/hbase/lib/curator-framework-2.7.1.jar
/usr/lib/hbase/lib/curator-recipes-2.7.1.jar
/usr/lib/hbase/lib/curator-client-2.7.1.jar
/usr/lib/hadoop/lib/curator-framework-2.7.1.jar
/usr/lib/hadoop/lib/curator-recipes-2.7.1.jar
/usr/lib/hadoop/lib/curator-client-2.7.1.jar
/usr/lib/hadoop/client/curator-framework-2.7.1.jar
/usr/lib/hadoop/client/curator-recipes-2.7.1.jar
/usr/lib/hadoop/client/curator-framework.jar
/usr/lib/hadoop/client/curator-recipes.jar
/usr/lib/hadoop/client/curator-client.jar
/usr/lib/hadoop/client/curator-client-2.7.1.jar
/usr/lib/hive/lib/apache-curator-2.7.1.pom
/usr/lib/hive/lib/curator-x-discovery-2.11.0.jar
/usr/lib/hive/lib/curator-framework-2.7.1.jar
/usr/lib/hive/lib/curator-recipes-2.7.1.jar
/usr/lib/hive/lib/curator-client-2.7.1.jar
/usr/lib/hadoop-mapreduce/curator-framework-2.7.1.jar
/usr/lib/hadoop-mapreduce/curator-recipes-2.7.1.jar
/usr/lib/hadoop-mapreduce/curator-client-2.7.1.jar
/usr/lib/hadoop-kms/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/curator-framework-2.7.1.jar
/usr/lib/hadoop-kms/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/curator-recipes-2.7.1.jar
/usr/lib/hadoop-kms/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/curator-client-2.7.1.jar
/usr/share/aws/emr/hadoop-state-pusher/lib/curator-framework-2.7.1.jar
/usr/share/aws/emr/hadoop-state-pusher/lib/curator-recipes-2.7.1.jar
/usr/share/aws/emr/hadoop-state-pusher/lib/curator-client-2.7.1.jar
/usr/share/aws/emr/instance-controller/lib/curator-framework-3.1.0.jar
/usr/share/aws/emr/instance-controller/lib/curator-recipes-3.1.0.jar
/usr/share/aws/emr/instance-controller/lib/curator-client-3.1.0.jar
/mnt/var/lib/hadoop-httpfs/tomcat-deployment/webapps/webhdfs/WEB-INF/lib/curator-framework-2.7.1.jar
/mnt/var/lib/hadoop-httpfs/tomcat-deployment/webapps/webhdfs/WEB-INF/lib/curator-recipes-2.7.1.jar
/mnt/var/lib/hadoop-httpfs/tomcat-deployment/webapps/webhdfs/WEB-INF/lib/curator-client-2.7.1.jar
~~~~
