### ISSUE TITLE
MySQL语法解析错误

### ISSUE THREAD

**Issue by ChenMingHe** [druid-io/druid#5196]
## 版本

1.1.6

## 错误的SQL语句

```sql
CREATE TABLE `service_template` (
  `service_code` varchar(48) NOT NULL DEFAULT '' COMMENT '服务码，代表业务',
  CONSTRAINT `service_code_relation` FOREIGN KEY (`service_code`) REFERENCES `service_code` (`service_code`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=384 DEFAULT CHARSET=utf8
;
```

## 错误堆栈

在解析到 `ON UPDATE NO ACTION`这里的时候出错:

```
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, expect ACTION, actual IDENTIFIER pos 571, line 9, column 138, token IDENTIFIER NO
	at com.alibaba.druid.sql.parser.SQLExprParser.parseReferenceOption(SQLExprParser.java:2682)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.parseForeignKey(MySqlExprParser.java:829)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseConstraint(MySqlCreateTableParser.java:869)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCreateTable(MySqlCreateTableParser.java:124)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:244)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:159)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:70)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:464)
```

## 错误位置

定位到: com.alibaba.druid.sql.parser.SQLExprParser#parseReferenceOption

![image](https://user-images.githubusercontent.com/1975542/34353676-8a7df542-ea64-11e7-9e9e-4002d303351a.png)

这里的代码解析有问题

**Comment by leventov** [comment]
This issue belongs to this repo: https://github.com/alibaba/druid, please create one there.
