### ISSUE TITLE
druid 0.11.0 reindex task failed with apache hadoop 2.7.3

### ISSUE THREAD

**Issue by quenlang** [druid-io/druid#5251]
**@jon-wei
As we konw Druid build against Hadoop 2.7.3 libraries after 0.10.1 , but there is a problem when i using 0.11.0 .
hadoop cluster env**
```
[root@hap ~]# java -version 
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

[root@hap ~]# hadoop version
Hadoop 2.7.3
Subversion https://git-wip-us.apache.org/repos/asf/hadoop.git -r baa91f7c6bc9cb92be5982de4719c1c8af91ccff
Compiled by root on 2016-08-18T01:41Z
Compiled with protoc 2.5.0
From source with checksum 2e4ce5f957ea4db193bce3734ff29ff4
```

**my reindex task spec file**
```
{
    "type": "index_hadoop",
    "spec": {
        "dataSchema": {
            "dataSource": "brs_pv_min",
            "parser": {
                "type": "hadoopyString",
                "parseSpec": {
                    "format": "json",
                    "timestampSpec": {
                        "column": "timestamp",
                        "format": "posix"
                    },
                    "dimensionsSpec": {
                        "dimensions": [
                            "browser_application_id",
                            "application_id"
                        ]
                    }
                }
            },
            "metricsSpec": [
                {
                    "name": "counter",
                    "type": "count"
                }
            ],
            "granularitySpec": {
                "type": "uniform",
                "queryGranularity": "MINUTE",
		 "intervals": [ "2018-01-10T00:00:00Z/2018-01-11T00:00:00Z" ]
            }
        },
        "ioConfig": {
            "type": "hadoop",
            "inputSpec": {
                "type": "dataSource",
                "ingestionSpec": {
                    "dataSource": "brs_pv_min",
                    "intervals": [ "2018-01-10T00:00:00Z/2018-01-11T00:00:00Z" ]
                }
            }
        },
        "tuningConfig": {
            "type": "hadoop",
            "partitionsSpec": {
                "type": "hashed",
                "numShards": 1
            },
            "buildV9Directly": "true"
        }
    }
}
```
**Then i launched the task , but problem occur.**
```
2018-01-11T23:30:16,923 INFO [task-runner-0-priority-0] org.apache.hadoop.mapreduce.Job - Running job: job_1515662631039_0006
2018-01-11T23:31:07,260 INFO [task-runner-0-priority-0] org.apache.hadoop.mapred.ClientServiceDelegate - Application state is completed. FinalApplicationStatus=FAILED. Redirecting to job history server
2018-01-11T23:31:07,445 INFO [task-runner-0-priority-0] org.apache.hadoop.mapreduce.Job - Job job_1515662631039_0006 running in uber mode : false
2018-01-11T23:31:07,471 INFO [task-runner-0-priority-0] org.apache.hadoop.mapreduce.Job -  map 0% reduce 0%
2018-01-11T23:31:07,707 INFO [task-runner-0-priority-0] org.apache.hadoop.mapreduce.Job - Task Id : attempt_1515662631039_0006_m_000000_0, Status : FAILED
Error: com.google.inject.util.Types.collectionOf(Ljava/lang/reflect/Type;)Ljava/lang/reflect/ParameterizedType;
2018-01-11T23:31:07,816 INFO [task-runner-0-priority-0] org.apache.hadoop.mapreduce.Job - Task Id : attempt_1515662631039_0006_m_000001_0, Status : FAILED
Error: com.google.inject.util.Types.collectionOf(Ljava/lang/reflect/Type;)Ljava/lang/reflect/ParameterizedType;
2018-01-11T23:31:07,826 INFO [task-runner-0-priority-0] org.apache.hadoop.mapreduce.Job - Task Id : attempt_1515662631039_0006_m_000002_0, Status : FAILED
Error: com.google.inject.util.Types.collectionOf(Ljava/lang/reflect/Type;)Ljava/lang/reflect/ParameterizedType;
2018-01-11T23:31:07,836 INFO [task-runner-0-priority-0] org.apache.hadoop.mapreduce.Job - Task Id : attempt_1515662631039_0006_m_000003_0, Status : FAILED
Error: com.google.inject.util.Types.collectionOf(Ljava/lang/reflect/Type;)Ljava/lang/reflect/ParameterizedType;
2018-01-11T23:31:07,840 INFO [task-runner-0-priority-0] org.apache.hadoop.mapreduce.Job - Task Id : attempt_1515662631039_0006_m_000001_1, Status : FAILED
Error: com.google.inject.util.Types.collectionOf(Ljava/lang/reflect/Type;)Ljava/lang/reflect/ParameterizedType;
2018-01-11T23:31:07,846 INFO [task-runner-0-priority-0] org.apache.hadoop.mapreduce.Job - Task Id : attempt_1515662631039_0006_m_000000_1, Status : FAILED
Error: com.google.inject.util.Types.collectionOf(Ljava/lang/reflect/Type;)Ljava/lang/reflect/ParameterizedType;
2018-01-11T23:31:07,863 INFO [task-runner-0-priority-0] org.apache.hadoop.mapreduce.Job - Task Id : attempt_1515662631039_0006_m_000002_1, Status : FAILED
Error: com.google.inject.util.Types.collectionOf(Ljava/lang/reflect/Type;)Ljava/lang/reflect/ParameterizedType;
2018-01-11T23:31:07,887 INFO [task-runner-0-priority-0] org.apache.hadoop.mapreduce.Job - Task Id : attempt_1515662631039_0006_m_000003_1, Status : FAILED
Error: com.google.inject.util.Types.collectionOf(Ljava/lang/reflect/Type;)Ljava/lang/reflect/ParameterizedType;
2018-01-11T23:31:07,897 INFO [task-runner-0-priority-0] org.apache.hadoop.mapreduce.Job - Task Id : attempt_1515662631039_0006_m_000001_2, Status : FAILED
Error: com.google.inject.util.Types.collectionOf(Ljava/lang/reflect/Type;)Ljava/lang/reflect/ParameterizedType;
2018-01-11T23:31:07,901 INFO [task-runner-0-priority-0] org.apache.hadoop.mapreduce.Job - Task Id : attempt_1515662631039_0006_m_000000_2, Status : FAILED
Error: com.google.inject.util.Types.collectionOf(Ljava/lang/reflect/Type;)Ljava/lang/reflect/ParameterizedType;
2018-01-11T23:31:07,926 INFO [task-runner-0-priority-0] org.apache.hadoop.mapreduce.Job - Job job_1515662631039_0006 failed with state FAILED due to: 
2018-01-11T23:31:08,164 ERROR [task-runner-0-priority-0] io.druid.indexing.overlord.ThreadPoolTaskRunner - Exception while running task[HadoopIndexTask{id=index_hadoop_brs_pv_min_2018-01-11T15:28:02.836Z, type=index_hadoop, dataSource=brs_pv_min}]
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-16.0.1.jar:?]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:218) ~[druid-indexing-service-0.11.0.jar:0.11.0]
	at io.druid.indexing.common.task.HadoopIndexTask.run(HadoopIndexTask.java:226) ~[druid-indexing-service-0.11.0.jar:0.11.0]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:436) [druid-indexing-service-0.11.0.jar:0.11.0]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:408) [druid-indexing-service-0.11.0.jar:0.11.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:215) ~[druid-indexing-service-0.11.0.jar:0.11.0]
	... 7 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at io.druid.indexer.IndexGeneratorJob.run(IndexGeneratorJob.java:220) ~[druid-indexing-hadoop-0.11.0.jar:0.11.0]
	at io.druid.indexer.JobHelper.runJobs(JobHelper.java:368) ~[druid-indexing-hadoop-0.11.0.jar:0.11.0]
	at io.druid.indexer.HadoopDruidIndexerJob.run(HadoopDruidIndexerJob.java:95) ~[druid-indexing-hadoop-0.11.0.jar:0.11.0]
	at io.druid.indexing.common.task.HadoopIndexTask$HadoopIndexGeneratorInnerProcessing.runTask(HadoopIndexTask.java:279) ~[druid-indexing-service-0.11.0.jar:0.11.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:215) ~[druid-indexing-service-0.11.0.jar:0.11.0]
	... 7 more
Caused by: java.lang.NullPointerException
	at io.druid.indexer.IndexGeneratorJob.run(IndexGeneratorJob.java:214) ~[druid-indexing-hadoop-0.11.0.jar:0.11.0]
	at io.druid.indexer.JobHelper.runJobs(JobHelper.java:368) ~[druid-indexing-hadoop-0.11.0.jar:0.11.0]
	at io.druid.indexer.HadoopDruidIndexerJob.run(HadoopDruidIndexerJob.java:95) ~[druid-indexing-hadoop-0.11.0.jar:0.11.0]
	at io.druid.indexing.common.task.HadoopIndexTask$HadoopIndexGeneratorInnerProcessing.runTask(HadoopIndexTask.java:279) ~[druid-indexing-service-0.11.0.jar:0.11.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:215) ~[druid-indexing-service-0.11.0.jar:0.11.0]
	... 7 more
2018-01-11T23:31:08,290 INFO [task-runner-0-priority-0] io.druid.indexing.overlord.TaskRunnerUtils - Task [index_hadoop_brs_pv_min_2018-01-11T15:28:02.836Z] status changed to [FAILED].
2018-01-11T23:31:08,341 INFO [task-runner-0-priority-0] io.druid.indexing.worker.executor.ExecutorLifecycle - Task completed with status: {
  "id" : "index_hadoop_brs_pv_min_2018-01-11T15:28:02.836Z",
  "status" : "FAILED",
  "duration" : 119987
}
```

**I had try adding mapreduce.job.classloader = true or mapreduce.job.user.classpath.first = true to the tuningConfig -> jobProperties of the ingestion spec , but it does not work .
Any ideas ?**

**Thanks !
Best wishes !**

**Comment by jon-wei** [comment]
@quenlang Do you have any `druid.indexer.task.defaultHadoopCoordinates` configurations in your properties that aren't hadoop 2.7.3?

**Comment by quenlang** [comment]
@jon-wei There is only one option in middelManager runtime configuration file and it is point to hadoop 2.7.3 .
```
[root@gpsegment1 druid-0.11.0]# grep  "druid.indexer.task.defaultHadoopCoordinates" ./* -r  --color 
./conf/druid/middleManager/runtime.properties:druid.indexer.task.defaultHadoopCoordinates=["org.apache.hadoop:hadoop-client:2.7.3"]
```

**Comment by jon-wei** [comment]
@quenlang Can you provide more info on how the hadoop environment was created/configured and what extensions you have loaded? 

I've run 0.11.0 against 2.7.3 hadoop successfully with ` mapreduce.job.user.classpath.first = true` (hadoop was running in docker, using https://hub.docker.com/r/sequenceiq/hadoop-docker/~/dockerfile/ modified to install 2.7.3 instead)

**Comment by quenlang** [comment]
@jon-wei I'm so sorry. It's my mistake. I've try again with the option ```mapreduce.job.user.classpath.first = true``` and it worked very well.
Configurations:
```
        "tuningConfig": {
            "type": "hadoop",
            "jobProperties": {
                "mapreduce.job.user.classpath.first": "true",
                "mapreduce.map.memory.mb": 256,
                "mapreduce.map.java.opts": "-server -Xmx512m -Duser.timezone=UTC+08:00 -Dfile.encoding=UTF-8",
                "mapreduce.reduce.memory.mb": 512,
                "mapreduce.reduce.java.opts": "-server -Xmx1g -Duser.timezone=UTC+08:00 -Dfile.encoding=UTF-8"
            },
            "partitionsSpec": {
                "type": "hashed",
                "numShards": 1
            },
            "buildV9Directly": "true"
        }
```
The problem i saw two days ago maybe be caused by the unnormal status of druid cluster or too big size of mapreduce.map/reduce.memory.mb options, but i'm not sure and it does not reapper.

Thank you so much !

**Comment by jon-wei** [comment]
Cool, good to hear it's working!
