### ISSUE TITLE
YarnChild cannot be started due to java.lang.NoSuchMethodError: io.druid.guice.PolyBind.createChoiceWithDefault

### ISSUE THREAD

**Issue by xy-xin** [druid-io/druid#5292]
I built druid-0.11.0, and run the example batch indexing job, however i got an exception:
```
2018-01-24 18:09:28,827 INFO [main] org.apache.hadoop.mapred.MapTask: Starting flush of map output
2018-01-24 18:09:28,836 INFO [main] org.apache.hadoop.io.compress.zlib.ZlibFactory: Successfully loaded & initialized native-zlib library
2018-01-24 18:09:28,837 INFO [main] org.apache.hadoop.io.compress.CodecPool: Got brand-new compressor [.deflate]
2018-01-24 18:09:28,844 FATAL [main] org.apache.hadoop.mapred.YarnChild: Error running child : java.lang.NoSuchMethodError: io.druid.guice.PolyBind.createChoiceWithDefault(Lcom/google/inject/Binder;Ljava/lang/String;Lcom/google/inject/Key;Ljava/lang/String;)Lcom/google/inject/binder/ScopedBindingBuilder;
	at io.druid.curator.discovery.DiscoveryModule.configure(DiscoveryModule.java:165)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at io.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:401)
	at io.druid.indexer.HadoopDruidIndexerConfig.<clinit>(HadoopDruidIndexerConfig.java:104)
	at io.druid.indexer.HadoopDruidIndexerMapper.setup(HadoopDruidIndexerMapper.java:48)
	at io.druid.indexer.DetermineHashedPartitionsJob$DetermineCardinalityMapper.setup(DetermineHashedPartitionsJob.java:227)
	at io.druid.indexer.DetermineHashedPartitionsJob$DetermineCardinalityMapper.run(DetermineHashedPartitionsJob.java:285)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1727)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
```
I have copied the hadoop xml files to druid-conf/druid/_common/, and turned on "mapreduce.job.classloader".

From the log, it seems it's not a hadoop jar problem. I suspect that it loaded the druid-api-0.9.1.jar (which was published in druid-hdfs-storage) other than what i expect druid-api-0.11.0.jar, but I'm not sure if my analysis was right or not. Can anyone gives me some hint?

Thanks.

**Comment by xy-xin** [comment]
I found it is because the druid jars' version is different with those in druid_home/lib. now i rebuild the project and get a consistent version. 

Close it.
