### ISSUE TITLE
Publishing segments with Kafka Index service failed

### ISSUE THREAD

**Issue by herlenashavi** [druid-io/druid#5420]
Hi,

I'm using Druid's Kafka indexing service to ingest data from Kafka into Druid. After running for about 10 hours I see some ingestion tasks failing with the following error.

Druid Version: 0.11.0
HDFS Version: 2.7.4 (Should this be 2.7.3 since the hadoop client being used in Druid 0.11.0 is 2.7.3?)

```
io.druid.java.util.common.ISE: Transaction failure publishing segments, aborting
	at io.druid.indexing.kafka.KafkaIndexTask.run(KafkaIndexTask.java:589) ~[?:?]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:436) [druid-indexing-service-0.11.0.jar:0.11.0]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:408) [druid-indexing-service-0.11.0.jar:0.11.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
2018-02-23T13:10:06,384 INFO [task-runner-0-priority-0] io.druid.indexing.overlord.TaskRunnerUtils - Task [index_kafka_table_dea2181c87cb11b_cpmmkfgp] status changed to [FAILED].
2018-02-23T13:10:06,387 INFO [task-runner-0-priority-0] io.druid.indexing.worker.executor.ExecutorLifecycle - Task completed with status: {
  "id" : "index_kafka_table_dea2181c87cb11b_cpmmkfgp",
  "status" : "FAILED",
  "duration" : 623346
}
```

I see a whole bunch of HDFS errors reported in the task logs about failure to rename temp index file.

```
2018-02-23T13:10:03,648 INFO [appenderator_merge_0] io.druid.storage.hdfs.HdfsDataSegmentPusher - Unable to rename temp Index file[hdfs://192.200.101.101:54310/druid/segments/table/6913119fe3764213bef1b26fa4258380/115_descriptor.json] to final segment path [hdfs://192.200.101.101:54310/druid/segments/table/20180223T123000.000Z_20180223T124000.000Z/2018-02-23T12_30_01.070Z/115_descriptor.json]. It is already pushed by a replica task.
2018-02-23T13:10:03,650 WARN [appenderator_merge_0] org.apache.hadoop.fs.HadoopFsWrapper - Failed to rename [hdfs://192.200.101.101:54310/druid/segments/table/6913119fe3764213bef1b26fa4258380/115_index.zip] to [hdfs://192.200.101.101:54310/druid/segments/table/20180223T123000.000Z_20180223T124000.000Z/2018-02-23T12_30_01.070Z/115_index.zip].
org.apache.hadoop.fs.FileAlreadyExistsException: rename destination /druid/segments/table/20180223T123000.000Z_20180223T124000.000Z/2018-02-23T12_30_01.070Z/115_index.zip already exists
	at org.apache.hadoop.hdfs.server.namenode.FSDirRenameOp.validateOverwrite(FSDirRenameOp.java:539)
	at org.apache.hadoop.hdfs.server.namenode.FSDirRenameOp.unprotectedRenameTo(FSDirRenameOp.java:382)
	at org.apache.hadoop.hdfs.server.namenode.FSDirRenameOp.renameTo(FSDirRenameOp.java:299)
	at org.apache.hadoop.hdfs.server.namenode.FSDirRenameOp.renameToInt(FSDirRenameOp.java:244)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.renameTo(FSNamesystem.java:3638)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.rename2(NameNodeRpcServer.java:914)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.rename2(ClientNamenodeProtocolServerSideTranslatorPB.java:599)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:982)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2217)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2213)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1746)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2213)

	at sun.reflect.GeneratedConstructorAccessor78.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_151]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_151]
	at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:106) ~[?:?]
	at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:73) ~[?:?]
	at org.apache.hadoop.hdfs.DFSClient.rename(DFSClient.java:1991) ~[?:?]
	at org.apache.hadoop.hdfs.DistributedFileSystem.rename(DistributedFileSystem.java:659) ~[?:?]
	at org.apache.hadoop.fs.HadoopFsWrapper.rename(HadoopFsWrapper.java:51) ~[?:?]
	at io.druid.storage.hdfs.HdfsDataSegmentPusher.copyFilesWithChecks(HdfsDataSegmentPusher.java:167) ~[?:?]
	at io.druid.storage.hdfs.HdfsDataSegmentPusher.push(HdfsDataSegmentPusher.java:149) ~[?:?]
	at io.druid.segment.realtime.appenderator.AppenderatorImpl.lambda$mergeAndPush$0(AppenderatorImpl.java:610) ~[druid-server-0.11.0.jar:0.11.0]
	at io.druid.java.util.common.RetryUtils.retry(RetryUtils.java:63) [java-util-0.11.0.jar:0.11.0]
	at io.druid.java.util.common.RetryUtils.retry(RetryUtils.java:81) [java-util-0.11.0.jar:0.11.0]
	at io.druid.segment.realtime.appenderator.AppenderatorImpl.mergeAndPush(AppenderatorImpl.java:609) [druid-server-0.11.0.jar:0.11.0]
	at io.druid.segment.realtime.appenderator.AppenderatorImpl.access$600(AppenderatorImpl.java:100) [druid-server-0.11.0.jar:0.11.0]
	at io.druid.segment.realtime.appenderator.AppenderatorImpl$3.apply(AppenderatorImpl.java:496) [druid-server-0.11.0.jar:0.11.0]
	at io.druid.segment.realtime.appenderator.AppenderatorImpl$3.apply(AppenderatorImpl.java:484) [druid-server-0.11.0.jar:0.11.0]
	at com.google.common.util.concurrent.Futures$1.apply(Futures.java:713) [guava-16.0.1.jar:?]
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:861) [guava-16.0.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: org.apache.hadoop.ipc.RemoteException: rename destination /druid/segments/table/20180223T123000.000Z_20180223T124000.000Z/2018-02-23T12_30_01.070Z/115_index.zip already exists
	at org.apache.hadoop.hdfs.server.namenode.FSDirRenameOp.validateOverwrite(FSDirRenameOp.java:539)
	at org.apache.hadoop.hdfs.server.namenode.FSDirRenameOp.unprotectedRenameTo(FSDirRenameOp.java:382)
	at org.apache.hadoop.hdfs.server.namenode.FSDirRenameOp.renameTo(FSDirRenameOp.java:299)
	at org.apache.hadoop.hdfs.server.namenode.FSDirRenameOp.renameToInt(FSDirRenameOp.java:244)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.renameTo(FSNamesystem.java:3638)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.rename2(NameNodeRpcServer.java:914)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.rename2(ClientNamenodeProtocolServerSideTranslatorPB.java:599)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:982)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2217)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2213)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1746)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2213)

	at org.apache.hadoop.ipc.Client.call(Client.java:1475) ~[?:?]
	at org.apache.hadoop.ipc.Client.call(Client.java:1412) ~[?:?]
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229) ~[?:?]
	at com.sun.proxy.$Proxy64.rename2(Unknown Source) ~[?:?]
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.rename2(ClientNamenodeProtocolTranslatorPB.java:513) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor129.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191) ~[?:?]
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102) ~[?:?]
	at com.sun.proxy.$Proxy65.rename2(Unknown Source) ~[?:?]
	at org.apache.hadoop.hdfs.DFSCl
```

Has anyone else hit this issue? I see this was a bug in a previous version of Druid which was fixed #3786. Is this an issue with the Hadoop version(2.7.4) I'm using?

**Comment by herlenashavi** [comment]
Just an update, I tried testing this with Hadoop version 2.7.1 and HadoopFSWrapper compiled with hadoop 2.3.0. Still get the same error. While using Druid 0.11.0, which version of Hadoop client (2.3.0 or 2.4.0) is recommended with HDFS version 2.7.1?

**Comment by herlenashavi** [comment]
Found this [post](https://groups.google.com/forum/#!msg/druid-user/mFRYT2dRS7g/XUDWIPjhAwAJ) which answers my question.
