### ISSUE TITLE
NPE while processing taskAnnouncement in RemoteTaskRunner

### ISSUE THREAD

**Issue by jihoonson** [druid-io/druid#5506]
Introduced in #5260.

```
2018-03-20T01:11:54,944 ERROR [Curator-PathChildrenCache-1] io.druid.indexing.overlord.RemoteTaskRunner - Failed to handle new worker status: {class=io.druid.indexing.overlord.RemoteTaskRunner, exceptionType=class java.lang.NullPointerException, exceptionMessage=null, worker=jihoons-mbp:8091, znode=/druid/indexer/status/jihoons-mbp:8091/parallelIndexSinglePhaseSubIndex_lineitem_2018-03-20T01:11:54.927Z}
java.lang.NullPointerException
        at io.druid.indexing.overlord.RemoteTaskRunner$6.childEvent(RemoteTaskRunner.java:971) [druid-indexing-service-0.13.0-SNAPSHOT.jar:0.13.0-SNAPSHOT]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:520) [curator-recipes-4.0.0.jar:4.0.0]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:514) [curator-recipes-4.0.0.jar:4.0.0]
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93) [curator-framework-4.0.0.jar:4.0.0]
        at org.apache.curator.shaded.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:296) [curator-client-4.0.0.jar:?]
        at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85) [curator-framework-4.0.0.jar:4.0.0]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache.callListeners(PathChildrenCache.java:512) [curator-recipes-4.0.0.jar:4.0.0]
        at org.apache.curator.framework.recipes.cache.EventOperation.invoke(EventOperation.java:35) [curator-recipes-4.0.0.jar:4.0.0]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$9.run(PathChildrenCache.java:771) [curator-recipes-4.0.0.jar:4.0.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Comment by jihoonson** [comment]
Looks that this happens only when there remain some tasks in ZooKeeper, but not in Overlord. This can happen if the overlord is restarted.
