### ISSUE TITLE
coordinator throws exception and loses leadership in 0.12.0

### ISSUE THREAD

**Issue by pdeva** [druid-io/druid#5561]
Exception:
```
2018-03-31 23:19:00,056 ERROR i.d.s.c.DruidCoordinator [Coordinator-Exec--0] Caught exception, ignoring so that schedule keeps going.: {class=io.druid.server.coordinator.DruidCoordinator, exceptionType=class java.lang.IllegalMonitorStateException, exceptionMessage=Called canStop() before start()}
java.lang.IllegalMonitorStateException: Called canStop() before start()
	at io.druid.concurrent.LifecycleLock$Sync.canStop(LifecycleLock.java:166) ~[druid-common-0.12.0.jar:0.12.0]
	at io.druid.concurrent.LifecycleLock.canStop(LifecycleLock.java:256) ~[druid-common-0.12.0.jar:0.12.0]
	at io.druid.metadata.SQLMetadataSegmentManager.stop(SQLMetadataSegmentManager.java:159) ~[druid-server-0.12.0.jar:0.12.0]
	at io.druid.server.coordinator.DruidCoordinator.stopBeingLeader(DruidCoordinator.java:584) ~[druid-server-0.12.0.jar:0.12.0]
	at io.druid.server.coordinator.DruidCoordinator.access$100(DruidCoordinator.java:96) ~[druid-server-0.12.0.jar:0.12.0]
	at io.druid.server.coordinator.DruidCoordinator$CoordinatorRunnable.run(DruidCoordinator.java:631) [druid-server-0.12.0.jar:0.12.0]
	at io.druid.server.coordinator.DruidCoordinator$3.call(DruidCoordinator.java:554) [druid-server-0.12.0.jar:0.12.0]
	at io.druid.server.coordinator.DruidCoordinator$3.call(DruidCoordinator.java:547) [druid-server-0.12.0.jar:0.12.0]
	at io.druid.java.util.common.concurrent.ScheduledExecutors$2.run(ScheduledExecutors.java:102) [java-util-0.12.0.jar:0.12.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

I do have coordinatorAsOverlord enabled fyi

**Comment by pdeva** [comment]
this seems to cause coordindator to lose its leadership, even though its the only coordinator instance running

**Comment by jon-wei** [comment]
This is fixed by: https://github.com/druid-io/druid/pull/5554
