### ISSUE TITLE
druid installation  os Mac osx High Sierra

### ISSUE THREAD

**Issue by HenryMiller** [druid-io/druid#5719]
Hello,
I am new to druid and would like to use it.
I just followed instruction on druid.io website  for a quickstart installation (http://druid.io/docs/0.12.0/tutorials/quickstart.html)

I downloaded and installed druid .0.12.0.
I downloaded and installed zookeeper 3.4.10.
I was able to start zookeeper via :
1) cp conf/zoo_sample.cfg conf/zoo.cfg
2) ./bin/zkServer.sh start
then I issued the following command under druid folder
bin/init 
and it worked fine by creating appropriate folders.
When I ran the commands to start DRUID services it failed with java noclassfound errors.
This is the first command

```
java `cat conf-quickstart/druid/historical/jvm.config | xargs` -cp "conf-quickstart/druid/_common:conf-quickstart/druid/historical:lib/*" io.druid.cli.Main server historical.
```

This is error raised by my MAC.

```
sudo java `cat conf-quickstart/druid/historical/jvm.config | xargs` -cp "conf-quickstart/druid/_common:conf-quickstart/druid/historical:lib/*" io.druid.cli.Main server historical
Password:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/Users/giovannimichielin/Downloads/druid-0.12.0/lib/guice-4.1.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2018-04-30T09:27:37,632 INFO [main] io.druid.guice.PropertiesModule - Loading properties from common.runtime.properties
2018-04-30T09:27:37,635 INFO [main] io.druid.guice.PropertiesModule - Loading properties from runtime.properties
2018-04-30T09:27:37,666 INFO [main] org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 5.1.3.Final
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1009)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at org.hibernate.validator.internal.engine.ConfigurationImpl.<init>(ConfigurationImpl.java:110)
	at org.hibernate.validator.internal.engine.ConfigurationImpl.<init>(ConfigurationImpl.java:86)
	at org.hibernate.validator.HibernateValidator.createGenericConfiguration(HibernateValidator.java:41)
	at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:276)
	at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:110)
	at io.druid.guice.ConfigModule.configure(ConfigModule.java:39)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at io.druid.guice.GuiceInjectors.makeStartupInjector(GuiceInjectors.java:60)
	at io.druid.cli.Main.main(Main.java:99)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 23 more
```

I am running Java "10".

MBP-di-Giovanni:druid-0.12.0 giovannimichielin$ java -version
java version "10" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)

Am I missing some prerequisite ?

Thanks 
Giovanni

**Comment by Dylan1312** [comment]
Hey @HenryMiller 

Druid currently requires Java8, there's an open Issue to support Java11 -> https://github.com/druid-io/druid/issues/5589

**Comment by HenryMiller** [comment]
Thank you Dylan!
I will try on a virtual Ubuntu machine then.
Thanks 
Giovanni

**Comment by drcrallen** [comment]
See https://github.com/druid-io/druid/issues/5589 for related info

**Comment by drcrallen** [comment]
This can be closed for now until https://github.com/druid-io/druid/issues/5589 is resolved
