### ISSUE TITLE
Druid 0.11 and Cloudera Hadoop

### ISSUE THREAD

**Issue by elukey** [druid-io/druid#5763]
Hi!

I am trying to upgrade Druid 0.10.0 to 0.11.0 but I am not able to successfully run an indexation job anymore, due to:

Error: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error in custom provider, java.lang.VerifyError: class com.fasterxml.jackson.datatype.guava.deser.HostAndPortDeserializer overrides final method deserialize.(Lcom/fasterxml/jacks
on/core/JsonParser;Lcom/fasterxml/jackson/databind/DeserializationContext;)Ljava/lang/Object;
  at io.druid.jackson.JacksonModule.jsonMapper(JacksonModule.java:46)
  at io.druid.jackson.JacksonModule.jsonMapper(JacksonModule.java:46)
  while locating com.fasterxml.jackson.databind.ObjectMapper annotated with interface io.druid.guice.annotations.Json
  while locating com.fasterxml.jackson.databind.ObjectMapper
    for the 1st parameter of io.druid.guice.JsonConfigurator.<init>(JsonConfigurator.java:67)
  at io.druid.guice.ConfigModule.configure(ConfigModule.java:40)
  while locating io.druid.guice.JsonConfigurator
    for the 2nd parameter of io.druid.guice.JsonConfigProvider.inject(JsonConfigProvider.java:188)
  at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:133)

We are running Hadoop 2.6.0 with Cloudera's CDH 5.10 distribution. We first ran into this issue with version 0.9 but it got solved by a colleague of mine via https://github.com/druid-io/druid/issues/2476#issuecomment-220712670.

I tried all the suggestions in http://druid.io/docs/0.11.0/operations/other-hadoop.html but it none of them works from my tests. I have even tried to manually build Druid (http://druid.io/docs/0.11.0/development/build.html), swapping the hadoop compile version from 2.7.3 to 2.6.0 in pom.xml and indexing-service/src/main/java/io/druid/indexing/common/config/TaskConfig.java, but then I got this error:

java.lang.NoSuchMethodError: com.google.common.base.Stopwatch.elapsedMillis()J at io.druid.indexer.DetermineHashedPartitionsJobTest.testDetermineHashedPartitions(DetermineHashedPartitionsJobTest.java:223)

(and 29 more)

The above seems to be a Guava version issue, so now I am wondering what would be the best path to follow since Druid should support Hadoop 2.6.0 from what I can read in the docs for 0.11.0. I haven't tried yet to lower down only the Jackson version in pom.xml since 0.11's version seems the same as 0.10's, and everything has been working fine so far.

Any help will be really appreciated!

Thanks in advance!

**Comment by elukey** [comment]
Tested lowering down hadoop.compile.version to 2.6.0 and rebuilt skipping tests, from what I can see nothing changes. Next test is to build with a lower version of Jackson.

**Comment by elukey** [comment]
It seems that the fault was ours, our version of the druid-hdfs-storage extension that we built to make Druid works in the previous versions doesn't work anymore. Indexing seems to work fine, sorry for the noise :)

Nit: Tranquillity seems still doing https://github.com/druid-io/tranquility/blob/master/core/src/main/scala/com/metamx/tranquility/druid/DruidEnvironment.scala#L28 that shouldn't be done anymore with Druid 0.11 afaics.
